// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package dbq

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const adminAuditLog = `-- name: AdminAuditLog :many
SELECT a.id, a.tenant_id, a.actor_type, a.actor_id, a.action, a.target_type, a.target_id, a.reason, a.ip, a.metadata, a.occurred_at, u.email AS actor_email
FROM audit_log a LEFT JOIN users u ON u.id = a.actor_id
WHERE ($1::uuid IS NULL OR a.tenant_id = $1)
  AND ($2::actor_type IS NULL OR a.actor_type = $2)
  AND ($3::bigint IS NULL OR a.id < $3)
ORDER BY a.id DESC
LIMIT $4
`

type AdminAuditLogParams struct {
	TenantID  *uuid.UUID
	ActorType *ActorType
	BeforeID  *int64
	Lim       int32
}

type AdminAuditLogRow struct {
	ID         int64
	TenantID   *uuid.UUID
	ActorType  ActorType
	ActorID    *uuid.UUID
	Action     string
	TargetType *string
	TargetID   *string
	Reason     *string
	Ip         *netip.Addr
	Metadata   []byte
	OccurredAt time.Time
	ActorEmail *string
}

func (q *Queries) AdminAuditLog(ctx context.Context, arg AdminAuditLogParams) ([]AdminAuditLogRow, error) {
	rows, err := q.db.Query(ctx, adminAuditLog,
		arg.TenantID,
		arg.ActorType,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminAuditLogRow
	for rows.Next() {
		var i AdminAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Reason,
			&i.Ip,
			&i.Metadata,
			&i.OccurredAt,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminDeliveryStats = `-- name: AdminDeliveryStats :many
SELECT status, count(*)::int AS n FROM webhook_deliveries WHERE created_at > $1 GROUP BY status
`

type AdminDeliveryStatsRow struct {
	Status DeliveryStatus
	N      int32
}

// Client webhook deliveries in the tenant since a time, by status.
func (q *Queries) AdminDeliveryStats(ctx context.Context, since time.Time) ([]AdminDeliveryStatsRow, error) {
	rows, err := q.db.Query(ctx, adminDeliveryStats, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminDeliveryStatsRow
	for rows.Next() {
		var i AdminDeliveryStatsRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminLastMessageAt = `-- name: AdminLastMessageAt :one
SELECT created_at FROM messages ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) AdminLastMessageAt(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, adminLastMessageAt)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const adminListTenants = `-- name: AdminListTenants :many
SELECT id, name, slug, legal_name, status, suspended_reason, default_locale, timezone, message_retention_days, created_at, updated_at, meta_payment_mode, meta_payment_mode_since FROM tenants
WHERE ($1::tenant_status IS NULL OR status = $1)
  AND ($2::text IS NULL OR name ILIKE '%' || $2 || '%' OR slug ILIKE '%' || $2 || '%')
  AND ($3::timestamptz IS NULL OR (created_at, id) < ($3, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type AdminListTenantsParams struct {
	Status   *TenantStatus
	Search   *string
	BeforeAt *time.Time
	BeforeID *uuid.UUID
	Lim      int32
}

func (q *Queries) AdminListTenants(ctx context.Context, arg AdminListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, adminListTenants,
		arg.Status,
		arg.Search,
		arg.BeforeAt,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.LegalName,
			&i.Status,
			&i.SuspendedReason,
			&i.DefaultLocale,
			&i.Timezone,
			&i.MessageRetentionDays,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MetaPaymentMode,
			&i.MetaPaymentModeSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminMetaErrors = `-- name: AdminMetaErrors :many
SELECT id, tenant_id, method, path, http_status, code, subcode, message, fbtrace_id, occurred_at FROM meta_api_errors
WHERE ($1::uuid IS NULL OR tenant_id = $1)
  AND ($2::bigint IS NULL OR id < $2)
ORDER BY id DESC
LIMIT $3
`

type AdminMetaErrorsParams struct {
	TenantID *uuid.UUID
	BeforeID *int64
	Lim      int32
}

func (q *Queries) AdminMetaErrors(ctx context.Context, arg AdminMetaErrorsParams) ([]MetaApiError, error) {
	rows, err := q.db.Query(ctx, adminMetaErrors, arg.TenantID, arg.BeforeID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetaApiError
	for rows.Next() {
		var i MetaApiError
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Method,
			&i.Path,
			&i.HttpStatus,
			&i.Code,
			&i.Subcode,
			&i.Message,
			&i.FbtraceID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSetTenantStatus = `-- name: AdminSetTenantStatus :one
UPDATE tenants SET status = $1, suspended_reason = $2, updated_at = now() WHERE id = $3
RETURNING id, name, slug, legal_name, status, suspended_reason, default_locale, timezone, message_retention_days, created_at, updated_at, meta_payment_mode, meta_payment_mode_since
`

type AdminSetTenantStatusParams struct {
	Status TenantStatus
	Reason *string
	ID     uuid.UUID
}

func (q *Queries) AdminSetTenantStatus(ctx context.Context, arg AdminSetTenantStatusParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, adminSetTenantStatus, arg.Status, arg.Reason, arg.ID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LegalName,
		&i.Status,
		&i.SuspendedReason,
		&i.DefaultLocale,
		&i.Timezone,
		&i.MessageRetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MetaPaymentMode,
		&i.MetaPaymentModeSince,
	)
	return i, err
}

const adminTenantCounts = `-- name: AdminTenantCounts :one
SELECT (SELECT count(*) FROM memberships)::int AS members,
       (SELECT count(*) FROM phone_numbers WHERE status = 'connected')::int AS connected_numbers,
       (SELECT count(*) FROM phone_numbers)::int AS numbers,
       (SELECT coalesce(sum(sent), 0) FROM usage_daily WHERE day > current_date - 30)::int AS sent_30d,
       (SELECT coalesce(sum(received), 0) FROM usage_daily WHERE day > current_date - 30)::int AS received_30d
`

type AdminTenantCountsRow struct {
	Members          int32
	ConnectedNumbers int32
	Numbers          int32
	Sent30d          int32
	Received30d      int32
}

// Run inside the tenant: its size at a glance.
func (q *Queries) AdminTenantCounts(ctx context.Context) (AdminTenantCountsRow, error) {
	row := q.db.QueryRow(ctx, adminTenantCounts)
	var i AdminTenantCountsRow
	err := row.Scan(
		&i.Members,
		&i.ConnectedNumbers,
		&i.Numbers,
		&i.Sent30d,
		&i.Received30d,
	)
	return i, err
}

const adminTenantNumbers = `-- name: AdminTenantNumbers :many
SELECT p.id, p.display_phone_number, p.verified_name, p.status, p.quality_rating, p.messaging_limit_tier,
       p.is_coexistence, w.waba_id
FROM phone_numbers p JOIN whatsapp_accounts w ON w.id = p.whatsapp_account_id
ORDER BY p.created_at
`

type AdminTenantNumbersRow struct {
	ID                 uuid.UUID
	DisplayPhoneNumber string
	VerifiedName       *string
	Status             ConnectionStatus
	QualityRating      QualityRating
	MessagingLimitTier *string
	IsCoexistence      bool
	WabaID             string
}

func (q *Queries) AdminTenantNumbers(ctx context.Context) ([]AdminTenantNumbersRow, error) {
	rows, err := q.db.Query(ctx, adminTenantNumbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminTenantNumbersRow
	for rows.Next() {
		var i AdminTenantNumbersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayPhoneNumber,
			&i.VerifiedName,
			&i.Status,
			&i.QualityRating,
			&i.MessagingLimitTier,
			&i.IsCoexistence,
			&i.WabaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminWebhookErrors = `-- name: AdminWebhookErrors :many
SELECT id, received_at, field, waba_id, tenant_id, error
FROM meta_webhook_events
WHERE error IS NOT NULL AND received_at > $1
ORDER BY received_at DESC
LIMIT 50
`

type AdminWebhookErrorsRow struct {
	ID         int64
	ReceivedAt time.Time
	Field      *string
	WabaID     *string
	TenantID   *uuid.UUID
	Error      *string
}

func (q *Queries) AdminWebhookErrors(ctx context.Context, since time.Time) ([]AdminWebhookErrorsRow, error) {
	rows, err := q.db.Query(ctx, adminWebhookErrors, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminWebhookErrorsRow
	for rows.Next() {
		var i AdminWebhookErrorsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReceivedAt,
			&i.Field,
			&i.WabaID,
			&i.TenantID,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminWebhookHourly = `-- name: AdminWebhookHourly :many
SELECT date_trunc('hour', received_at)::timestamptz AS hour,
       count(*)::int AS received,
       (count(*) FILTER (WHERE processed_at IS NOT NULL AND error IS NULL))::int AS processed,
       (count(*) FILTER (WHERE error IS NOT NULL))::int AS failed,
       (count(*) FILTER (WHERE processed_at IS NULL))::int AS pending,
       coalesce(percentile_cont(0.95) WITHIN GROUP (ORDER BY extract(epoch FROM processed_at - received_at))
                FILTER (WHERE processed_at IS NOT NULL), 0)::float8 AS p95_lag_seconds
FROM meta_webhook_events
WHERE received_at > $1
GROUP BY 1
ORDER BY 1
`

type AdminWebhookHourlyRow struct {
	Hour          time.Time
	Received      int32
	Processed     int32
	Failed        int32
	Pending       int32
	P95LagSeconds float64
}

// Meta webhook deliveries per hour: received, processed, failed and still waiting.
func (q *Queries) AdminWebhookHourly(ctx context.Context, since time.Time) ([]AdminWebhookHourlyRow, error) {
	rows, err := q.db.Query(ctx, adminWebhookHourly, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminWebhookHourlyRow
	for rows.Next() {
		var i AdminWebhookHourlyRow
		if err := rows.Scan(
			&i.Hour,
			&i.Received,
			&i.Processed,
			&i.Failed,
			&i.Pending,
			&i.P95LagSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAdminAudit = `-- name: InsertAdminAudit :exec
INSERT INTO audit_log (tenant_id, actor_type, actor_id, action, target_type, target_id, reason, ip, metadata)
VALUES ($1, 'platform_admin', $2, $3, $4, $5, $6, $7, '{}')
`

type InsertAdminAuditParams struct {
	TenantID   *uuid.UUID
	ActorID    *uuid.UUID
	Action     string
	TargetType *string
	TargetID   *string
	Reason     *string
	Ip         *netip.Addr
}

func (q *Queries) InsertAdminAudit(ctx context.Context, arg InsertAdminAuditParams) error {
	_, err := q.db.Exec(ctx, insertAdminAudit,
		arg.TenantID,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Reason,
		arg.Ip,
	)
	return err
}
