// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAIReplies = `-- name: CountAIReplies :one
SELECT count(*) FROM ai_logs WHERE outcome IN ('answered', 'low_confidence', 'test') AND created_at >= $1::timestamptz
`

func (q *Queries) CountAIReplies(ctx context.Context, since time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countAIReplies, since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countKBChunks = `-- name: CountKBChunks :one
SELECT count(*) FROM kb_chunks
`

func (q *Queries) CountKBChunks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countKBChunks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteKBChunks = `-- name: DeleteKBChunks :exec
DELETE FROM kb_chunks WHERE source_id = $1
`

func (q *Queries) DeleteKBChunks(ctx context.Context, sourceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteKBChunks, sourceID)
	return err
}

const deleteKBSource = `-- name: DeleteKBSource :execrows
DELETE FROM kb_sources WHERE id = $1
`

func (q *Queries) DeleteKBSource(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteKBSource, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishKBSource = `-- name: FinishKBSource :one
UPDATE kb_sources
SET status = $1, error = $2, chunk_count = $3, updated_at = now()
WHERE id = $4
RETURNING id, tenant_id, kind, title, url, status, error, chunk_count, created_by, created_at, updated_at
`

type FinishKBSourceParams struct {
	Status     string
	Error      *string
	ChunkCount int32
	ID         uuid.UUID
}

func (q *Queries) FinishKBSource(ctx context.Context, arg FinishKBSourceParams) (KbSource, error) {
	row := q.db.QueryRow(ctx, finishKBSource,
		arg.Status,
		arg.Error,
		arg.ChunkCount,
		arg.ID,
	)
	var i KbSource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Title,
		&i.Url,
		&i.Status,
		&i.Error,
		&i.ChunkCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKBSource = `-- name: GetKBSource :one
SELECT id, tenant_id, kind, title, url, status, error, chunk_count, created_by, created_at, updated_at FROM kb_sources WHERE id = $1
`

func (q *Queries) GetKBSource(ctx context.Context, id uuid.UUID) (KbSource, error) {
	row := q.db.QueryRow(ctx, getKBSource, id)
	var i KbSource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Title,
		&i.Url,
		&i.Status,
		&i.Error,
		&i.ChunkCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKBSourceForUpdate = `-- name: GetKBSourceForUpdate :one
SELECT id, tenant_id, kind, title, url, status, error, chunk_count, created_by, created_at, updated_at FROM kb_sources WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetKBSourceForUpdate(ctx context.Context, id uuid.UUID) (KbSource, error) {
	row := q.db.QueryRow(ctx, getKBSourceForUpdate, id)
	var i KbSource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Title,
		&i.Url,
		&i.Status,
		&i.Error,
		&i.ChunkCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAILog = `-- name: InsertAILog :exec
INSERT INTO ai_logs (id, tenant_id, bot_id, conversation_id, question, answer, confidence, outcome, source_ids, input_tokens, output_tokens)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertAILogParams struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	BotID          *uuid.UUID
	ConversationID *uuid.UUID
	Question       string
	Answer         *string
	Confidence     *float32
	Outcome        string
	SourceIds      []uuid.UUID
	InputTokens    int32
	OutputTokens   int32
}

func (q *Queries) InsertAILog(ctx context.Context, arg InsertAILogParams) error {
	_, err := q.db.Exec(ctx, insertAILog,
		arg.ID,
		arg.TenantID,
		arg.BotID,
		arg.ConversationID,
		arg.Question,
		arg.Answer,
		arg.Confidence,
		arg.Outcome,
		arg.SourceIds,
		arg.InputTokens,
		arg.OutputTokens,
	)
	return err
}

const insertKBChunk = `-- name: InsertKBChunk :exec
INSERT INTO kb_chunks (id, tenant_id, source_id, ord, content) VALUES ($1, $2, $3, $4, $5)
`

type InsertKBChunkParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	SourceID uuid.UUID
	Ord      int32
	Content  string
}

func (q *Queries) InsertKBChunk(ctx context.Context, arg InsertKBChunkParams) error {
	_, err := q.db.Exec(ctx, insertKBChunk,
		arg.ID,
		arg.TenantID,
		arg.SourceID,
		arg.Ord,
		arg.Content,
	)
	return err
}

const insertKBSource = `-- name: InsertKBSource :one
INSERT INTO kb_sources (id, tenant_id, kind, title, url, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, kind, title, url, status, error, chunk_count, created_by, created_at, updated_at
`

type InsertKBSourceParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Kind      string
	Title     string
	Url       *string
	Status    string
	CreatedBy *uuid.UUID
}

func (q *Queries) InsertKBSource(ctx context.Context, arg InsertKBSourceParams) (KbSource, error) {
	row := q.db.QueryRow(ctx, insertKBSource,
		arg.ID,
		arg.TenantID,
		arg.Kind,
		arg.Title,
		arg.Url,
		arg.Status,
		arg.CreatedBy,
	)
	var i KbSource
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Title,
		&i.Url,
		&i.Status,
		&i.Error,
		&i.ChunkCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAILogs = `-- name: ListAILogs :many
SELECT id, tenant_id, bot_id, conversation_id, question, answer, confidence, outcome, source_ids, input_tokens, output_tokens, created_at FROM ai_logs
WHERE ($1::timestamptz IS NULL OR (created_at, id) < ($1, $2::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListAILogsParams struct {
	BeforeAt *time.Time
	BeforeID *uuid.UUID
	Lim      int32
}

func (q *Queries) ListAILogs(ctx context.Context, arg ListAILogsParams) ([]AiLog, error) {
	rows, err := q.db.Query(ctx, listAILogs, arg.BeforeAt, arg.BeforeID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiLog
	for rows.Next() {
		var i AiLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BotID,
			&i.ConversationID,
			&i.Question,
			&i.Answer,
			&i.Confidence,
			&i.Outcome,
			&i.SourceIds,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKBChunksForScan = `-- name: ListKBChunksForScan :many
SELECT c.id, c.source_id, c.content, s.title
FROM kb_chunks c JOIN kb_sources s ON s.id = c.source_id
ORDER BY c.source_id, c.ord
LIMIT $1
`

type ListKBChunksForScanRow struct {
	ID       uuid.UUID
	SourceID uuid.UUID
	Content  string
	Title    string
}

// A bounded scan for languages the full-text parser does not split into words.
func (q *Queries) ListKBChunksForScan(ctx context.Context, lim int32) ([]ListKBChunksForScanRow, error) {
	rows, err := q.db.Query(ctx, listKBChunksForScan, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKBChunksForScanRow
	for rows.Next() {
		var i ListKBChunksForScanRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Content,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKBSources = `-- name: ListKBSources :many
SELECT id, tenant_id, kind, title, url, status, error, chunk_count, created_by, created_at, updated_at FROM kb_sources ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListKBSources(ctx context.Context) ([]KbSource, error) {
	rows, err := q.db.Query(ctx, listKBSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KbSource
	for rows.Next() {
		var i KbSource
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.Title,
			&i.Url,
			&i.Status,
			&i.Error,
			&i.ChunkCount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markKBSourcePending = `-- name: MarkKBSourcePending :exec
UPDATE kb_sources SET status = 'pending', error = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) MarkKBSourcePending(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markKBSourcePending, id)
	return err
}

const searchKBChunks = `-- name: SearchKBChunks :many
SELECT c.id, c.source_id, c.content, s.title,
       ts_rank(c.tsv, to_tsquery('simple', $1::text)) AS rank
FROM kb_chunks c JOIN kb_sources s ON s.id = c.source_id
WHERE c.tsv @@ to_tsquery('simple', $1::text)
ORDER BY rank DESC, c.id
LIMIT $2
`

type SearchKBChunksParams struct {
	Query string
	Lim   int32
}

type SearchKBChunksRow struct {
	ID       uuid.UUID
	SourceID uuid.UUID
	Content  string
	Title    string
	Rank     float32
}

// Full-text search over the workspace's knowledge; the query is a to_tsquery string of OR-ed words.
func (q *Queries) SearchKBChunks(ctx context.Context, arg SearchKBChunksParams) ([]SearchKBChunksRow, error) {
	rows, err := q.db.Query(ctx, searchKBChunks, arg.Query, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchKBChunksRow
	for rows.Next() {
		var i SearchKBChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Content,
			&i.Title,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
