// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const agentAssignments = `-- name: AgentAssignments :many
SELECT assignee_user_id::uuid AS user_id, count(*)::int AS assigned,
       (count(*) FILTER (WHERE status = 'closed'))::int AS resolved
FROM conversations
WHERE assignee_user_id IS NOT NULL AND coalesce(last_message_at, created_at) >= $1::timestamptz
  AND created_at < $2
GROUP BY assignee_user_id
`

type AgentAssignmentsParams struct {
	Start time.Time
	EndAt time.Time
}

type AgentAssignmentsRow struct {
	UserID   uuid.UUID
	Assigned int32
	Resolved int32
}

// Conversations assigned to each team member that were active in the period, and how many are closed.
func (q *Queries) AgentAssignments(ctx context.Context, arg AgentAssignmentsParams) ([]AgentAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, agentAssignments, arg.Start, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentAssignmentsRow
	for rows.Next() {
		var i AgentAssignmentsRow
		if err := rows.Scan(&i.UserID, &i.Assigned, &i.Resolved); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentChats = `-- name: AgentChats :many
SELECT sent_by_user_id::uuid AS user_id, count(DISTINCT conversation_id)::int AS chats, count(*)::int AS messages
FROM messages
WHERE direction = 'outbound' AND sent_by_user_id IS NOT NULL AND created_at >= $1 AND created_at < $2
GROUP BY sent_by_user_id
`

type AgentChatsParams struct {
	Start time.Time
	EndAt time.Time
}

type AgentChatsRow struct {
	UserID   uuid.UUID
	Chats    int32
	Messages int32
}

// Conversations each team member replied in.
func (q *Queries) AgentChats(ctx context.Context, arg AgentChatsParams) ([]AgentChatsRow, error) {
	rows, err := q.db.Query(ctx, agentChats, arg.Start, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentChatsRow
	for rows.Next() {
		var i AgentChatsRow
		if err := rows.Scan(&i.UserID, &i.Chats, &i.Messages); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const conversationsByNumber = `-- name: ConversationsByNumber :many
SELECT phone_number_id, count(DISTINCT conversation_id)::int AS conversations
FROM messages
WHERE created_at >= $1 AND created_at < $2
  AND ($3::uuid IS NULL OR phone_number_id = $3)
GROUP BY phone_number_id
`

type ConversationsByNumberParams struct {
	Start         time.Time
	EndAt         time.Time
	PhoneNumberID *uuid.UUID
}

type ConversationsByNumberRow struct {
	PhoneNumberID uuid.UUID
	Conversations int32
}

// Conversations with at least one message in the period, per number.
func (q *Queries) ConversationsByNumber(ctx context.Context, arg ConversationsByNumberParams) ([]ConversationsByNumberRow, error) {
	rows, err := q.db.Query(ctx, conversationsByNumber, arg.Start, arg.EndAt, arg.PhoneNumberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationsByNumberRow
	for rows.Next() {
		var i ConversationsByNumberRow
		if err := rows.Scan(&i.PhoneNumberID, &i.Conversations); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUsageDay = `-- name: DeleteUsageDay :exec
DELETE FROM usage_daily WHERE day = $1
`

func (q *Queries) DeleteUsageDay(ctx context.Context, day pgtype.Date) error {
	_, err := q.db.Exec(ctx, deleteUsageDay, day)
	return err
}

const firstResponses = `-- name: FirstResponses :many
WITH turns AS (
    SELECT m.conversation_id, m.created_at, m.direction,
           lag(m.direction) OVER (PARTITION BY m.conversation_id ORDER BY m.created_at, m.id) AS prev_dir
    FROM messages m
    WHERE m.created_at >= $1 AND m.created_at < $2
)
SELECT r.sent_by_user_id, extract(epoch FROM r.created_at - t.created_at)::float8 AS seconds
FROM turns t
CROSS JOIN LATERAL (
    SELECT o.created_at, o.sent_by_user_id FROM messages o
    WHERE o.conversation_id = t.conversation_id AND o.direction = 'outbound' AND o.created_at > t.created_at
    ORDER BY o.created_at LIMIT 1
) r
WHERE t.direction = 'inbound' AND (t.prev_dir IS NULL OR t.prev_dir = 'outbound')
`

type FirstResponsesParams struct {
	Start time.Time
	EndAt time.Time
}

type FirstResponsesRow struct {
	SentByUserID *uuid.UUID
	Seconds      float64
}

// How long each customer waited for a first reply. A customer's turn starts with an inbound
// message that follows an outbound one (or opens the conversation); the reply is the next
// outbound message, by a team member (sent_by_user_id) or by a bot or the API (NULL).
func (q *Queries) FirstResponses(ctx context.Context, arg FirstResponsesParams) ([]FirstResponsesRow, error) {
	rows, err := q.db.Query(ctx, firstResponses, arg.Start, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FirstResponsesRow
	for rows.Next() {
		var i FirstResponsesRow
		if err := rows.Scan(&i.SentByUserID, &i.Seconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUsage = `-- name: InsertUsage :exec
INSERT INTO usage_daily (tenant_id, phone_number_id, day, pricing_category, recipient_country, origin,
                         sent, delivered, read, failed, received, billable, est_meta_cost_minor)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertUsageParams struct {
	TenantID         uuid.UUID
	PhoneNumberID    uuid.UUID
	Day              pgtype.Date
	PricingCategory  string
	RecipientCountry string
	Origin           MessageOrigin
	Sent             int32
	Delivered        int32
	Read             int32
	Failed           int32
	Received         int32
	Billable         int32
	EstMetaCostMinor int64
}

func (q *Queries) InsertUsage(ctx context.Context, arg InsertUsageParams) error {
	_, err := q.db.Exec(ctx, insertUsage,
		arg.TenantID,
		arg.PhoneNumberID,
		arg.Day,
		arg.PricingCategory,
		arg.RecipientCountry,
		arg.Origin,
		arg.Sent,
		arg.Delivered,
		arg.Read,
		arg.Failed,
		arg.Received,
		arg.Billable,
		arg.EstMetaCostMinor,
	)
	return err
}

const listActiveTenants = `-- name: ListActiveTenants :many
SELECT id, timezone FROM tenants WHERE status = 'active' ORDER BY id
`

type ListActiveTenantsRow struct {
	ID       uuid.UUID
	Timezone string
}

func (q *Queries) ListActiveTenants(ctx context.Context) ([]ListActiveTenantsRow, error) {
	rows, err := q.db.Query(ctx, listActiveTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTenantsRow
	for rows.Next() {
		var i ListActiveTenantsRow
		if err := rows.Scan(&i.ID, &i.Timezone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageForPeriod = `-- name: UsageForPeriod :many
SELECT m.phone_number_id,
       coalesce(m.pricing_category, CASE WHEN m.direction = 'outbound' THEN t.category::text END, 'service')::text AS category,
       left(c.wa_id, 3)::text AS prefix,
       m.origin,
       (count(*) FILTER (WHERE m.direction = 'outbound' AND m.status IN ('sent', 'delivered', 'read')))::int AS sent,
       (count(*) FILTER (WHERE m.direction = 'outbound' AND m.status IN ('delivered', 'read')))::int AS delivered,
       (count(*) FILTER (WHERE m.direction = 'outbound' AND m.status = 'read'))::int AS read,
       (count(*) FILTER (WHERE m.direction = 'outbound' AND m.status = 'failed'))::int AS failed,
       (count(*) FILTER (WHERE m.direction = 'inbound'))::int AS received,
       (count(*) FILTER (WHERE m.direction = 'outbound' AND m.pricing_billable))::int AS billable
FROM messages m
JOIN contacts c ON c.id = m.contact_id
LEFT JOIN templates t ON t.id = m.template_id
WHERE m.created_at >= $1 AND m.created_at < $2
GROUP BY 1, 2, 3, 4
`

type UsageForPeriodParams struct {
	Start time.Time
	EndAt time.Time
}

type UsageForPeriodRow struct {
	PhoneNumberID uuid.UUID
	Category      string
	Prefix        string
	Origin        MessageOrigin
	Sent          int32
	Delivered     int32
	Read          int32
	Failed        int32
	Received      int32
	Billable      int32
}

// Message counts for one day of a tenant, by number, pricing category, recipient calling-code
// prefix and origin. sent, delivered and read are cumulative.
func (q *Queries) UsageForPeriod(ctx context.Context, arg UsageForPeriodParams) ([]UsageForPeriodRow, error) {
	rows, err := q.db.Query(ctx, usageForPeriod, arg.Start, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageForPeriodRow
	for rows.Next() {
		var i UsageForPeriodRow
		if err := rows.Scan(
			&i.PhoneNumberID,
			&i.Category,
			&i.Prefix,
			&i.Origin,
			&i.Sent,
			&i.Delivered,
			&i.Read,
			&i.Failed,
			&i.Received,
			&i.Billable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageRange = `-- name: UsageRange :many
SELECT tenant_id, phone_number_id, day, pricing_category, recipient_country, origin, sent, delivered, read, failed, billable, est_meta_cost_minor, received FROM usage_daily
WHERE day BETWEEN $1 AND $2
  AND ($3::uuid IS NULL OR phone_number_id = $3)
ORDER BY day
`

type UsageRangeParams struct {
	FromDay       pgtype.Date
	ToDay         pgtype.Date
	PhoneNumberID *uuid.UUID
}

func (q *Queries) UsageRange(ctx context.Context, arg UsageRangeParams) ([]UsageDaily, error) {
	rows, err := q.db.Query(ctx, usageRange, arg.FromDay, arg.ToDay, arg.PhoneNumberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageDaily
	for rows.Next() {
		var i UsageDaily
		if err := rows.Scan(
			&i.TenantID,
			&i.PhoneNumberID,
			&i.Day,
			&i.PricingCategory,
			&i.RecipientCountry,
			&i.Origin,
			&i.Sent,
			&i.Delivered,
			&i.Read,
			&i.Failed,
			&i.Billable,
			&i.EstMetaCostMinor,
			&i.Received,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
