// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUsageDay = `-- name: DeleteUsageDay :exec
DELETE FROM usage_daily WHERE day = $1
`

func (q *Queries) DeleteUsageDay(ctx context.Context, day pgtype.Date) error {
	_, err := q.db.Exec(ctx, deleteUsageDay, day)
	return err
}

const insertUsage = `-- name: InsertUsage :exec
INSERT INTO usage_daily (tenant_id, phone_number_id, day, pricing_category, recipient_country, origin,
                         sent, delivered, read, failed, received, billable, est_meta_cost_minor)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertUsageParams struct {
	TenantID         uuid.UUID
	PhoneNumberID    uuid.UUID
	Day              pgtype.Date
	PricingCategory  string
	RecipientCountry string
	Origin           MessageOrigin
	Sent             int32
	Delivered        int32
	Read             int32
	Failed           int32
	Received         int32
	Billable         int32
	EstMetaCostMinor int64
}

func (q *Queries) InsertUsage(ctx context.Context, arg InsertUsageParams) error {
	_, err := q.db.Exec(ctx, insertUsage,
		arg.TenantID,
		arg.PhoneNumberID,
		arg.Day,
		arg.PricingCategory,
		arg.RecipientCountry,
		arg.Origin,
		arg.Sent,
		arg.Delivered,
		arg.Read,
		arg.Failed,
		arg.Received,
		arg.Billable,
		arg.EstMetaCostMinor,
	)
	return err
}

const listActiveTenants = `-- name: ListActiveTenants :many
SELECT id, timezone FROM tenants WHERE status = 'active' ORDER BY id
`

type ListActiveTenantsRow struct {
	ID       uuid.UUID
	Timezone string
}

func (q *Queries) ListActiveTenants(ctx context.Context) ([]ListActiveTenantsRow, error) {
	rows, err := q.db.Query(ctx, listActiveTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTenantsRow
	for rows.Next() {
		var i ListActiveTenantsRow
		if err := rows.Scan(&i.ID, &i.Timezone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageForPeriod = `-- name: UsageForPeriod :many
SELECT m.phone_number_id,
       coalesce(m.pricing_category, CASE WHEN m.direction = 'outbound' THEN t.category::text END, 'service')::text AS category,
       left(c.wa_id, 3)::text AS prefix,
       m.origin,
       (count(*) FILTER (WHERE m.direction = 'outbound' AND m.status IN ('sent', 'delivered', 'read')))::int AS sent,
       (count(*) FILTER (WHERE m.direction = 'outbound' AND m.status IN ('delivered', 'read')))::int AS delivered,
       (count(*) FILTER (WHERE m.direction = 'outbound' AND m.status = 'read'))::int AS read,
       (count(*) FILTER (WHERE m.direction = 'outbound' AND m.status = 'failed'))::int AS failed,
       (count(*) FILTER (WHERE m.direction = 'inbound'))::int AS received,
       (count(*) FILTER (WHERE m.direction = 'outbound' AND m.pricing_billable))::int AS billable
FROM messages m
JOIN contacts c ON c.id = m.contact_id
LEFT JOIN templates t ON t.id = m.template_id
WHERE m.created_at >= $1 AND m.created_at < $2
GROUP BY 1, 2, 3, 4
`

type UsageForPeriodParams struct {
	Start time.Time
	EndAt time.Time
}

type UsageForPeriodRow struct {
	PhoneNumberID uuid.UUID
	Category      string
	Prefix        string
	Origin        MessageOrigin
	Sent          int32
	Delivered     int32
	Read          int32
	Failed        int32
	Received      int32
	Billable      int32
}

// Message counts for one day of a tenant, by number, pricing category, recipient calling-code
// prefix and origin. sent, delivered and read are cumulative.
func (q *Queries) UsageForPeriod(ctx context.Context, arg UsageForPeriodParams) ([]UsageForPeriodRow, error) {
	rows, err := q.db.Query(ctx, usageForPeriod, arg.Start, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageForPeriodRow
	for rows.Next() {
		var i UsageForPeriodRow
		if err := rows.Scan(
			&i.PhoneNumberID,
			&i.Category,
			&i.Prefix,
			&i.Origin,
			&i.Sent,
			&i.Delivered,
			&i.Read,
			&i.Failed,
			&i.Received,
			&i.Billable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageRange = `-- name: UsageRange :many
SELECT tenant_id, phone_number_id, day, pricing_category, recipient_country, origin, sent, delivered, read, failed, billable, est_meta_cost_minor, received FROM usage_daily
WHERE day BETWEEN $1 AND $2
  AND ($3::uuid IS NULL OR phone_number_id = $3)
ORDER BY day
`

type UsageRangeParams struct {
	FromDay       pgtype.Date
	ToDay         pgtype.Date
	PhoneNumberID *uuid.UUID
}

func (q *Queries) UsageRange(ctx context.Context, arg UsageRangeParams) ([]UsageDaily, error) {
	rows, err := q.db.Query(ctx, usageRange, arg.FromDay, arg.ToDay, arg.PhoneNumberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageDaily
	for rows.Next() {
		var i UsageDaily
		if err := rows.Scan(
			&i.TenantID,
			&i.PhoneNumberID,
			&i.Day,
			&i.PricingCategory,
			&i.RecipientCountry,
			&i.Origin,
			&i.Sent,
			&i.Delivered,
			&i.Read,
			&i.Failed,
			&i.Billable,
			&i.EstMetaCostMinor,
			&i.Received,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
