// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbq

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createMembership = `-- name: CreateMembership :exec
INSERT INTO memberships (tenant_id, user_id, role) VALUES ($1, $2, $3)
`

type CreateMembershipParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
	Role     MemberRole
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership, arg.TenantID, arg.UserID, arg.Role)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, tenant_id, token_hash, ip, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, tenant_id, token_hash, mfa_passed, ip, user_agent, created_at, last_seen_at, expires_at
`

type CreateSessionParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TenantID  *uuid.UUID
	TokenHash []byte
	Ip        *netip.Addr
	UserAgent *string
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TenantID,
		arg.TokenHash,
		arg.Ip,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TokenHash,
		&i.MfaPassed,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (id, name, slug)
VALUES ($1, $2, $3)
RETURNING id, name, slug, legal_name, status, suspended_reason, default_locale, timezone, message_retention_days, created_at, updated_at, meta_payment_mode, meta_payment_mode_since
`

type CreateTenantParams struct {
	ID   uuid.UUID
	Name string
	Slug string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.ID, arg.Name, arg.Slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LegalName,
		&i.Status,
		&i.SuspendedReason,
		&i.DefaultLocale,
		&i.Timezone,
		&i.MessageRetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MetaPaymentMode,
		&i.MetaPaymentModeSince,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, name, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, email, name, password_hash, email_verified_at, totp_secret_enc, preferred_locale, is_platform_admin, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.TotpSecretEnc,
		&i.PreferredLocale,
		&i.IsPlatformAdmin,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, tenant_id, token_hash, mfa_passed, ip, user_agent, created_at, last_seen_at, expires_at FROM sessions WHERE token_hash = $1 AND expires_at > now()
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TokenHash,
		&i.MfaPassed,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, slug, legal_name, status, suspended_reason, default_locale, timezone, message_retention_days, created_at, updated_at, meta_payment_mode, meta_payment_mode_since FROM tenants WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LegalName,
		&i.Status,
		&i.SuspendedReason,
		&i.DefaultLocale,
		&i.Timezone,
		&i.MessageRetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MetaPaymentMode,
		&i.MetaPaymentModeSince,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, email_verified_at, totp_secret_enc, preferred_locale, is_platform_admin, last_login_at, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.TotpSecretEnc,
		&i.PreferredLocale,
		&i.IsPlatformAdmin,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, email_verified_at, totp_secret_enc, preferred_locale, is_platform_admin, last_login_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.TotpSecretEnc,
		&i.PreferredLocale,
		&i.IsPlatformAdmin,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (tenant_id, actor_type, actor_id, action, target_type, target_id, ip, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditLogParams struct {
	TenantID   *uuid.UUID
	ActorType  ActorType
	ActorID    *uuid.UUID
	Action     string
	TargetType *string
	TargetID   *string
	Ip         *netip.Addr
	Metadata   []byte
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.TenantID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Ip,
		arg.Metadata,
	)
	return err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users SET email_verified_at = coalesce(email_verified_at, now()), updated_at = now() WHERE id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const setSessionTenant = `-- name: SetSessionTenant :exec
UPDATE sessions SET tenant_id = $2 WHERE id = $1
`

type SetSessionTenantParams struct {
	ID       uuid.UUID
	TenantID *uuid.UUID
}

func (q *Queries) SetSessionTenant(ctx context.Context, arg SetSessionTenantParams) error {
	_, err := q.db.Exec(ctx, setSessionTenant, arg.ID, arg.TenantID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now(), expires_at = $2 WHERE id = $1
`

type TouchSessionParams struct {
	ID        uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.ExpiresAt)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const userMemberships = `-- name: UserMemberships :many
SELECT m.tenant_id::uuid AS tenant_id, m.tenant_name::text AS tenant_name, m.tenant_slug::text AS tenant_slug,
       m.tenant_status::tenant_status AS tenant_status, m.role::member_role AS role
FROM user_memberships($1::uuid) m
`

type UserMembershipsRow struct {
	TenantID     uuid.UUID
	TenantName   string
	TenantSlug   string
	TenantStatus TenantStatus
	Role         MemberRole
}

func (q *Queries) UserMemberships(ctx context.Context, userID uuid.UUID) ([]UserMembershipsRow, error) {
	rows, err := q.db.Query(ctx, userMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserMembershipsRow
	for rows.Next() {
		var i UserMembershipsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.TenantName,
			&i.TenantSlug,
			&i.TenantStatus,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
