// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const applySubscriptionState = `-- name: ApplySubscriptionState :one
UPDATE subscriptions
SET status = $1,
    plan_code = coalesce($2, plan_code),
    current_period_start = coalesce($3, current_period_start),
    current_period_end = coalesce($4, current_period_end),
    cancel_at_period_end = $5,
    updated_at = now()
WHERE tenant_id = $6
RETURNING id, tenant_id, plan_code, status, seats, current_period_start, current_period_end, payment_provider, provider_customer_id, provider_subscription_id, created_at, updated_at, cancel_at_period_end
`

type ApplySubscriptionStateParams struct {
	Status            SubscriptionStatus
	PlanCode          *string
	PeriodStart       *time.Time
	PeriodEnd         *time.Time
	CancelAtPeriodEnd bool
	TenantID          uuid.UUID
}

func (q *Queries) ApplySubscriptionState(ctx context.Context, arg ApplySubscriptionStateParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, applySubscriptionState,
		arg.Status,
		arg.PlanCode,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.CancelAtPeriodEnd,
		arg.TenantID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanCode,
		&i.Status,
		&i.Seats,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.PaymentProvider,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelAtPeriodEnd,
	)
	return i, err
}

const billingUsage = `-- name: BillingUsage :one
SELECT (SELECT count(*) FROM phone_numbers WHERE status = 'connected')::int AS connected_numbers,
       (SELECT count(*) FROM memberships)::int AS seats
`

type BillingUsageRow struct {
	ConnectedNumbers int32
	Seats            int32
}

// Run inside the tenant: what the plan's limits are measured against.
func (q *Queries) BillingUsage(ctx context.Context) (BillingUsageRow, error) {
	row := q.db.QueryRow(ctx, billingUsage)
	var i BillingUsageRow
	err := row.Scan(&i.ConnectedNumbers, &i.Seats)
	return i, err
}

const currentPlan = `-- name: CurrentPlan :one
SELECT p.code, p.name, p.price_minor, p.currency, p.included_numbers, p.included_seats, p.extra_seat_minor, p.features, p.is_active, p.razorpay_plan_id, p.sort_order, p.created_at, p.updated_at FROM plans p JOIN subscriptions s ON s.plan_code = p.code
`

// Run inside the tenant. No row while the workspace is on a trial with no plan chosen.
func (q *Queries) CurrentPlan(ctx context.Context) (Plan, error) {
	row := q.db.QueryRow(ctx, currentPlan)
	var i Plan
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.PriceMinor,
		&i.Currency,
		&i.IncludedNumbers,
		&i.IncludedSeats,
		&i.ExtraSeatMinor,
		&i.Features,
		&i.IsActive,
		&i.RazorpayPlanID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dropTrialPlan = `-- name: DropTrialPlan :exec
UPDATE subscriptions SET plan_code = NULL, provider_subscription_id = NULL, updated_at = now()
WHERE tenant_id = $1 AND status = 'trialing'
`

// A plan chosen during the trial was cancelled before its first charge.
func (q *Queries) DropTrialPlan(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, dropTrialPlan, tenantID)
	return err
}

const extendTrial = `-- name: ExtendTrial :one
UPDATE subscriptions SET current_period_end = $1, updated_at = now()
WHERE tenant_id = $2 AND status = 'trialing'
RETURNING id, tenant_id, plan_code, status, seats, current_period_start, current_period_end, payment_provider, provider_customer_id, provider_subscription_id, created_at, updated_at, cancel_at_period_end
`

type ExtendTrialParams struct {
	Until    time.Time
	TenantID uuid.UUID
}

func (q *Queries) ExtendTrial(ctx context.Context, arg ExtendTrialParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, extendTrial, arg.Until, arg.TenantID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanCode,
		&i.Status,
		&i.Seats,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.PaymentProvider,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelAtPeriodEnd,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT code, name, price_minor, currency, included_numbers, included_seats, extra_seat_minor, features, is_active, razorpay_plan_id, sort_order, created_at, updated_at FROM plans WHERE code = $1
`

func (q *Queries) GetPlan(ctx context.Context, code string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, code)
	var i Plan
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.PriceMinor,
		&i.Currency,
		&i.IncludedNumbers,
		&i.IncludedSeats,
		&i.ExtraSeatMinor,
		&i.Features,
		&i.IsActive,
		&i.RazorpayPlanID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanByRazorpayID = `-- name: GetPlanByRazorpayID :one
SELECT code, name, price_minor, currency, included_numbers, included_seats, extra_seat_minor, features, is_active, razorpay_plan_id, sort_order, created_at, updated_at FROM plans WHERE razorpay_plan_id = $1
`

func (q *Queries) GetPlanByRazorpayID(ctx context.Context, razorpayPlanID *string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByRazorpayID, razorpayPlanID)
	var i Plan
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.PriceMinor,
		&i.Currency,
		&i.IncludedNumbers,
		&i.IncludedSeats,
		&i.ExtraSeatMinor,
		&i.Features,
		&i.IsActive,
		&i.RazorpayPlanID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, tenant_id, plan_code, status, seats, current_period_start, current_period_end, payment_provider, provider_customer_id, provider_subscription_id, created_at, updated_at, cancel_at_period_end FROM subscriptions LIMIT 1
`

// Run inside the tenant.
func (q *Queries) GetSubscription(ctx context.Context) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanCode,
		&i.Status,
		&i.Seats,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.PaymentProvider,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelAtPeriodEnd,
	)
	return i, err
}

const getSubscriptionForUpdate = `-- name: GetSubscriptionForUpdate :one
SELECT id, tenant_id, plan_code, status, seats, current_period_start, current_period_end, payment_provider, provider_customer_id, provider_subscription_id, created_at, updated_at, cancel_at_period_end FROM subscriptions LIMIT 1 FOR UPDATE
`

func (q *Queries) GetSubscriptionForUpdate(ctx context.Context) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionForUpdate)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanCode,
		&i.Status,
		&i.Seats,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.PaymentProvider,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelAtPeriodEnd,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT code, name, price_minor, currency, included_numbers, included_seats, extra_seat_minor, features, is_active, razorpay_plan_id, sort_order, created_at, updated_at FROM plans
WHERE (NOT $1::boolean OR is_active)
ORDER BY sort_order, price_minor, code
`

func (q *Queries) ListPlans(ctx context.Context, activeOnly bool) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans, activeOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.PriceMinor,
			&i.Currency,
			&i.IncludedNumbers,
			&i.IncludedSeats,
			&i.ExtraSeatMinor,
			&i.Features,
			&i.IsActive,
			&i.RazorpayPlanID,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const numbersInUse = `-- name: NumbersInUse :one
SELECT count(*)::int FROM phone_numbers
WHERE status IN ('pending', 'connected') AND phone_number_id <> $1::text
`

// Numbers that count against the plan: connected or being connected, other than the one named.
func (q *Queries) NumbersInUse(ctx context.Context, otherID string) (int32, error) {
	row := q.db.QueryRow(ctx, numbersInUse, otherID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const recordRazorpayEvent = `-- name: RecordRazorpayEvent :execrows
INSERT INTO razorpay_events (id, event) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type RecordRazorpayEventParams struct {
	ID    string
	Event string
}

func (q *Queries) RecordRazorpayEvent(ctx context.Context, arg RecordRazorpayEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordRazorpayEvent, arg.ID, arg.Event)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCancelAtPeriodEnd = `-- name: SetCancelAtPeriodEnd :exec
UPDATE subscriptions SET cancel_at_period_end = $1, updated_at = now() WHERE tenant_id = $2
`

type SetCancelAtPeriodEndParams struct {
	Cancel   bool
	TenantID uuid.UUID
}

func (q *Queries) SetCancelAtPeriodEnd(ctx context.Context, arg SetCancelAtPeriodEndParams) error {
	_, err := q.db.Exec(ctx, setCancelAtPeriodEnd, arg.Cancel, arg.TenantID)
	return err
}

const setProviderSubscription = `-- name: SetProviderSubscription :exec
UPDATE subscriptions
SET provider_customer_id = $1, provider_subscription_id = $2, updated_at = now()
WHERE tenant_id = $3
`

type SetProviderSubscriptionParams struct {
	ProviderCustomerID     *string
	ProviderSubscriptionID *string
	TenantID               uuid.UUID
}

func (q *Queries) SetProviderSubscription(ctx context.Context, arg SetProviderSubscriptionParams) error {
	_, err := q.db.Exec(ctx, setProviderSubscription, arg.ProviderCustomerID, arg.ProviderSubscriptionID, arg.TenantID)
	return err
}

const subscriptionTenant = `-- name: SubscriptionTenant :one
SELECT t.tenant_id::uuid FROM (SELECT subscription_tenant($1::text) AS tenant_id) t
WHERE t.tenant_id IS NOT NULL
`

func (q *Queries) SubscriptionTenant(ctx context.Context, providerSubscriptionID string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, subscriptionTenant, providerSubscriptionID)
	var t_tenant_id uuid.UUID
	err := row.Scan(&t_tenant_id)
	return t_tenant_id, err
}

const upsertPlan = `-- name: UpsertPlan :one
INSERT INTO plans (code, name, price_minor, included_numbers, included_seats, extra_seat_minor,
                   razorpay_plan_id, sort_order, is_active)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9)
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name, price_minor = EXCLUDED.price_minor, included_numbers = EXCLUDED.included_numbers,
    included_seats = EXCLUDED.included_seats, extra_seat_minor = EXCLUDED.extra_seat_minor,
    razorpay_plan_id = EXCLUDED.razorpay_plan_id, sort_order = EXCLUDED.sort_order,
    is_active = EXCLUDED.is_active, updated_at = now()
RETURNING code, name, price_minor, currency, included_numbers, included_seats, extra_seat_minor, features, is_active, razorpay_plan_id, sort_order, created_at, updated_at
`

type UpsertPlanParams struct {
	Code            string
	Name            string
	PriceMinor      int64
	IncludedNumbers int32
	IncludedSeats   int32
	ExtraSeatMinor  int64
	RazorpayPlanID  *string
	SortOrder       int32
	IsActive        bool
}

func (q *Queries) UpsertPlan(ctx context.Context, arg UpsertPlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, upsertPlan,
		arg.Code,
		arg.Name,
		arg.PriceMinor,
		arg.IncludedNumbers,
		arg.IncludedSeats,
		arg.ExtraSeatMinor,
		arg.RazorpayPlanID,
		arg.SortOrder,
		arg.IsActive,
	)
	var i Plan
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.PriceMinor,
		&i.Currency,
		&i.IncludedNumbers,
		&i.IncludedSeats,
		&i.ExtraSeatMinor,
		&i.Features,
		&i.IsActive,
		&i.RazorpayPlanID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
