// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bots.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const botsInUse = `-- name: BotsInUse :one
SELECT EXISTS (SELECT 1 FROM bots WHERE status = 'active')
    OR EXISTS (SELECT 1 FROM bot_sessions WHERE conversation_id = $1 AND status = 'active')
`

// Whether an inbound message in this conversation could involve a bot.
func (q *Queries) BotsInUse(ctx context.Context, conversationID uuid.UUID) (*bool, error) {
	row := q.db.QueryRow(ctx, botsInUse, conversationID)
	var column_1 *bool
	err := row.Scan(&column_1)
	return column_1, err
}

const countInboundMessages = `-- name: CountInboundMessages :one
SELECT count(*) FROM messages WHERE conversation_id = $1 AND direction = 'inbound'
`

func (q *Queries) CountInboundMessages(ctx context.Context, conversationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInboundMessages, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBot = `-- name: DeleteBot :execrows
DELETE FROM bots WHERE id = $1
`

func (q *Queries) DeleteBot(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBot, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveBotSession = `-- name: GetActiveBotSession :one
SELECT id, tenant_id, bot_id, conversation_id, contact_id, node_id, vars, status, end_reason, started_at, updated_at, ended_at FROM bot_sessions WHERE conversation_id = $1 AND status = 'active' FOR UPDATE
`

func (q *Queries) GetActiveBotSession(ctx context.Context, conversationID uuid.UUID) (BotSession, error) {
	row := q.db.QueryRow(ctx, getActiveBotSession, conversationID)
	var i BotSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BotID,
		&i.ConversationID,
		&i.ContactID,
		&i.NodeID,
		&i.Vars,
		&i.Status,
		&i.EndReason,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.EndedAt,
	)
	return i, err
}

const getBot = `-- name: GetBot :one
SELECT id, tenant_id, name, status, phone_number_id, flow, created_by, created_at, updated_at FROM bots WHERE id = $1
`

func (q *Queries) GetBot(ctx context.Context, id uuid.UUID) (Bot, error) {
	row := q.db.QueryRow(ctx, getBot, id)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.PhoneNumberID,
		&i.Flow,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBotConversation = `-- name: GetBotConversation :one
SELECT cv.id, cv.tenant_id, cv.phone_number_id, cv.contact_id, cv.status, cv.assignee_user_id, cv.last_inbound_at, cv.last_message_at, cv.last_message_preview, cv.unread_count, cv.created_at, cv.updated_at, ct.id, ct.tenant_id, ct.wa_id, ct.name, ct.profile_name, ct.language, ct.custom_fields, ct.opt_in_status, ct.opted_in_at, ct.opted_out_at, ct.blocked, ct.created_at, ct.updated_at
FROM conversations cv JOIN contacts ct ON ct.id = cv.contact_id
WHERE cv.id = $1
FOR UPDATE OF cv
`

type GetBotConversationRow struct {
	Conversation Conversation
	Contact      Contact
}

func (q *Queries) GetBotConversation(ctx context.Context, id uuid.UUID) (GetBotConversationRow, error) {
	row := q.db.QueryRow(ctx, getBotConversation, id)
	var i GetBotConversationRow
	err := row.Scan(
		&i.Conversation.ID,
		&i.Conversation.TenantID,
		&i.Conversation.PhoneNumberID,
		&i.Conversation.ContactID,
		&i.Conversation.Status,
		&i.Conversation.AssigneeUserID,
		&i.Conversation.LastInboundAt,
		&i.Conversation.LastMessageAt,
		&i.Conversation.LastMessagePreview,
		&i.Conversation.UnreadCount,
		&i.Conversation.CreatedAt,
		&i.Conversation.UpdatedAt,
		&i.Contact.ID,
		&i.Contact.TenantID,
		&i.Contact.WaID,
		&i.Contact.Name,
		&i.Contact.ProfileName,
		&i.Contact.Language,
		&i.Contact.CustomFields,
		&i.Contact.OptInStatus,
		&i.Contact.OptedInAt,
		&i.Contact.OptedOutAt,
		&i.Contact.Blocked,
		&i.Contact.CreatedAt,
		&i.Contact.UpdatedAt,
	)
	return i, err
}

const getBotSession = `-- name: GetBotSession :one
SELECT id, tenant_id, bot_id, conversation_id, contact_id, node_id, vars, status, end_reason, started_at, updated_at, ended_at FROM bot_sessions WHERE id = $1
`

func (q *Queries) GetBotSession(ctx context.Context, id uuid.UUID) (BotSession, error) {
	row := q.db.QueryRow(ctx, getBotSession, id)
	var i BotSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BotID,
		&i.ConversationID,
		&i.ContactID,
		&i.NodeID,
		&i.Vars,
		&i.Status,
		&i.EndReason,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.EndedAt,
	)
	return i, err
}

const getInboundMessage = `-- name: GetInboundMessage :one
SELECT id, tenant_id, conversation_id, phone_number_id, contact_id, direction, origin, wamid, type, content, media_id, template_id, reply_to_wamid, status, error_code, error_title, sent_by_user_id, api_key_id, campaign_id, idempotency_key, pricing_category, pricing_billable, recipient_country, meta_timestamp, status_updated_at, created_at, bot_id FROM messages WHERE id = $1 AND direction = 'inbound'
`

func (q *Queries) GetInboundMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getInboundMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ConversationID,
		&i.PhoneNumberID,
		&i.ContactID,
		&i.Direction,
		&i.Origin,
		&i.Wamid,
		&i.Type,
		&i.Content,
		&i.MediaID,
		&i.TemplateID,
		&i.ReplyToWamid,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorTitle,
		&i.SentByUserID,
		&i.ApiKeyID,
		&i.CampaignID,
		&i.IdempotencyKey,
		&i.PricingCategory,
		&i.PricingBillable,
		&i.RecipientCountry,
		&i.MetaTimestamp,
		&i.StatusUpdatedAt,
		&i.CreatedAt,
		&i.BotID,
	)
	return i, err
}

const hasHumanReplySince = `-- name: HasHumanReplySince :one
SELECT EXISTS (
    SELECT 1 FROM messages
    WHERE conversation_id = $1 AND direction = 'outbound' AND origin = 'dashboard' AND created_at >= $2::timestamptz
)
`

type HasHumanReplySinceParams struct {
	ConversationID uuid.UUID
	Since          time.Time
}

func (q *Queries) HasHumanReplySince(ctx context.Context, arg HasHumanReplySinceParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasHumanReplySince, arg.ConversationID, arg.Since)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertBot = `-- name: InsertBot :one
INSERT INTO bots (id, tenant_id, name, phone_number_id, flow, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, status, phone_number_id, flow, created_by, created_at, updated_at
`

type InsertBotParams struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	Name          string
	PhoneNumberID *uuid.UUID
	Flow          []byte
	CreatedBy     *uuid.UUID
}

func (q *Queries) InsertBot(ctx context.Context, arg InsertBotParams) (Bot, error) {
	row := q.db.QueryRow(ctx, insertBot,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.PhoneNumberID,
		arg.Flow,
		arg.CreatedBy,
	)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.PhoneNumberID,
		&i.Flow,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBotMessage = `-- name: InsertBotMessage :one
INSERT INTO messages (id, tenant_id, conversation_id, phone_number_id, contact_id, direction, origin,
                      type, content, template_id, status, bot_id)
VALUES ($1, $2, $3, $4, $5, 'outbound', 'bot', $6, $7, $8, 'queued', $9)
RETURNING id, tenant_id, conversation_id, phone_number_id, contact_id, direction, origin, wamid, type, content, media_id, template_id, reply_to_wamid, status, error_code, error_title, sent_by_user_id, api_key_id, campaign_id, idempotency_key, pricing_category, pricing_billable, recipient_country, meta_timestamp, status_updated_at, created_at, bot_id
`

type InsertBotMessageParams struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ConversationID uuid.UUID
	PhoneNumberID  uuid.UUID
	ContactID      uuid.UUID
	Type           MessageType
	Content        []byte
	TemplateID     *uuid.UUID
	BotID          *uuid.UUID
}

func (q *Queries) InsertBotMessage(ctx context.Context, arg InsertBotMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertBotMessage,
		arg.ID,
		arg.TenantID,
		arg.ConversationID,
		arg.PhoneNumberID,
		arg.ContactID,
		arg.Type,
		arg.Content,
		arg.TemplateID,
		arg.BotID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ConversationID,
		&i.PhoneNumberID,
		&i.ContactID,
		&i.Direction,
		&i.Origin,
		&i.Wamid,
		&i.Type,
		&i.Content,
		&i.MediaID,
		&i.TemplateID,
		&i.ReplyToWamid,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorTitle,
		&i.SentByUserID,
		&i.ApiKeyID,
		&i.CampaignID,
		&i.IdempotencyKey,
		&i.PricingCategory,
		&i.PricingBillable,
		&i.RecipientCountry,
		&i.MetaTimestamp,
		&i.StatusUpdatedAt,
		&i.CreatedAt,
		&i.BotID,
	)
	return i, err
}

const insertBotSession = `-- name: InsertBotSession :one
INSERT INTO bot_sessions (id, tenant_id, bot_id, conversation_id, contact_id, vars)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, bot_id, conversation_id, contact_id, node_id, vars, status, end_reason, started_at, updated_at, ended_at
`

type InsertBotSessionParams struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	BotID          uuid.UUID
	ConversationID uuid.UUID
	ContactID      uuid.UUID
	Vars           []byte
}

func (q *Queries) InsertBotSession(ctx context.Context, arg InsertBotSessionParams) (BotSession, error) {
	row := q.db.QueryRow(ctx, insertBotSession,
		arg.ID,
		arg.TenantID,
		arg.BotID,
		arg.ConversationID,
		arg.ContactID,
		arg.Vars,
	)
	var i BotSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BotID,
		&i.ConversationID,
		&i.ContactID,
		&i.NodeID,
		&i.Vars,
		&i.Status,
		&i.EndReason,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.EndedAt,
	)
	return i, err
}

const listActiveBotsForNumber = `-- name: ListActiveBotsForNumber :many
SELECT id, tenant_id, name, status, phone_number_id, flow, created_by, created_at, updated_at FROM bots
WHERE status = 'active' AND (phone_number_id IS NULL OR phone_number_id = $1)
ORDER BY (phone_number_id IS NULL), created_at, id
`

func (q *Queries) ListActiveBotsForNumber(ctx context.Context, phoneNumberID *uuid.UUID) ([]Bot, error) {
	rows, err := q.db.Query(ctx, listActiveBotsForNumber, phoneNumberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bot
	for rows.Next() {
		var i Bot
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Status,
			&i.PhoneNumberID,
			&i.Flow,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBotSessions = `-- name: ListBotSessions :many
SELECT id, tenant_id, bot_id, conversation_id, contact_id, node_id, vars, status, end_reason, started_at, updated_at, ended_at FROM bot_sessions WHERE bot_id = $1 ORDER BY started_at DESC, id LIMIT $2
`

type ListBotSessionsParams struct {
	BotID uuid.UUID
	Lim   int32
}

func (q *Queries) ListBotSessions(ctx context.Context, arg ListBotSessionsParams) ([]BotSession, error) {
	rows, err := q.db.Query(ctx, listBotSessions, arg.BotID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotSession
	for rows.Next() {
		var i BotSession
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BotID,
			&i.ConversationID,
			&i.ContactID,
			&i.NodeID,
			&i.Vars,
			&i.Status,
			&i.EndReason,
			&i.StartedAt,
			&i.UpdatedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBots = `-- name: ListBots :many
SELECT id, tenant_id, name, status, phone_number_id, flow, created_by, created_at, updated_at FROM bots ORDER BY created_at, id
`

func (q *Queries) ListBots(ctx context.Context) ([]Bot, error) {
	rows, err := q.db.Query(ctx, listBots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bot
	for rows.Next() {
		var i Bot
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Status,
			&i.PhoneNumberID,
			&i.Flow,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveBotSession = `-- name: SaveBotSession :exec
UPDATE bot_sessions
SET node_id = $1, vars = $2, status = $3, end_reason = $4, updated_at = now(),
    ended_at = CASE WHEN $3::text = 'active' THEN NULL ELSE now() END
WHERE id = $5
`

type SaveBotSessionParams struct {
	NodeID    *string
	Vars      []byte
	Status    string
	EndReason *string
	ID        uuid.UUID
}

func (q *Queries) SaveBotSession(ctx context.Context, arg SaveBotSessionParams) error {
	_, err := q.db.Exec(ctx, saveBotSession,
		arg.NodeID,
		arg.Vars,
		arg.Status,
		arg.EndReason,
		arg.ID,
	)
	return err
}

const setBotStatus = `-- name: SetBotStatus :one
UPDATE bots SET status = $1, updated_at = now() WHERE id = $2 RETURNING id, tenant_id, name, status, phone_number_id, flow, created_by, created_at, updated_at
`

type SetBotStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) SetBotStatus(ctx context.Context, arg SetBotStatusParams) (Bot, error) {
	row := q.db.QueryRow(ctx, setBotStatus, arg.Status, arg.ID)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.PhoneNumberID,
		&i.Flow,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const stopBotSessionsForBot = `-- name: StopBotSessionsForBot :exec
UPDATE bot_sessions SET status = 'stopped', end_reason = 'bot_paused', ended_at = now(), updated_at = now()
WHERE bot_id = $1 AND status = 'active'
`

func (q *Queries) StopBotSessionsForBot(ctx context.Context, botID uuid.UUID) error {
	_, err := q.db.Exec(ctx, stopBotSessionsForBot, botID)
	return err
}

const updateBot = `-- name: UpdateBot :one
UPDATE bots
SET name = $1, flow = $2, phone_number_id = $3, updated_at = now()
WHERE id = $4
RETURNING id, tenant_id, name, status, phone_number_id, flow, created_by, created_at, updated_at
`

type UpdateBotParams struct {
	Name          string
	Flow          []byte
	PhoneNumberID *uuid.UUID
	ID            uuid.UUID
}

func (q *Queries) UpdateBot(ctx context.Context, arg UpdateBotParams) (Bot, error) {
	row := q.db.QueryRow(ctx, updateBot,
		arg.Name,
		arg.Flow,
		arg.PhoneNumberID,
		arg.ID,
	)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.PhoneNumberID,
		&i.Flow,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
