// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaigns.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const audienceCounts = `-- name: AudienceCounts :one
SELECT count(*)::int AS total,
       (count(*) FILTER (WHERE NOT c.blocked AND c.opt_in_status = 'opted_in'))::int AS eligible,
       (count(*) FILTER (WHERE c.blocked))::int AS blocked,
       (count(*) FILTER (WHERE NOT c.blocked AND c.opt_in_status = 'opted_out'))::int AS opted_out,
       (count(*) FILTER (WHERE NOT c.blocked AND c.opt_in_status = 'unknown'))::int AS no_opt_in
FROM contacts c
WHERE c.id = ANY($1::uuid[])
   OR EXISTS (SELECT 1 FROM contact_tags ct JOIN tags t ON t.id = ct.tag_id
              WHERE ct.contact_id = c.id AND t.name = ANY($2::citext[]))
`

type AudienceCountsParams struct {
	ContactIds []uuid.UUID
	Tags       []string
}

type AudienceCountsRow struct {
	Total    int32
	Eligible int32
	Blocked  int32
	OptedOut int32
	NoOptIn  int32
}

// How many contacts an audience reaches, and why the others would be skipped.
func (q *Queries) AudienceCounts(ctx context.Context, arg AudienceCountsParams) (AudienceCountsRow, error) {
	row := q.db.QueryRow(ctx, audienceCounts, arg.ContactIds, arg.Tags)
	var i AudienceCountsRow
	err := row.Scan(
		&i.Total,
		&i.Eligible,
		&i.Blocked,
		&i.OptedOut,
		&i.NoOptIn,
	)
	return i, err
}

const businessInitiatedToday = `-- name: BusinessInitiatedToday :one
SELECT count(DISTINCT contact_id)::int FROM messages
WHERE phone_number_id = $1 AND direction = 'outbound' AND type = 'template'
  AND status <> 'failed' AND created_at > now() - interval '24 hours'
`

// Distinct customers sent a template from this number in the last 24 hours: what Meta's
// messaging limit counts.
func (q *Queries) BusinessInitiatedToday(ctx context.Context, phoneNumberID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, businessInitiatedToday, phoneNumberID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const campaignCounts = `-- name: CampaignCounts :many
SELECT status, count(*)::int AS n FROM campaigns
WHERE $1::uuid IS NULL OR phone_number_id = $1
GROUP BY status
`

type CampaignCountsRow struct {
	Status CampaignStatus
	N      int32
}

func (q *Queries) CampaignCounts(ctx context.Context, phoneNumberID *uuid.UUID) ([]CampaignCountsRow, error) {
	rows, err := q.db.Query(ctx, campaignCounts, phoneNumberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignCountsRow
	for rows.Next() {
		var i CampaignCountsRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const campaignStats = `-- name: CampaignStats :many
SELECT campaign_id,
       count(*)::int AS total,
       (count(*) FILTER (WHERE status = 'pending'))::int AS pending,
       (count(*) FILTER (WHERE status = 'skipped'))::int AS skipped,
       (count(*) FILTER (WHERE status = 'queued'))::int AS queued,
       (count(*) FILTER (WHERE status IN ('sent', 'delivered', 'read')))::int AS sent,
       (count(*) FILTER (WHERE status IN ('delivered', 'read')))::int AS delivered,
       (count(*) FILTER (WHERE status = 'read'))::int AS read,
       (count(*) FILTER (WHERE status = 'failed'))::int AS failed
FROM campaign_recipients
WHERE campaign_id = ANY($1::uuid[])
GROUP BY campaign_id
`

type CampaignStatsRow struct {
	CampaignID uuid.UUID
	Total      int32
	Pending    int32
	Skipped    int32
	Queued     int32
	Sent       int32
	Delivered  int32
	Read       int32
	Failed     int32
}

// Recipient counts per campaign. sent, delivered and read are cumulative: a read message was
// also delivered and sent.
func (q *Queries) CampaignStats(ctx context.Context, ids []uuid.UUID) ([]CampaignStatsRow, error) {
	rows, err := q.db.Query(ctx, campaignStats, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignStatsRow
	for rows.Next() {
		var i CampaignStatsRow
		if err := rows.Scan(
			&i.CampaignID,
			&i.Total,
			&i.Pending,
			&i.Skipped,
			&i.Queued,
			&i.Sent,
			&i.Delivered,
			&i.Read,
			&i.Failed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDraftCampaign = `-- name: DeleteDraftCampaign :execrows
DELETE FROM campaigns WHERE id = $1 AND status = 'draft'
`

func (q *Queries) DeleteDraftCampaign(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDraftCampaign, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expandCampaignAudience = `-- name: ExpandCampaignAudience :execrows
INSERT INTO campaign_recipients (tenant_id, campaign_id, contact_id, status, skip_reason)
SELECT c.tenant_id, $1, c.id,
       CASE WHEN c.blocked OR c.opt_in_status <> 'opted_in' THEN 'skipped' ELSE 'pending' END::recipient_status,
       CASE WHEN c.blocked THEN 'blocked'
            WHEN c.opt_in_status = 'opted_out' THEN 'opted_out'
            WHEN c.opt_in_status <> 'opted_in' THEN 'no_opt_in' END
FROM contacts c
WHERE c.id = ANY($2::uuid[])
   OR EXISTS (SELECT 1 FROM contact_tags ct JOIN tags t ON t.id = ct.tag_id
              WHERE ct.contact_id = c.id AND t.name = ANY($3::citext[]))
ON CONFLICT DO NOTHING
`

type ExpandCampaignAudienceParams struct {
	CampaignID uuid.UUID
	ContactIds []uuid.UUID
	Tags       []string
}

// Adds every contact in the audience once. Blocked, opted-out and never-opted-in contacts are
// recorded as skipped with the reason.
func (q *Queries) ExpandCampaignAudience(ctx context.Context, arg ExpandCampaignAudienceParams) (int64, error) {
	result, err := q.db.Exec(ctx, expandCampaignAudience, arg.CampaignID, arg.ContactIds, arg.Tags)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishCampaign = `-- name: FinishCampaign :exec
UPDATE campaigns SET status = $1, finished_at = now(), updated_at = now() WHERE id = $2
`

type FinishCampaignParams struct {
	Status CampaignStatus
	ID     uuid.UUID
}

func (q *Queries) FinishCampaign(ctx context.Context, arg FinishCampaignParams) error {
	_, err := q.db.Exec(ctx, finishCampaign, arg.Status, arg.ID)
	return err
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, tenant_id, phone_number_id, template_id, name, audience, variables, status, scheduled_at, started_at, finished_at, send_rate_per_min, stats, created_by, api_key_id, created_at, updated_at, run_generation FROM campaigns WHERE id = $1
`

func (q *Queries) GetCampaign(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneNumberID,
		&i.TemplateID,
		&i.Name,
		&i.Audience,
		&i.Variables,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SendRatePerMin,
		&i.Stats,
		&i.CreatedBy,
		&i.ApiKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RunGeneration,
	)
	return i, err
}

const getCampaignForUpdate = `-- name: GetCampaignForUpdate :one
SELECT id, tenant_id, phone_number_id, template_id, name, audience, variables, status, scheduled_at, started_at, finished_at, send_rate_per_min, stats, created_by, api_key_id, created_at, updated_at, run_generation FROM campaigns WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetCampaignForUpdate(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignForUpdate, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneNumberID,
		&i.TemplateID,
		&i.Name,
		&i.Audience,
		&i.Variables,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SendRatePerMin,
		&i.Stats,
		&i.CreatedBy,
		&i.ApiKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RunGeneration,
	)
	return i, err
}

const hasPendingRecipients = `-- name: HasPendingRecipients :one
SELECT EXISTS (SELECT 1 FROM campaign_recipients WHERE campaign_id = $1 AND status = 'pending')
`

func (q *Queries) HasPendingRecipients(ctx context.Context, campaignID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasPendingRecipients, campaignID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertCampaign = `-- name: InsertCampaign :one
INSERT INTO campaigns (id, tenant_id, phone_number_id, template_id, name, audience, variables, status,
                       scheduled_at, send_rate_per_min, created_by, api_key_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, tenant_id, phone_number_id, template_id, name, audience, variables, status, scheduled_at, started_at, finished_at, send_rate_per_min, stats, created_by, api_key_id, created_at, updated_at, run_generation
`

type InsertCampaignParams struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	PhoneNumberID  uuid.UUID
	TemplateID     uuid.UUID
	Name           string
	Audience       []byte
	Variables      []byte
	Status         CampaignStatus
	ScheduledAt    *time.Time
	SendRatePerMin *int32
	CreatedBy      *uuid.UUID
	ApiKeyID       *uuid.UUID
}

func (q *Queries) InsertCampaign(ctx context.Context, arg InsertCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, insertCampaign,
		arg.ID,
		arg.TenantID,
		arg.PhoneNumberID,
		arg.TemplateID,
		arg.Name,
		arg.Audience,
		arg.Variables,
		arg.Status,
		arg.ScheduledAt,
		arg.SendRatePerMin,
		arg.CreatedBy,
		arg.ApiKeyID,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneNumberID,
		&i.TemplateID,
		&i.Name,
		&i.Audience,
		&i.Variables,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SendRatePerMin,
		&i.Stats,
		&i.CreatedBy,
		&i.ApiKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RunGeneration,
	)
	return i, err
}

const insertCampaignMessage = `-- name: InsertCampaignMessage :one
INSERT INTO messages (id, tenant_id, conversation_id, phone_number_id, contact_id, direction, origin,
                      type, content, template_id, status, campaign_id)
VALUES ($1, $2, $3, $4, $5, 'outbound', 'campaign', 'template', $6, $7, 'queued', $8)
RETURNING id, tenant_id, conversation_id, phone_number_id, contact_id, direction, origin, wamid, type, content, media_id, template_id, reply_to_wamid, status, error_code, error_title, sent_by_user_id, api_key_id, campaign_id, idempotency_key, pricing_category, pricing_billable, recipient_country, meta_timestamp, status_updated_at, created_at, bot_id
`

type InsertCampaignMessageParams struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ConversationID uuid.UUID
	PhoneNumberID  uuid.UUID
	ContactID      uuid.UUID
	Content        []byte
	TemplateID     *uuid.UUID
	CampaignID     *uuid.UUID
}

func (q *Queries) InsertCampaignMessage(ctx context.Context, arg InsertCampaignMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertCampaignMessage,
		arg.ID,
		arg.TenantID,
		arg.ConversationID,
		arg.PhoneNumberID,
		arg.ContactID,
		arg.Content,
		arg.TemplateID,
		arg.CampaignID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ConversationID,
		&i.PhoneNumberID,
		&i.ContactID,
		&i.Direction,
		&i.Origin,
		&i.Wamid,
		&i.Type,
		&i.Content,
		&i.MediaID,
		&i.TemplateID,
		&i.ReplyToWamid,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorTitle,
		&i.SentByUserID,
		&i.ApiKeyID,
		&i.CampaignID,
		&i.IdempotencyKey,
		&i.PricingCategory,
		&i.PricingBillable,
		&i.RecipientCountry,
		&i.MetaTimestamp,
		&i.StatusUpdatedAt,
		&i.CreatedAt,
		&i.BotID,
	)
	return i, err
}

const listCampaignRecipients = `-- name: ListCampaignRecipients :many
SELECT r.contact_id, r.status, r.skip_reason, r.message_id, r.error_code, r.updated_at,
       c.wa_id, coalesce(c.name, c.profile_name) AS contact_name
FROM campaign_recipients r JOIN contacts c ON c.id = r.contact_id
WHERE r.campaign_id = $1
  AND ($2::recipient_status IS NULL OR r.status = $2)
  AND ($3::uuid IS NULL OR r.contact_id > $3)
ORDER BY r.contact_id
LIMIT $4
`

type ListCampaignRecipientsParams struct {
	CampaignID uuid.UUID
	Status     *RecipientStatus
	AfterID    *uuid.UUID
	Lim        int32
}

type ListCampaignRecipientsRow struct {
	ContactID   uuid.UUID
	Status      RecipientStatus
	SkipReason  *string
	MessageID   *uuid.UUID
	ErrorCode   *int32
	UpdatedAt   time.Time
	WaID        string
	ContactName *string
}

func (q *Queries) ListCampaignRecipients(ctx context.Context, arg ListCampaignRecipientsParams) ([]ListCampaignRecipientsRow, error) {
	rows, err := q.db.Query(ctx, listCampaignRecipients,
		arg.CampaignID,
		arg.Status,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignRecipientsRow
	for rows.Next() {
		var i ListCampaignRecipientsRow
		if err := rows.Scan(
			&i.ContactID,
			&i.Status,
			&i.SkipReason,
			&i.MessageID,
			&i.ErrorCode,
			&i.UpdatedAt,
			&i.WaID,
			&i.ContactName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, tenant_id, phone_number_id, template_id, name, audience, variables, status, scheduled_at, started_at, finished_at, send_rate_per_min, stats, created_by, api_key_id, created_at, updated_at, run_generation FROM campaigns
WHERE ($1::uuid IS NULL OR phone_number_id = $1)
  AND ($2::text[] IS NULL OR status::text = ANY($2::text[]))
  AND ($3::timestamptz IS NULL OR (created_at, id) < ($3, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListCampaignsParams struct {
	PhoneNumberID *uuid.UUID
	Statuses      []string
	BeforeAt      *time.Time
	BeforeID      *uuid.UUID
	Lim           int32
}

func (q *Queries) ListCampaigns(ctx context.Context, arg ListCampaignsParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaigns,
		arg.PhoneNumberID,
		arg.Statuses,
		arg.BeforeAt,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PhoneNumberID,
			&i.TemplateID,
			&i.Name,
			&i.Audience,
			&i.Variables,
			&i.Status,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.SendRatePerMin,
			&i.Stats,
			&i.CreatedBy,
			&i.ApiKeyID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RunGeneration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextCampaignRecipients = `-- name: NextCampaignRecipients :many
SELECT c.id, c.tenant_id, c.wa_id, c.name, c.profile_name, c.language, c.custom_fields, c.opt_in_status, c.opted_in_at, c.opted_out_at, c.blocked, c.created_at, c.updated_at
FROM campaign_recipients r JOIN contacts c ON c.id = r.contact_id
WHERE r.campaign_id = $1 AND r.status = 'pending'
ORDER BY r.contact_id
LIMIT $2
`

type NextCampaignRecipientsParams struct {
	CampaignID uuid.UUID
	Lim        int32
}

type NextCampaignRecipientsRow struct {
	Contact Contact
}

// The next pending recipients to send to, with their contact.
func (q *Queries) NextCampaignRecipients(ctx context.Context, arg NextCampaignRecipientsParams) ([]NextCampaignRecipientsRow, error) {
	rows, err := q.db.Query(ctx, nextCampaignRecipients, arg.CampaignID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NextCampaignRecipientsRow
	for rows.Next() {
		var i NextCampaignRecipientsRow
		if err := rows.Scan(
			&i.Contact.ID,
			&i.Contact.TenantID,
			&i.Contact.WaID,
			&i.Contact.Name,
			&i.Contact.ProfileName,
			&i.Contact.Language,
			&i.Contact.CustomFields,
			&i.Contact.OptInStatus,
			&i.Contact.OptedInAt,
			&i.Contact.OptedOutAt,
			&i.Contact.Blocked,
			&i.Contact.CreatedAt,
			&i.Contact.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueCampaignRecipient = `-- name: QueueCampaignRecipient :exec
UPDATE campaign_recipients SET status = 'queued', message_id = $1, updated_at = now()
WHERE campaign_id = $2 AND contact_id = $3
`

type QueueCampaignRecipientParams struct {
	MessageID  *uuid.UUID
	CampaignID uuid.UUID
	ContactID  uuid.UUID
}

func (q *Queries) QueueCampaignRecipient(ctx context.Context, arg QueueCampaignRecipientParams) error {
	_, err := q.db.Exec(ctx, queueCampaignRecipient, arg.MessageID, arg.CampaignID, arg.ContactID)
	return err
}

const setCampaignStatus = `-- name: SetCampaignStatus :one
UPDATE campaigns SET status = $1, run_generation = run_generation + 1, updated_at = now()
WHERE id = $2
RETURNING id, tenant_id, phone_number_id, template_id, name, audience, variables, status, scheduled_at, started_at, finished_at, send_rate_per_min, stats, created_by, api_key_id, created_at, updated_at, run_generation
`

type SetCampaignStatusParams struct {
	Status CampaignStatus
	ID     uuid.UUID
}

// Pauses or resumes a campaign. The generation changes so only the job queued now runs.
func (q *Queries) SetCampaignStatus(ctx context.Context, arg SetCampaignStatusParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, setCampaignStatus, arg.Status, arg.ID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneNumberID,
		&i.TemplateID,
		&i.Name,
		&i.Audience,
		&i.Variables,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SendRatePerMin,
		&i.Stats,
		&i.CreatedBy,
		&i.ApiKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RunGeneration,
	)
	return i, err
}

const skipCampaignRecipient = `-- name: SkipCampaignRecipient :exec
UPDATE campaign_recipients SET status = 'skipped', skip_reason = $1, updated_at = now()
WHERE campaign_id = $2 AND contact_id = $3
`

type SkipCampaignRecipientParams struct {
	Reason     *string
	CampaignID uuid.UUID
	ContactID  uuid.UUID
}

func (q *Queries) SkipCampaignRecipient(ctx context.Context, arg SkipCampaignRecipientParams) error {
	_, err := q.db.Exec(ctx, skipCampaignRecipient, arg.Reason, arg.CampaignID, arg.ContactID)
	return err
}

const skipPendingRecipients = `-- name: SkipPendingRecipients :exec
UPDATE campaign_recipients SET status = 'skipped', skip_reason = $1, updated_at = now()
WHERE campaign_id = $2 AND status = 'pending'
`

type SkipPendingRecipientsParams struct {
	Reason     *string
	CampaignID uuid.UUID
}

func (q *Queries) SkipPendingRecipients(ctx context.Context, arg SkipPendingRecipientsParams) error {
	_, err := q.db.Exec(ctx, skipPendingRecipients, arg.Reason, arg.CampaignID)
	return err
}

const startCampaign = `-- name: StartCampaign :exec
UPDATE campaigns SET status = 'running', started_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) StartCampaign(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, startCampaign, id)
	return err
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns
SET phone_number_id = $1, template_id = $2, name = $3, audience = $4,
    variables = $5, status = $6, scheduled_at = $7,
    send_rate_per_min = $8, run_generation = run_generation + 1, updated_at = now()
WHERE id = $9
RETURNING id, tenant_id, phone_number_id, template_id, name, audience, variables, status, scheduled_at, started_at, finished_at, send_rate_per_min, stats, created_by, api_key_id, created_at, updated_at, run_generation
`

type UpdateCampaignParams struct {
	PhoneNumberID  uuid.UUID
	TemplateID     uuid.UUID
	Name           string
	Audience       []byte
	Variables      []byte
	Status         CampaignStatus
	ScheduledAt    *time.Time
	SendRatePerMin *int32
	ID             uuid.UUID
}

// Replaces a draft or scheduled campaign's settings and invalidates its queued run job.
func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaign,
		arg.PhoneNumberID,
		arg.TemplateID,
		arg.Name,
		arg.Audience,
		arg.Variables,
		arg.Status,
		arg.ScheduledAt,
		arg.SendRatePerMin,
		arg.ID,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneNumberID,
		&i.TemplateID,
		&i.Name,
		&i.Audience,
		&i.Variables,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SendRatePerMin,
		&i.Stats,
		&i.CreatedBy,
		&i.ApiKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RunGeneration,
	)
	return i, err
}
