// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addContactTag = `-- name: AddContactTag :exec
INSERT INTO contact_tags (tenant_id, contact_id, tag_id) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddContactTagParams struct {
	TenantID  uuid.UUID
	ContactID uuid.UUID
	TagID     uuid.UUID
}

func (q *Queries) AddContactTag(ctx context.Context, arg AddContactTagParams) error {
	_, err := q.db.Exec(ctx, addContactTag, arg.TenantID, arg.ContactID, arg.TagID)
	return err
}

const contactConversationCount = `-- name: ContactConversationCount :one
SELECT count(*)::int FROM (
    SELECT created_at, lag(created_at) OVER (ORDER BY created_at) AS prev
    FROM messages WHERE contact_id = $1 AND direction = 'inbound'
) m
WHERE prev IS NULL OR created_at > prev + interval '24 hours'
`

// Customer service conversations with a contact: each inbound message that arrives more than 24
// hours after the previous one starts a new one.
func (q *Queries) ContactConversationCount(ctx context.Context, contactID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, contactConversationCount, contactID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const contactLastMessages = `-- name: ContactLastMessages :many
SELECT contact_id, max(last_message_at)::timestamptz AS last_message_at
FROM conversations
WHERE contact_id = ANY($1::uuid[]) AND last_message_at IS NOT NULL
GROUP BY contact_id
`

type ContactLastMessagesRow struct {
	ContactID     uuid.UUID
	LastMessageAt time.Time
}

func (q *Queries) ContactLastMessages(ctx context.Context, ids []uuid.UUID) ([]ContactLastMessagesRow, error) {
	rows, err := q.db.Query(ctx, contactLastMessages, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactLastMessagesRow
	for rows.Next() {
		var i ContactLastMessagesRow
		if err := rows.Scan(&i.ContactID, &i.LastMessageAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contactOptInSources = `-- name: ContactOptInSources :many
SELECT DISTINCT ON (contact_id) contact_id, source
FROM consent_events
WHERE contact_id = ANY($1::uuid[]) AND kind = 'opt_in'
ORDER BY contact_id, occurred_at DESC
`

type ContactOptInSourcesRow struct {
	ContactID uuid.UUID
	Source    ConsentSource
}

// Where each contact's latest opt-in came from.
func (q *Queries) ContactOptInSources(ctx context.Context, ids []uuid.UUID) ([]ContactOptInSourcesRow, error) {
	rows, err := q.db.Query(ctx, contactOptInSources, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactOptInSourcesRow
	for rows.Next() {
		var i ContactOptInSourcesRow
		if err := rows.Scan(&i.ContactID, &i.Source); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contactSummary = `-- name: ContactSummary :one
SELECT count(*)::int AS total,
       (count(*) FILTER (WHERE NOT blocked AND opt_in_status = 'opted_in'))::int AS opted_in,
       (count(*) FILTER (WHERE NOT blocked AND opt_in_status = 'opted_out'))::int AS opted_out,
       (count(*) FILTER (WHERE NOT blocked AND opt_in_status = 'unknown'))::int AS unknown,
       (count(*) FILTER (WHERE blocked))::int AS blocked
FROM contacts
`

type ContactSummaryRow struct {
	Total    int32
	OptedIn  int32
	OptedOut int32
	Unknown  int32
	Blocked  int32
}

// Totals for the contacts header and filter tabs. Consent counts leave out blocked contacts.
func (q *Queries) ContactSummary(ctx context.Context) (ContactSummaryRow, error) {
	row := q.db.QueryRow(ctx, contactSummary)
	var i ContactSummaryRow
	err := row.Scan(
		&i.Total,
		&i.OptedIn,
		&i.OptedOut,
		&i.Unknown,
		&i.Blocked,
	)
	return i, err
}

const countContacts = `-- name: CountContacts :one
SELECT count(*)::int FROM contacts c
WHERE ($1::opt_in_status IS NULL OR c.opt_in_status = $1)
  AND ($2::text IS NULL OR EXISTS (
        SELECT 1 FROM contact_tags ct JOIN tags t ON t.id = ct.tag_id
        WHERE ct.contact_id = c.id AND t.name = $2::citext))
  AND ($3::bool IS NULL OR c.blocked = $3)
  AND ($4::text IS NULL OR c.wa_id LIKE '%' || $4 || '%'
       OR c.name ILIKE '%' || $4 || '%' OR c.profile_name ILIKE '%' || $4 || '%')
`

type CountContactsParams struct {
	OptInStatus *OptInStatus
	Tag         *string
	Blocked     *bool
	Search      *string
}

// How many contacts match the list filters, for "Showing 1-50 of N".
func (q *Queries) CountContacts(ctx context.Context, arg CountContactsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countContacts,
		arg.OptInStatus,
		arg.Tag,
		arg.Blocked,
		arg.Search,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getContact = `-- name: GetContact :one
SELECT id, tenant_id, wa_id, name, profile_name, language, custom_fields, opt_in_status, opted_in_at, opted_out_at, blocked, created_at, updated_at FROM contacts WHERE id = $1
`

func (q *Queries) GetContact(ctx context.Context, id uuid.UUID) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WaID,
		&i.Name,
		&i.ProfileName,
		&i.Language,
		&i.CustomFields,
		&i.OptInStatus,
		&i.OptedInAt,
		&i.OptedOutAt,
		&i.Blocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertConsentEvent = `-- name: InsertConsentEvent :exec
INSERT INTO consent_events (tenant_id, contact_id, kind, source, evidence, recorded_by, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertConsentEventParams struct {
	TenantID   uuid.UUID
	ContactID  uuid.UUID
	Kind       ConsentKind
	Source     ConsentSource
	Evidence   *string
	RecordedBy *uuid.UUID
	OccurredAt time.Time
}

func (q *Queries) InsertConsentEvent(ctx context.Context, arg InsertConsentEventParams) error {
	_, err := q.db.Exec(ctx, insertConsentEvent,
		arg.TenantID,
		arg.ContactID,
		arg.Kind,
		arg.Source,
		arg.Evidence,
		arg.RecordedBy,
		arg.OccurredAt,
	)
	return err
}

const listConsentEvents = `-- name: ListConsentEvents :many
SELECT e.id, e.tenant_id, e.contact_id, e.kind, e.source, e.evidence, e.recorded_by, e.occurred_at, u.name AS recorded_by_name
FROM consent_events e LEFT JOIN users u ON u.id = e.recorded_by
WHERE e.contact_id = $1
ORDER BY e.occurred_at DESC
LIMIT 100
`

type ListConsentEventsRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ContactID      uuid.UUID
	Kind           ConsentKind
	Source         ConsentSource
	Evidence       *string
	RecordedBy     *uuid.UUID
	OccurredAt     time.Time
	RecordedByName *string
}

func (q *Queries) ListConsentEvents(ctx context.Context, contactID uuid.UUID) ([]ListConsentEventsRow, error) {
	rows, err := q.db.Query(ctx, listConsentEvents, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConsentEventsRow
	for rows.Next() {
		var i ListConsentEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ContactID,
			&i.Kind,
			&i.Source,
			&i.Evidence,
			&i.RecordedBy,
			&i.OccurredAt,
			&i.RecordedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContacts = `-- name: ListContacts :many
SELECT c.id, c.tenant_id, c.wa_id, c.name, c.profile_name, c.language, c.custom_fields, c.opt_in_status, c.opted_in_at, c.opted_out_at, c.blocked, c.created_at, c.updated_at FROM contacts c
WHERE ($1::opt_in_status IS NULL OR c.opt_in_status = $1)
  AND ($2::text IS NULL OR EXISTS (
        SELECT 1 FROM contact_tags ct JOIN tags t ON t.id = ct.tag_id
        WHERE ct.contact_id = c.id AND t.name = $2::citext))
  AND ($3::bool IS NULL OR c.blocked = $3)
  AND ($4::text IS NULL OR c.wa_id LIKE '%' || $4 || '%'
       OR c.name ILIKE '%' || $4 || '%' OR c.profile_name ILIKE '%' || $4 || '%')
  AND ($5::timestamptz IS NULL OR (c.created_at, c.id) < ($5, $6::uuid))
ORDER BY c.created_at DESC, c.id DESC
LIMIT $7
`

type ListContactsParams struct {
	OptInStatus *OptInStatus
	Tag         *string
	Blocked     *bool
	Search      *string
	BeforeAt    *time.Time
	BeforeID    *uuid.UUID
	Lim         int32
}

func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContacts,
		arg.OptInStatus,
		arg.Tag,
		arg.Blocked,
		arg.Search,
		arg.BeforeAt,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WaID,
			&i.Name,
			&i.ProfileName,
			&i.Language,
			&i.CustomFields,
			&i.OptInStatus,
			&i.OptedInAt,
			&i.OptedOutAt,
			&i.Blocked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.name, count(ct.contact_id) AS contacts
FROM tags t LEFT JOIN contact_tags ct ON ct.tag_id = t.id
GROUP BY t.id, t.name
ORDER BY t.name
`

type ListTagsRow struct {
	ID       uuid.UUID
	Name     string
	Contacts int64
}

func (q *Queries) ListTags(ctx context.Context) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsRow
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Contacts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeContactTag = `-- name: RemoveContactTag :exec
DELETE FROM contact_tags ct USING tags t
WHERE ct.tag_id = t.id AND ct.contact_id = $1 AND t.name = $2::citext
`

type RemoveContactTagParams struct {
	ContactID uuid.UUID
	Name      string
}

func (q *Queries) RemoveContactTag(ctx context.Context, arg RemoveContactTagParams) error {
	_, err := q.db.Exec(ctx, removeContactTag, arg.ContactID, arg.Name)
	return err
}

const setContactConsent = `-- name: SetContactConsent :one
UPDATE contacts
SET opt_in_status = $1,
    opted_in_at = CASE WHEN $1 = 'opted_in'::opt_in_status THEN $2::timestamptz ELSE opted_in_at END,
    opted_out_at = CASE WHEN $1 = 'opted_out'::opt_in_status THEN $2::timestamptz ELSE opted_out_at END,
    updated_at = now()
WHERE id = $3
RETURNING id, tenant_id, wa_id, name, profile_name, language, custom_fields, opt_in_status, opted_in_at, opted_out_at, blocked, created_at, updated_at
`

type SetContactConsentParams struct {
	Status OptInStatus
	At     time.Time
	ID     uuid.UUID
}

func (q *Queries) SetContactConsent(ctx context.Context, arg SetContactConsentParams) (Contact, error) {
	row := q.db.QueryRow(ctx, setContactConsent, arg.Status, arg.At, arg.ID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WaID,
		&i.Name,
		&i.ProfileName,
		&i.Language,
		&i.CustomFields,
		&i.OptInStatus,
		&i.OptedInAt,
		&i.OptedOutAt,
		&i.Blocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts
SET name = CASE WHEN $1::bool THEN $2 ELSE name END,
    language = CASE WHEN $3::bool THEN $4 ELSE language END,
    custom_fields = jsonb_strip_nulls(custom_fields || coalesce($5::jsonb, '{}')),
    blocked = coalesce($6, blocked),
    updated_at = now()
WHERE id = $7
RETURNING id, tenant_id, wa_id, name, profile_name, language, custom_fields, opt_in_status, opted_in_at, opted_out_at, blocked, created_at, updated_at
`

type UpdateContactParams struct {
	SetName      bool
	Name         *string
	SetLanguage  bool
	Language     *string
	CustomFields []byte
	Blocked      *bool
	ID           uuid.UUID
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.SetName,
		arg.Name,
		arg.SetLanguage,
		arg.Language,
		arg.CustomFields,
		arg.Blocked,
		arg.ID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WaID,
		&i.Name,
		&i.ProfileName,
		&i.Language,
		&i.CustomFields,
		&i.OptInStatus,
		&i.OptedInAt,
		&i.OptedOutAt,
		&i.Blocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertContact = `-- name: UpsertContact :one
INSERT INTO contacts (id, tenant_id, wa_id, name, language, custom_fields)
VALUES ($1, $2, $3, $4, $5, jsonb_strip_nulls(coalesce($6::jsonb, '{}')))
ON CONFLICT (tenant_id, wa_id) DO UPDATE
SET name = coalesce(EXCLUDED.name, contacts.name),
    language = coalesce(EXCLUDED.language, contacts.language),
    custom_fields = jsonb_strip_nulls(contacts.custom_fields || coalesce($6::jsonb, '{}')),
    updated_at = now()
RETURNING id, tenant_id, wa_id, name, profile_name, language, custom_fields, opt_in_status, opted_in_at, opted_out_at, blocked, created_at, updated_at, (xmax = 0) AS inserted
`

type UpsertContactParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	WaID         string
	Name         *string
	Language     *string
	CustomFields []byte
}

type UpsertContactRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	WaID         string
	Name         *string
	ProfileName  *string
	Language     *string
	CustomFields []byte
	OptInStatus  OptInStatus
	OptedInAt    *time.Time
	OptedOutAt   *time.Time
	Blocked      bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Inserted     bool
}

// Creates a contact or updates the given fields of the one with this number. custom_fields are
// merged; a null value removes a field.
func (q *Queries) UpsertContact(ctx context.Context, arg UpsertContactParams) (UpsertContactRow, error) {
	row := q.db.QueryRow(ctx, upsertContact,
		arg.ID,
		arg.TenantID,
		arg.WaID,
		arg.Name,
		arg.Language,
		arg.CustomFields,
	)
	var i UpsertContactRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WaID,
		&i.Name,
		&i.ProfileName,
		&i.Language,
		&i.CustomFields,
		&i.OptInStatus,
		&i.OptedInAt,
		&i.OptedOutAt,
		&i.Blocked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Inserted,
	)
	return i, err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (tenant_id, name) VALUES ($1, $2)
ON CONFLICT (tenant_id, name) DO UPDATE SET name = tags.name
RETURNING id
`

type UpsertTagParams struct {
	TenantID uuid.UUID
	Name     string
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertTag, arg.TenantID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
