// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addContactTag = `-- name: AddContactTag :exec
INSERT INTO contact_tags (tenant_id, contact_id, tag_id) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddContactTagParams struct {
	TenantID  uuid.UUID
	ContactID uuid.UUID
	TagID     uuid.UUID
}

func (q *Queries) AddContactTag(ctx context.Context, arg AddContactTagParams) error {
	_, err := q.db.Exec(ctx, addContactTag, arg.TenantID, arg.ContactID, arg.TagID)
	return err
}

const getContact = `-- name: GetContact :one
SELECT id, tenant_id, wa_id, name, profile_name, language, custom_fields, opt_in_status, opted_in_at, opted_out_at, blocked, created_at, updated_at FROM contacts WHERE id = $1
`

func (q *Queries) GetContact(ctx context.Context, id uuid.UUID) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WaID,
		&i.Name,
		&i.ProfileName,
		&i.Language,
		&i.CustomFields,
		&i.OptInStatus,
		&i.OptedInAt,
		&i.OptedOutAt,
		&i.Blocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertConsentEvent = `-- name: InsertConsentEvent :exec
INSERT INTO consent_events (tenant_id, contact_id, kind, source, evidence, recorded_by, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertConsentEventParams struct {
	TenantID   uuid.UUID
	ContactID  uuid.UUID
	Kind       ConsentKind
	Source     ConsentSource
	Evidence   *string
	RecordedBy *uuid.UUID
	OccurredAt time.Time
}

func (q *Queries) InsertConsentEvent(ctx context.Context, arg InsertConsentEventParams) error {
	_, err := q.db.Exec(ctx, insertConsentEvent,
		arg.TenantID,
		arg.ContactID,
		arg.Kind,
		arg.Source,
		arg.Evidence,
		arg.RecordedBy,
		arg.OccurredAt,
	)
	return err
}

const listConsentEvents = `-- name: ListConsentEvents :many
SELECT e.id, e.tenant_id, e.contact_id, e.kind, e.source, e.evidence, e.recorded_by, e.occurred_at, u.name AS recorded_by_name
FROM consent_events e LEFT JOIN users u ON u.id = e.recorded_by
WHERE e.contact_id = $1
ORDER BY e.occurred_at DESC
LIMIT 100
`

type ListConsentEventsRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ContactID      uuid.UUID
	Kind           ConsentKind
	Source         ConsentSource
	Evidence       *string
	RecordedBy     *uuid.UUID
	OccurredAt     time.Time
	RecordedByName *string
}

func (q *Queries) ListConsentEvents(ctx context.Context, contactID uuid.UUID) ([]ListConsentEventsRow, error) {
	rows, err := q.db.Query(ctx, listConsentEvents, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConsentEventsRow
	for rows.Next() {
		var i ListConsentEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ContactID,
			&i.Kind,
			&i.Source,
			&i.Evidence,
			&i.RecordedBy,
			&i.OccurredAt,
			&i.RecordedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContacts = `-- name: ListContacts :many
SELECT c.id, c.tenant_id, c.wa_id, c.name, c.profile_name, c.language, c.custom_fields, c.opt_in_status, c.opted_in_at, c.opted_out_at, c.blocked, c.created_at, c.updated_at FROM contacts c
WHERE ($1::opt_in_status IS NULL OR c.opt_in_status = $1)
  AND ($2::text IS NULL OR EXISTS (
        SELECT 1 FROM contact_tags ct JOIN tags t ON t.id = ct.tag_id
        WHERE ct.contact_id = c.id AND t.name = $2::citext))
  AND ($3::text IS NULL OR c.wa_id LIKE '%' || $3 || '%'
       OR c.name ILIKE '%' || $3 || '%' OR c.profile_name ILIKE '%' || $3 || '%')
  AND ($4::timestamptz IS NULL OR (c.created_at, c.id) < ($4, $5::uuid))
ORDER BY c.created_at DESC, c.id DESC
LIMIT $6
`

type ListContactsParams struct {
	OptInStatus *OptInStatus
	Tag         *string
	Search      *string
	BeforeAt    *time.Time
	BeforeID    *uuid.UUID
	Lim         int32
}

func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContacts,
		arg.OptInStatus,
		arg.Tag,
		arg.Search,
		arg.BeforeAt,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WaID,
			&i.Name,
			&i.ProfileName,
			&i.Language,
			&i.CustomFields,
			&i.OptInStatus,
			&i.OptedInAt,
			&i.OptedOutAt,
			&i.Blocked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.name, count(ct.contact_id) AS contacts
FROM tags t LEFT JOIN contact_tags ct ON ct.tag_id = t.id
GROUP BY t.id, t.name
ORDER BY t.name
`

type ListTagsRow struct {
	ID       uuid.UUID
	Name     string
	Contacts int64
}

func (q *Queries) ListTags(ctx context.Context) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsRow
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Contacts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeContactTag = `-- name: RemoveContactTag :exec
DELETE FROM contact_tags ct USING tags t
WHERE ct.tag_id = t.id AND ct.contact_id = $1 AND t.name = $2::citext
`

type RemoveContactTagParams struct {
	ContactID uuid.UUID
	Name      string
}

func (q *Queries) RemoveContactTag(ctx context.Context, arg RemoveContactTagParams) error {
	_, err := q.db.Exec(ctx, removeContactTag, arg.ContactID, arg.Name)
	return err
}

const setContactConsent = `-- name: SetContactConsent :one
UPDATE contacts
SET opt_in_status = $1,
    opted_in_at = CASE WHEN $1 = 'opted_in'::opt_in_status THEN $2::timestamptz ELSE opted_in_at END,
    opted_out_at = CASE WHEN $1 = 'opted_out'::opt_in_status THEN $2::timestamptz ELSE opted_out_at END,
    updated_at = now()
WHERE id = $3
RETURNING id, tenant_id, wa_id, name, profile_name, language, custom_fields, opt_in_status, opted_in_at, opted_out_at, blocked, created_at, updated_at
`

type SetContactConsentParams struct {
	Status OptInStatus
	At     time.Time
	ID     uuid.UUID
}

func (q *Queries) SetContactConsent(ctx context.Context, arg SetContactConsentParams) (Contact, error) {
	row := q.db.QueryRow(ctx, setContactConsent, arg.Status, arg.At, arg.ID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WaID,
		&i.Name,
		&i.ProfileName,
		&i.Language,
		&i.CustomFields,
		&i.OptInStatus,
		&i.OptedInAt,
		&i.OptedOutAt,
		&i.Blocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts
SET name = CASE WHEN $1::bool THEN $2 ELSE name END,
    language = CASE WHEN $3::bool THEN $4 ELSE language END,
    custom_fields = jsonb_strip_nulls(custom_fields || coalesce($5::jsonb, '{}')),
    blocked = coalesce($6, blocked),
    updated_at = now()
WHERE id = $7
RETURNING id, tenant_id, wa_id, name, profile_name, language, custom_fields, opt_in_status, opted_in_at, opted_out_at, blocked, created_at, updated_at
`

type UpdateContactParams struct {
	SetName      bool
	Name         *string
	SetLanguage  bool
	Language     *string
	CustomFields []byte
	Blocked      *bool
	ID           uuid.UUID
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.SetName,
		arg.Name,
		arg.SetLanguage,
		arg.Language,
		arg.CustomFields,
		arg.Blocked,
		arg.ID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WaID,
		&i.Name,
		&i.ProfileName,
		&i.Language,
		&i.CustomFields,
		&i.OptInStatus,
		&i.OptedInAt,
		&i.OptedOutAt,
		&i.Blocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertContact = `-- name: UpsertContact :one
INSERT INTO contacts (id, tenant_id, wa_id, name, language, custom_fields)
VALUES ($1, $2, $3, $4, $5, jsonb_strip_nulls(coalesce($6::jsonb, '{}')))
ON CONFLICT (tenant_id, wa_id) DO UPDATE
SET name = coalesce(EXCLUDED.name, contacts.name),
    language = coalesce(EXCLUDED.language, contacts.language),
    custom_fields = jsonb_strip_nulls(contacts.custom_fields || coalesce($6::jsonb, '{}')),
    updated_at = now()
RETURNING id, tenant_id, wa_id, name, profile_name, language, custom_fields, opt_in_status, opted_in_at, opted_out_at, blocked, created_at, updated_at, (xmax = 0) AS inserted
`

type UpsertContactParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	WaID         string
	Name         *string
	Language     *string
	CustomFields []byte
}

type UpsertContactRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	WaID         string
	Name         *string
	ProfileName  *string
	Language     *string
	CustomFields []byte
	OptInStatus  OptInStatus
	OptedInAt    *time.Time
	OptedOutAt   *time.Time
	Blocked      bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Inserted     bool
}

// Creates a contact or updates the given fields of the one with this number. custom_fields are
// merged; a null value removes a field.
func (q *Queries) UpsertContact(ctx context.Context, arg UpsertContactParams) (UpsertContactRow, error) {
	row := q.db.QueryRow(ctx, upsertContact,
		arg.ID,
		arg.TenantID,
		arg.WaID,
		arg.Name,
		arg.Language,
		arg.CustomFields,
	)
	var i UpsertContactRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WaID,
		&i.Name,
		&i.ProfileName,
		&i.Language,
		&i.CustomFields,
		&i.OptInStatus,
		&i.OptedInAt,
		&i.OptedOutAt,
		&i.Blocked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Inserted,
	)
	return i, err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (tenant_id, name) VALUES ($1, $2)
ON CONFLICT (tenant_id, name) DO UPDATE SET name = tags.name
RETURNING id
`

type UpsertTagParams struct {
	TenantID uuid.UUID
	Name     string
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertTag, arg.TenantID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
