// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deletion.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const getDeletionRequestByCode = `-- name: GetDeletionRequestByCode :one
SELECT id, confirmation_code, meta_user_id, status, requested_at, completed_at FROM data_deletion_requests WHERE confirmation_code = $1
`

func (q *Queries) GetDeletionRequestByCode(ctx context.Context, confirmationCode string) (DataDeletionRequest, error) {
	row := q.db.QueryRow(ctx, getDeletionRequestByCode, confirmationCode)
	var i DataDeletionRequest
	err := row.Scan(
		&i.ID,
		&i.ConfirmationCode,
		&i.MetaUserID,
		&i.Status,
		&i.RequestedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertDeletionRequest = `-- name: InsertDeletionRequest :one
INSERT INTO data_deletion_requests (confirmation_code, meta_user_id) VALUES ($1, $2)
RETURNING id, confirmation_code, meta_user_id, status, requested_at, completed_at
`

type InsertDeletionRequestParams struct {
	ConfirmationCode string
	MetaUserID       string
}

func (q *Queries) InsertDeletionRequest(ctx context.Context, arg InsertDeletionRequestParams) (DataDeletionRequest, error) {
	row := q.db.QueryRow(ctx, insertDeletionRequest, arg.ConfirmationCode, arg.MetaUserID)
	var i DataDeletionRequest
	err := row.Scan(
		&i.ID,
		&i.ConfirmationCode,
		&i.MetaUserID,
		&i.Status,
		&i.RequestedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listDeletionRequests = `-- name: ListDeletionRequests :many
SELECT id, confirmation_code, meta_user_id, status, requested_at, completed_at FROM data_deletion_requests ORDER BY requested_at DESC LIMIT 100
`

func (q *Queries) ListDeletionRequests(ctx context.Context) ([]DataDeletionRequest, error) {
	rows, err := q.db.Query(ctx, listDeletionRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DataDeletionRequest
	for rows.Next() {
		var i DataDeletionRequest
		if err := rows.Scan(
			&i.ID,
			&i.ConfirmationCode,
			&i.MetaUserID,
			&i.Status,
			&i.RequestedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeletionRequestStatus = `-- name: SetDeletionRequestStatus :one
UPDATE data_deletion_requests
SET status = $1::text, completed_at = CASE WHEN $1::text = 'completed' THEN now() ELSE NULL END
WHERE id = $2
RETURNING id, confirmation_code, meta_user_id, status, requested_at, completed_at
`

type SetDeletionRequestStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) SetDeletionRequestStatus(ctx context.Context, arg SetDeletionRequestStatusParams) (DataDeletionRequest, error) {
	row := q.db.QueryRow(ctx, setDeletionRequestStatus, arg.Status, arg.ID)
	var i DataDeletionRequest
	err := row.Scan(
		&i.ID,
		&i.ConfirmationCode,
		&i.MetaUserID,
		&i.Status,
		&i.RequestedAt,
		&i.CompletedAt,
	)
	return i, err
}
