// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devportal.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const aPIUsageSince = `-- name: APIUsageSince :many
SELECT api_key_id, sum(calls)::int AS calls, sum(errors)::int AS errors
FROM api_usage_hourly
WHERE hour >= date_trunc('hour', $1::timestamptz)
GROUP BY api_key_id
`

type APIUsageSinceRow struct {
	ApiKeyID uuid.UUID
	Calls    int32
	Errors   int32
}

// Calls and errors per key since a time (whole hours).
func (q *Queries) APIUsageSince(ctx context.Context, since time.Time) ([]APIUsageSinceRow, error) {
	rows, err := q.db.Query(ctx, aPIUsageSince, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APIUsageSinceRow
	for rows.Next() {
		var i APIUsageSinceRow
		if err := rows.Scan(&i.ApiKeyID, &i.Calls, &i.Errors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAPICall = `-- name: CountAPICall :exec
INSERT INTO api_usage_hourly (tenant_id, api_key_id, hour, calls, errors)
VALUES ($1, $2, date_trunc('hour', now()), 1, CASE WHEN $3::bool THEN 1 ELSE 0 END)
ON CONFLICT (api_key_id, hour) DO UPDATE
SET calls = api_usage_hourly.calls + 1, errors = api_usage_hourly.errors + EXCLUDED.errors
`

type CountAPICallParams struct {
	TenantID uuid.UUID
	ApiKeyID uuid.UUID
	Failed   bool
}

func (q *Queries) CountAPICall(ctx context.Context, arg CountAPICallParams) error {
	_, err := q.db.Exec(ctx, countAPICall, arg.TenantID, arg.ApiKeyID, arg.Failed)
	return err
}

const insertAPIKey = `-- name: InsertAPIKey :one
INSERT INTO api_keys (id, tenant_id, name, prefix, key_hash, mode, phone_number_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, name, prefix, key_hash, mode, phone_number_id, created_by, last_used_at, revoked_at, created_at
`

type InsertAPIKeyParams struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	Name          string
	Prefix        string
	KeyHash       []byte
	Mode          ApiKeyMode
	PhoneNumberID *uuid.UUID
	CreatedBy     *uuid.UUID
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, insertAPIKey,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Prefix,
		arg.KeyHash,
		arg.Mode,
		arg.PhoneNumberID,
		arg.CreatedBy,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Mode,
		&i.PhoneNumberID,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, tenant_id, name, prefix, key_hash, mode, phone_number_id, created_by, last_used_at, revoked_at, created_at FROM api_keys ORDER BY revoked_at IS NOT NULL, created_at DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Prefix,
			&i.KeyHash,
			&i.Mode,
			&i.PhoneNumberID,
			&i.CreatedBy,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

func (q *Queries) TouchAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
