// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flows.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteFlow = `-- name: DeleteFlow :execrows
DELETE FROM flows WHERE id = $1
`

func (q *Queries) DeleteFlow(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFlow, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFlow = `-- name: GetFlow :one
SELECT id, tenant_id, whatsapp_account_id, meta_flow_id, name, categories, status, flow_json, validation_errors, preview_url, preview_expires_at, created_by, created_at, updated_at, published_at FROM flows WHERE id = $1
`

func (q *Queries) GetFlow(ctx context.Context, id uuid.UUID) (Flow, error) {
	row := q.db.QueryRow(ctx, getFlow, id)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WhatsappAccountID,
		&i.MetaFlowID,
		&i.Name,
		&i.Categories,
		&i.Status,
		&i.FlowJson,
		&i.ValidationErrors,
		&i.PreviewUrl,
		&i.PreviewExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getFlowByMetaID = `-- name: GetFlowByMetaID :one
SELECT id, tenant_id, whatsapp_account_id, meta_flow_id, name, categories, status, flow_json, validation_errors, preview_url, preview_expires_at, created_by, created_at, updated_at, published_at FROM flows WHERE meta_flow_id = $1
`

func (q *Queries) GetFlowByMetaID(ctx context.Context, metaFlowID string) (Flow, error) {
	row := q.db.QueryRow(ctx, getFlowByMetaID, metaFlowID)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WhatsappAccountID,
		&i.MetaFlowID,
		&i.Name,
		&i.Categories,
		&i.Status,
		&i.FlowJson,
		&i.ValidationErrors,
		&i.PreviewUrl,
		&i.PreviewExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getFlowSubmissionView = `-- name: GetFlowSubmissionView :one
SELECT s.id, s.tenant_id, s.flow_id, s.meta_flow_id, s.contact_id, s.conversation_id, s.message_id, s.flow_token, s.response, s.created_at, c.wa_id AS contact_wa_id, coalesce(c.name, c.profile_name) AS contact_name, f.name AS flow_name
FROM flow_submissions s
JOIN contacts c ON c.id = s.contact_id
LEFT JOIN flows f ON f.id = s.flow_id
WHERE s.id = $1
`

type GetFlowSubmissionViewRow struct {
	FlowSubmission FlowSubmission
	ContactWaID    string
	ContactName    *string
	FlowName       *string
}

func (q *Queries) GetFlowSubmissionView(ctx context.Context, id uuid.UUID) (GetFlowSubmissionViewRow, error) {
	row := q.db.QueryRow(ctx, getFlowSubmissionView, id)
	var i GetFlowSubmissionViewRow
	err := row.Scan(
		&i.FlowSubmission.ID,
		&i.FlowSubmission.TenantID,
		&i.FlowSubmission.FlowID,
		&i.FlowSubmission.MetaFlowID,
		&i.FlowSubmission.ContactID,
		&i.FlowSubmission.ConversationID,
		&i.FlowSubmission.MessageID,
		&i.FlowSubmission.FlowToken,
		&i.FlowSubmission.Response,
		&i.FlowSubmission.CreatedAt,
		&i.ContactWaID,
		&i.ContactName,
		&i.FlowName,
	)
	return i, err
}

const insertFlow = `-- name: InsertFlow :one
INSERT INTO flows (id, tenant_id, whatsapp_account_id, meta_flow_id, name, categories, status, flow_json,
                   validation_errors, preview_url, preview_expires_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, tenant_id, whatsapp_account_id, meta_flow_id, name, categories, status, flow_json, validation_errors, preview_url, preview_expires_at, created_by, created_at, updated_at, published_at
`

type InsertFlowParams struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	WhatsappAccountID uuid.UUID
	MetaFlowID        string
	Name              string
	Categories        []string
	Status            string
	FlowJson          []byte
	ValidationErrors  []byte
	PreviewUrl        *string
	PreviewExpiresAt  *time.Time
	CreatedBy         *uuid.UUID
}

func (q *Queries) InsertFlow(ctx context.Context, arg InsertFlowParams) (Flow, error) {
	row := q.db.QueryRow(ctx, insertFlow,
		arg.ID,
		arg.TenantID,
		arg.WhatsappAccountID,
		arg.MetaFlowID,
		arg.Name,
		arg.Categories,
		arg.Status,
		arg.FlowJson,
		arg.ValidationErrors,
		arg.PreviewUrl,
		arg.PreviewExpiresAt,
		arg.CreatedBy,
	)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WhatsappAccountID,
		&i.MetaFlowID,
		&i.Name,
		&i.Categories,
		&i.Status,
		&i.FlowJson,
		&i.ValidationErrors,
		&i.PreviewUrl,
		&i.PreviewExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const insertFlowSubmission = `-- name: InsertFlowSubmission :one
INSERT INTO flow_submissions (id, tenant_id, flow_id, meta_flow_id, contact_id, conversation_id, message_id, flow_token, response)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (message_id) DO NOTHING
RETURNING id, tenant_id, flow_id, meta_flow_id, contact_id, conversation_id, message_id, flow_token, response, created_at
`

type InsertFlowSubmissionParams struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	FlowID         *uuid.UUID
	MetaFlowID     *string
	ContactID      uuid.UUID
	ConversationID uuid.UUID
	MessageID      uuid.UUID
	FlowToken      *string
	Response       []byte
}

func (q *Queries) InsertFlowSubmission(ctx context.Context, arg InsertFlowSubmissionParams) (FlowSubmission, error) {
	row := q.db.QueryRow(ctx, insertFlowSubmission,
		arg.ID,
		arg.TenantID,
		arg.FlowID,
		arg.MetaFlowID,
		arg.ContactID,
		arg.ConversationID,
		arg.MessageID,
		arg.FlowToken,
		arg.Response,
	)
	var i FlowSubmission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FlowID,
		&i.MetaFlowID,
		&i.ContactID,
		&i.ConversationID,
		&i.MessageID,
		&i.FlowToken,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const listFlowSubmissions = `-- name: ListFlowSubmissions :many
SELECT s.id, s.tenant_id, s.flow_id, s.meta_flow_id, s.contact_id, s.conversation_id, s.message_id, s.flow_token, s.response, s.created_at, c.wa_id AS contact_wa_id, coalesce(c.name, c.profile_name) AS contact_name, f.name AS flow_name
FROM flow_submissions s
JOIN contacts c ON c.id = s.contact_id
LEFT JOIN flows f ON f.id = s.flow_id
WHERE ($1::uuid IS NULL OR s.flow_id = $1)
  AND ($2::uuid IS NULL OR s.contact_id = $2)
  AND ($3::timestamptz IS NULL OR (s.created_at, s.id) < ($3, $4::uuid))
ORDER BY s.created_at DESC, s.id DESC
LIMIT $5
`

type ListFlowSubmissionsParams struct {
	FlowID    *uuid.UUID
	ContactID *uuid.UUID
	BeforeAt  *time.Time
	BeforeID  *uuid.UUID
	Lim       int32
}

type ListFlowSubmissionsRow struct {
	FlowSubmission FlowSubmission
	ContactWaID    string
	ContactName    *string
	FlowName       *string
}

func (q *Queries) ListFlowSubmissions(ctx context.Context, arg ListFlowSubmissionsParams) ([]ListFlowSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, listFlowSubmissions,
		arg.FlowID,
		arg.ContactID,
		arg.BeforeAt,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlowSubmissionsRow
	for rows.Next() {
		var i ListFlowSubmissionsRow
		if err := rows.Scan(
			&i.FlowSubmission.ID,
			&i.FlowSubmission.TenantID,
			&i.FlowSubmission.FlowID,
			&i.FlowSubmission.MetaFlowID,
			&i.FlowSubmission.ContactID,
			&i.FlowSubmission.ConversationID,
			&i.FlowSubmission.MessageID,
			&i.FlowSubmission.FlowToken,
			&i.FlowSubmission.Response,
			&i.FlowSubmission.CreatedAt,
			&i.ContactWaID,
			&i.ContactName,
			&i.FlowName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlows = `-- name: ListFlows :many
SELECT id, tenant_id, whatsapp_account_id, meta_flow_id, name, categories, status, flow_json, validation_errors, preview_url, preview_expires_at, created_by, created_at, updated_at, published_at FROM flows ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListFlows(ctx context.Context) ([]Flow, error) {
	rows, err := q.db.Query(ctx, listFlows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flow
	for rows.Next() {
		var i Flow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WhatsappAccountID,
			&i.MetaFlowID,
			&i.Name,
			&i.Categories,
			&i.Status,
			&i.FlowJson,
			&i.ValidationErrors,
			&i.PreviewUrl,
			&i.PreviewExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlowContent = `-- name: UpdateFlowContent :one
UPDATE flows
SET name = $1, categories = $2, flow_json = $3, validation_errors = $4,
    preview_url = $5, preview_expires_at = $6, updated_at = now()
WHERE id = $7
RETURNING id, tenant_id, whatsapp_account_id, meta_flow_id, name, categories, status, flow_json, validation_errors, preview_url, preview_expires_at, created_by, created_at, updated_at, published_at
`

type UpdateFlowContentParams struct {
	Name             string
	Categories       []string
	FlowJson         []byte
	ValidationErrors []byte
	PreviewUrl       *string
	PreviewExpiresAt *time.Time
	ID               uuid.UUID
}

func (q *Queries) UpdateFlowContent(ctx context.Context, arg UpdateFlowContentParams) (Flow, error) {
	row := q.db.QueryRow(ctx, updateFlowContent,
		arg.Name,
		arg.Categories,
		arg.FlowJson,
		arg.ValidationErrors,
		arg.PreviewUrl,
		arg.PreviewExpiresAt,
		arg.ID,
	)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WhatsappAccountID,
		&i.MetaFlowID,
		&i.Name,
		&i.Categories,
		&i.Status,
		&i.FlowJson,
		&i.ValidationErrors,
		&i.PreviewUrl,
		&i.PreviewExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const updateFlowStatus = `-- name: UpdateFlowStatus :one
UPDATE flows
SET status = $1,
    published_at = CASE WHEN $1::text = 'published' THEN coalesce(published_at, now()) ELSE published_at END,
    validation_errors = coalesce($2, validation_errors),
    preview_url = coalesce($3, preview_url),
    preview_expires_at = coalesce($4, preview_expires_at),
    updated_at = now()
WHERE id = $5
RETURNING id, tenant_id, whatsapp_account_id, meta_flow_id, name, categories, status, flow_json, validation_errors, preview_url, preview_expires_at, created_by, created_at, updated_at, published_at
`

type UpdateFlowStatusParams struct {
	Status           string
	ValidationErrors []byte
	PreviewUrl       *string
	PreviewExpiresAt *time.Time
	ID               uuid.UUID
}

func (q *Queries) UpdateFlowStatus(ctx context.Context, arg UpdateFlowStatusParams) (Flow, error) {
	row := q.db.QueryRow(ctx, updateFlowStatus,
		arg.Status,
		arg.ValidationErrors,
		arg.PreviewUrl,
		arg.PreviewExpiresAt,
		arg.ID,
	)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WhatsappAccountID,
		&i.MetaFlowID,
		&i.Name,
		&i.Categories,
		&i.Status,
		&i.FlowJson,
		&i.ValidationErrors,
		&i.PreviewUrl,
		&i.PreviewExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}
