// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbox.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteQuickReply = `-- name: DeleteQuickReply :execrows
DELETE FROM quick_replies WHERE id = $1
`

func (q *Queries) DeleteQuickReply(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteQuickReply, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConversationView = `-- name: GetConversationView :one
SELECT cv.id, cv.tenant_id, cv.phone_number_id, cv.contact_id, cv.status, cv.assignee_user_id, cv.last_inbound_at, cv.last_message_at, cv.last_message_preview, cv.unread_count, cv.created_at, cv.updated_at, ct.id, ct.tenant_id, ct.wa_id, ct.name, ct.profile_name, ct.language, ct.custom_fields, ct.opt_in_status, ct.opted_in_at, ct.opted_out_at, ct.blocked, ct.created_at, ct.updated_at
FROM conversations cv JOIN contacts ct ON ct.id = cv.contact_id
WHERE cv.id = $1
`

type GetConversationViewRow struct {
	Conversation Conversation
	Contact      Contact
}

func (q *Queries) GetConversationView(ctx context.Context, id uuid.UUID) (GetConversationViewRow, error) {
	row := q.db.QueryRow(ctx, getConversationView, id)
	var i GetConversationViewRow
	err := row.Scan(
		&i.Conversation.ID,
		&i.Conversation.TenantID,
		&i.Conversation.PhoneNumberID,
		&i.Conversation.ContactID,
		&i.Conversation.Status,
		&i.Conversation.AssigneeUserID,
		&i.Conversation.LastInboundAt,
		&i.Conversation.LastMessageAt,
		&i.Conversation.LastMessagePreview,
		&i.Conversation.UnreadCount,
		&i.Conversation.CreatedAt,
		&i.Conversation.UpdatedAt,
		&i.Contact.ID,
		&i.Contact.TenantID,
		&i.Contact.WaID,
		&i.Contact.Name,
		&i.Contact.ProfileName,
		&i.Contact.Language,
		&i.Contact.CustomFields,
		&i.Contact.OptInStatus,
		&i.Contact.OptedInAt,
		&i.Contact.OptedOutAt,
		&i.Contact.Blocked,
		&i.Contact.CreatedAt,
		&i.Contact.UpdatedAt,
	)
	return i, err
}

const insertNote = `-- name: InsertNote :one
INSERT INTO conversation_notes (id, tenant_id, conversation_id, author_user_id, body)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, conversation_id, author_user_id, body, created_at
`

type InsertNoteParams struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ConversationID uuid.UUID
	AuthorUserID   uuid.UUID
	Body           string
}

func (q *Queries) InsertNote(ctx context.Context, arg InsertNoteParams) (ConversationNote, error) {
	row := q.db.QueryRow(ctx, insertNote,
		arg.ID,
		arg.TenantID,
		arg.ConversationID,
		arg.AuthorUserID,
		arg.Body,
	)
	var i ConversationNote
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ConversationID,
		&i.AuthorUserID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const insertQuickReply = `-- name: InsertQuickReply :one
INSERT INTO quick_replies (id, tenant_id, shortcut, body, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, shortcut, body, created_by, created_at
`

type InsertQuickReplyParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Shortcut  string
	Body      string
	CreatedBy *uuid.UUID
}

func (q *Queries) InsertQuickReply(ctx context.Context, arg InsertQuickReplyParams) (QuickReply, error) {
	row := q.db.QueryRow(ctx, insertQuickReply,
		arg.ID,
		arg.TenantID,
		arg.Shortcut,
		arg.Body,
		arg.CreatedBy,
	)
	var i QuickReply
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Shortcut,
		&i.Body,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const isMember = `-- name: IsMember :one
SELECT EXISTS (SELECT 1 FROM memberships WHERE user_id = $1)::boolean
`

func (q *Queries) IsMember(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isMember, userID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listContactTags = `-- name: ListContactTags :many
SELECT ct.contact_id, t.name FROM contact_tags ct JOIN tags t ON t.id = ct.tag_id
WHERE ct.contact_id = ANY($1::uuid[])
ORDER BY t.name
`

type ListContactTagsRow struct {
	ContactID uuid.UUID
	Name      string
}

func (q *Queries) ListContactTags(ctx context.Context, contactIds []uuid.UUID) ([]ListContactTagsRow, error) {
	rows, err := q.db.Query(ctx, listContactTags, contactIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactTagsRow
	for rows.Next() {
		var i ListContactTagsRow
		if err := rows.Scan(&i.ContactID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationMessages = `-- name: ListConversationMessages :many
SELECT id, tenant_id, conversation_id, phone_number_id, contact_id, direction, origin, wamid, type, content, media_id, template_id, reply_to_wamid, status, error_code, error_title, sent_by_user_id, api_key_id, campaign_id, idempotency_key, pricing_category, pricing_billable, recipient_country, meta_timestamp, status_updated_at, created_at FROM messages
WHERE conversation_id = $1 AND ($2::uuid IS NULL OR id < $2)
ORDER BY id DESC
LIMIT $3
`

type ListConversationMessagesParams struct {
	ConversationID uuid.UUID
	Before         *uuid.UUID
	Lim            int32
}

func (q *Queries) ListConversationMessages(ctx context.Context, arg ListConversationMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listConversationMessages, arg.ConversationID, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ConversationID,
			&i.PhoneNumberID,
			&i.ContactID,
			&i.Direction,
			&i.Origin,
			&i.Wamid,
			&i.Type,
			&i.Content,
			&i.MediaID,
			&i.TemplateID,
			&i.ReplyToWamid,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorTitle,
			&i.SentByUserID,
			&i.ApiKeyID,
			&i.CampaignID,
			&i.IdempotencyKey,
			&i.PricingCategory,
			&i.PricingBillable,
			&i.RecipientCountry,
			&i.MetaTimestamp,
			&i.StatusUpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversations = `-- name: ListConversations :many
SELECT cv.id, cv.tenant_id, cv.phone_number_id, cv.contact_id, cv.status, cv.assignee_user_id, cv.last_inbound_at, cv.last_message_at, cv.last_message_preview, cv.unread_count, cv.created_at, cv.updated_at, ct.id, ct.tenant_id, ct.wa_id, ct.name, ct.profile_name, ct.language, ct.custom_fields, ct.opt_in_status, ct.opted_in_at, ct.opted_out_at, ct.blocked, ct.created_at, ct.updated_at, coalesce(cv.last_message_at, cv.created_at)::timestamptz AS activity_at
FROM conversations cv JOIN contacts ct ON ct.id = cv.contact_id
WHERE ($1::uuid IS NULL OR cv.phone_number_id = $1)
  AND ($2::conversation_status IS NULL OR cv.status = $2)
  AND ($3::uuid IS NULL OR cv.assignee_user_id = $3)
  AND (NOT $4::boolean OR cv.assignee_user_id IS NULL)
  AND ($5::boolean IS NULL
       OR coalesce(cv.last_inbound_at > now() - interval '24 hours', false) = $5)
  AND ($6::text IS NULL
       OR ct.wa_id LIKE '%' || $6 || '%'
       OR ct.name ILIKE '%' || $6 || '%'
       OR ct.profile_name ILIKE '%' || $6 || '%')
  AND ($7::timestamptz IS NULL
       OR (coalesce(cv.last_message_at, cv.created_at), cv.id) < ($7, $8::uuid))
ORDER BY coalesce(cv.last_message_at, cv.created_at) DESC, cv.id DESC
LIMIT $9
`

type ListConversationsParams struct {
	PhoneNumberID *uuid.UUID
	Status        *ConversationStatus
	AssigneeID    *uuid.UUID
	Unassigned    bool
	WindowOpen    *bool
	Search        *string
	BeforeAt      *time.Time
	BeforeID      *uuid.UUID
	Lim           int32
}

type ListConversationsRow struct {
	Conversation Conversation
	Contact      Contact
	ActivityAt   time.Time
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]ListConversationsRow, error) {
	rows, err := q.db.Query(ctx, listConversations,
		arg.PhoneNumberID,
		arg.Status,
		arg.AssigneeID,
		arg.Unassigned,
		arg.WindowOpen,
		arg.Search,
		arg.BeforeAt,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsRow
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.Conversation.ID,
			&i.Conversation.TenantID,
			&i.Conversation.PhoneNumberID,
			&i.Conversation.ContactID,
			&i.Conversation.Status,
			&i.Conversation.AssigneeUserID,
			&i.Conversation.LastInboundAt,
			&i.Conversation.LastMessageAt,
			&i.Conversation.LastMessagePreview,
			&i.Conversation.UnreadCount,
			&i.Conversation.CreatedAt,
			&i.Conversation.UpdatedAt,
			&i.Contact.ID,
			&i.Contact.TenantID,
			&i.Contact.WaID,
			&i.Contact.Name,
			&i.Contact.ProfileName,
			&i.Contact.Language,
			&i.Contact.CustomFields,
			&i.Contact.OptInStatus,
			&i.Contact.OptedInAt,
			&i.Contact.OptedOutAt,
			&i.Contact.Blocked,
			&i.Contact.CreatedAt,
			&i.Contact.UpdatedAt,
			&i.ActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT u.id, u.name, u.email, m.role, m.created_at
FROM memberships m JOIN users u ON u.id = m.user_id
ORDER BY u.name
`

type ListMembersRow struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Role      MemberRole
	CreatedAt time.Time
}

func (q *Queries) ListMembers(ctx context.Context) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotes = `-- name: ListNotes :many
SELECT n.id, n.body, n.created_at, n.author_user_id, u.name AS author_name
FROM conversation_notes n JOIN users u ON u.id = n.author_user_id
WHERE n.conversation_id = $1
ORDER BY n.created_at
`

type ListNotesRow struct {
	ID           uuid.UUID
	Body         string
	CreatedAt    time.Time
	AuthorUserID uuid.UUID
	AuthorName   string
}

func (q *Queries) ListNotes(ctx context.Context, conversationID uuid.UUID) ([]ListNotesRow, error) {
	rows, err := q.db.Query(ctx, listNotes, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotesRow
	for rows.Next() {
		var i ListNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorUserID,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuickReplies = `-- name: ListQuickReplies :many
SELECT id, tenant_id, shortcut, body, created_by, created_at FROM quick_replies ORDER BY shortcut
`

func (q *Queries) ListQuickReplies(ctx context.Context) ([]QuickReply, error) {
	rows, err := q.db.Query(ctx, listQuickReplies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuickReply
	for rows.Next() {
		var i QuickReply
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Shortcut,
			&i.Body,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversation = `-- name: UpdateConversation :exec
UPDATE conversations
SET status = coalesce($1, status),
    assignee_user_id = CASE WHEN $2::boolean THEN $3 ELSE assignee_user_id END,
    updated_at = now()
WHERE id = $4
`

type UpdateConversationParams struct {
	Status         *ConversationStatus
	SetAssignee    bool
	AssigneeUserID *uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) error {
	_, err := q.db.Exec(ctx, updateConversation,
		arg.Status,
		arg.SetAssignee,
		arg.AssigneeUserID,
		arg.ID,
	)
	return err
}
