// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoices.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getBillingProfile = `-- name: GetBillingProfile :one
SELECT tenant_id, legal_name, gstin, state_code, address, updated_at FROM billing_profiles LIMIT 1
`

func (q *Queries) GetBillingProfile(ctx context.Context) (BillingProfile, error) {
	row := q.db.QueryRow(ctx, getBillingProfile)
	var i BillingProfile
	err := row.Scan(
		&i.TenantID,
		&i.LegalName,
		&i.Gstin,
		&i.StateCode,
		&i.Address,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, tenant_id, number, razorpay_payment_id, description, period_start, period_end, sac, total_minor, taxable_minor, gst_rate_bp, cgst_minor, sgst_minor, igst_minor, place_of_supply, seller, buyer, issued_at FROM invoices WHERE id = $1
`

func (q *Queries) GetInvoice(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Number,
		&i.RazorpayPaymentID,
		&i.Description,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Sac,
		&i.TotalMinor,
		&i.TaxableMinor,
		&i.GstRateBp,
		&i.CgstMinor,
		&i.SgstMinor,
		&i.IgstMinor,
		&i.PlaceOfSupply,
		&i.Seller,
		&i.Buyer,
		&i.IssuedAt,
	)
	return i, err
}

const insertInvoice = `-- name: InsertInvoice :execrows
INSERT INTO invoices (id, tenant_id, number, razorpay_payment_id, description, period_start, period_end, sac,
                      total_minor, taxable_minor, gst_rate_bp, cgst_minor, sgst_minor, igst_minor,
                      place_of_supply, seller, buyer, issued_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12, $13, $14,
        $15, $16, $17, $18)
ON CONFLICT (razorpay_payment_id) DO NOTHING
`

type InsertInvoiceParams struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	Number            string
	RazorpayPaymentID string
	Description       string
	PeriodStart       *time.Time
	PeriodEnd         *time.Time
	Sac               *string
	TotalMinor        int64
	TaxableMinor      int64
	GstRateBp         int32
	CgstMinor         int64
	SgstMinor         int64
	IgstMinor         int64
	PlaceOfSupply     string
	Seller            []byte
	Buyer             []byte
	IssuedAt          time.Time
}

func (q *Queries) InsertInvoice(ctx context.Context, arg InsertInvoiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertInvoice,
		arg.ID,
		arg.TenantID,
		arg.Number,
		arg.RazorpayPaymentID,
		arg.Description,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Sac,
		arg.TotalMinor,
		arg.TaxableMinor,
		arg.GstRateBp,
		arg.CgstMinor,
		arg.SgstMinor,
		arg.IgstMinor,
		arg.PlaceOfSupply,
		arg.Seller,
		arg.Buyer,
		arg.IssuedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, tenant_id, number, razorpay_payment_id, description, period_start, period_end, sac, total_minor, taxable_minor, gst_rate_bp, cgst_minor, sgst_minor, igst_minor, place_of_supply, seller, buyer, issued_at FROM invoices ORDER BY issued_at DESC, number DESC
`

func (q *Queries) ListInvoices(ctx context.Context) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Number,
			&i.RazorpayPaymentID,
			&i.Description,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Sac,
			&i.TotalMinor,
			&i.TaxableMinor,
			&i.GstRateBp,
			&i.CgstMinor,
			&i.SgstMinor,
			&i.IgstMinor,
			&i.PlaceOfSupply,
			&i.Seller,
			&i.Buyer,
			&i.IssuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextInvoiceNumber = `-- name: NextInvoiceNumber :one
INSERT INTO invoice_counters (fy, last) VALUES ($1, 1)
ON CONFLICT (fy) DO UPDATE SET last = invoice_counters.last + 1
RETURNING last
`

// Locks the year's counter row until the invoice commits, so numbers stay gapless.
func (q *Queries) NextInvoiceNumber(ctx context.Context, fy string) (int32, error) {
	row := q.db.QueryRow(ctx, nextInvoiceNumber, fy)
	var last int32
	err := row.Scan(&last)
	return last, err
}

const paymentInvoiced = `-- name: PaymentInvoiced :one
SELECT EXISTS (SELECT 1 FROM invoices WHERE razorpay_payment_id = $1)::boolean
`

func (q *Queries) PaymentInvoiced(ctx context.Context, razorpayPaymentID string) (bool, error) {
	row := q.db.QueryRow(ctx, paymentInvoiced, razorpayPaymentID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertBillingProfile = `-- name: UpsertBillingProfile :one
INSERT INTO billing_profiles (tenant_id, legal_name, gstin, state_code, address)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id) DO UPDATE
SET legal_name = EXCLUDED.legal_name, gstin = EXCLUDED.gstin, state_code = EXCLUDED.state_code,
    address = EXCLUDED.address, updated_at = now()
RETURNING tenant_id, legal_name, gstin, state_code, address, updated_at
`

type UpsertBillingProfileParams struct {
	TenantID  uuid.UUID
	LegalName string
	Gstin     *string
	StateCode string
	Address   string
}

func (q *Queries) UpsertBillingProfile(ctx context.Context, arg UpsertBillingProfileParams) (BillingProfile, error) {
	row := q.db.QueryRow(ctx, upsertBillingProfile,
		arg.TenantID,
		arg.LegalName,
		arg.Gstin,
		arg.StateCode,
		arg.Address,
	)
	var i BillingProfile
	err := row.Scan(
		&i.TenantID,
		&i.LegalName,
		&i.Gstin,
		&i.StateCode,
		&i.Address,
		&i.UpdatedAt,
	)
	return i, err
}
