// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getMedia = `-- name: GetMedia :one
SELECT id, tenant_id, phone_number_id, storage_key, mime_type, size_bytes, sha256, filename, meta_media_id, meta_uploaded_at, created_at FROM media WHERE id = $1
`

func (q *Queries) GetMedia(ctx context.Context, id uuid.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getMedia, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneNumberID,
		&i.StorageKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Filename,
		&i.MetaMediaID,
		&i.MetaUploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageForMediaDownload = `-- name: GetMessageForMediaDownload :one
SELECT m.id, m.tenant_id, m.conversation_id, m.phone_number_id, m.contact_id, m.direction, m.origin, m.wamid, m.type, m.content, m.media_id, m.template_id, m.reply_to_wamid, m.status, m.error_code, m.error_title, m.sent_by_user_id, m.api_key_id, m.campaign_id, m.idempotency_key, m.pricing_category, m.pricing_billable, m.recipient_country, m.meta_timestamp, m.status_updated_at, m.created_at, m.bot_id, p.whatsapp_account_id
FROM messages m JOIN phone_numbers p ON p.id = m.phone_number_id
WHERE m.id = $1
`

type GetMessageForMediaDownloadRow struct {
	Message           Message
	WhatsappAccountID uuid.UUID
}

func (q *Queries) GetMessageForMediaDownload(ctx context.Context, id uuid.UUID) (GetMessageForMediaDownloadRow, error) {
	row := q.db.QueryRow(ctx, getMessageForMediaDownload, id)
	var i GetMessageForMediaDownloadRow
	err := row.Scan(
		&i.Message.ID,
		&i.Message.TenantID,
		&i.Message.ConversationID,
		&i.Message.PhoneNumberID,
		&i.Message.ContactID,
		&i.Message.Direction,
		&i.Message.Origin,
		&i.Message.Wamid,
		&i.Message.Type,
		&i.Message.Content,
		&i.Message.MediaID,
		&i.Message.TemplateID,
		&i.Message.ReplyToWamid,
		&i.Message.Status,
		&i.Message.ErrorCode,
		&i.Message.ErrorTitle,
		&i.Message.SentByUserID,
		&i.Message.ApiKeyID,
		&i.Message.CampaignID,
		&i.Message.IdempotencyKey,
		&i.Message.PricingCategory,
		&i.Message.PricingBillable,
		&i.Message.RecipientCountry,
		&i.Message.MetaTimestamp,
		&i.Message.StatusUpdatedAt,
		&i.Message.CreatedAt,
		&i.Message.BotID,
		&i.WhatsappAccountID,
	)
	return i, err
}

const insertMedia = `-- name: InsertMedia :one
INSERT INTO media (id, tenant_id, phone_number_id, storage_key, mime_type, size_bytes, sha256, filename, meta_media_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, phone_number_id, storage_key, mime_type, size_bytes, sha256, filename, meta_media_id, meta_uploaded_at, created_at
`

type InsertMediaParams struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	PhoneNumberID *uuid.UUID
	StorageKey    string
	MimeType      string
	SizeBytes     int64
	Sha256        []byte
	Filename      *string
	MetaMediaID   *string
}

func (q *Queries) InsertMedia(ctx context.Context, arg InsertMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, insertMedia,
		arg.ID,
		arg.TenantID,
		arg.PhoneNumberID,
		arg.StorageKey,
		arg.MimeType,
		arg.SizeBytes,
		arg.Sha256,
		arg.Filename,
		arg.MetaMediaID,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneNumberID,
		&i.StorageKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Filename,
		&i.MetaMediaID,
		&i.MetaUploadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markMediaUploaded = `-- name: MarkMediaUploaded :exec
UPDATE media SET phone_number_id = $2, meta_media_id = $3, meta_uploaded_at = $4 WHERE id = $1
`

type MarkMediaUploadedParams struct {
	ID             uuid.UUID
	PhoneNumberID  *uuid.UUID
	MetaMediaID    *string
	MetaUploadedAt *time.Time
}

// Records the ID Meta gave an upload from a phone number; Meta keeps it for 30 days.
func (q *Queries) MarkMediaUploaded(ctx context.Context, arg MarkMediaUploadedParams) error {
	_, err := q.db.Exec(ctx, markMediaUploaded,
		arg.ID,
		arg.PhoneNumberID,
		arg.MetaMediaID,
		arg.MetaUploadedAt,
	)
	return err
}

const setMessageMedia = `-- name: SetMessageMedia :exec
UPDATE messages SET media_id = $2 WHERE id = $1
`

type SetMessageMediaParams struct {
	ID      uuid.UUID
	MediaID *uuid.UUID
}

func (q *Queries) SetMessageMedia(ctx context.Context, arg SetMessageMediaParams) error {
	_, err := q.db.Exec(ctx, setMessageMedia, arg.ID, arg.MediaID)
	return err
}
