// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messaging.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one
INSERT INTO idempotency_records (tenant_id, key, request_hash)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, key) DO NOTHING
RETURNING key
`

type ClaimIdempotencyKeyParams struct {
	TenantID    uuid.UUID
	Key         string
	RequestHash []byte
}

// Returns the key when this request is the first to use it; no row means the key exists.
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyKey, arg.TenantID, arg.Key, arg.RequestHash)
	var key string
	err := row.Scan(&key)
	return key, err
}

const clearIdempotencyKey = `-- name: ClearIdempotencyKey :exec
UPDATE messages SET idempotency_key = NULL WHERE tenant_id = $1 AND idempotency_key = $2
`

type ClearIdempotencyKeyParams struct {
	TenantID       uuid.UUID
	IdempotencyKey *string
}

// Frees a key held by an earlier message whose 24 hours have passed.
func (q *Queries) ClearIdempotencyKey(ctx context.Context, arg ClearIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, clearIdempotencyKey, arg.TenantID, arg.IdempotencyKey)
	return err
}

const getIdempotencyRecordForUpdate = `-- name: GetIdempotencyRecordForUpdate :one
SELECT tenant_id, key, request_hash, response_status, response_body, created_at FROM idempotency_records WHERE tenant_id = $1 AND key = $2 FOR UPDATE
`

type GetIdempotencyRecordForUpdateParams struct {
	TenantID uuid.UUID
	Key      string
}

func (q *Queries) GetIdempotencyRecordForUpdate(ctx context.Context, arg GetIdempotencyRecordForUpdateParams) (IdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, getIdempotencyRecordForUpdate, arg.TenantID, arg.Key)
	var i IdempotencyRecord
	err := row.Scan(
		&i.TenantID,
		&i.Key,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, tenant_id, conversation_id, phone_number_id, contact_id, direction, origin, wamid, type, content, media_id, template_id, reply_to_wamid, status, error_code, error_title, sent_by_user_id, api_key_id, campaign_id, idempotency_key, pricing_category, pricing_billable, recipient_country, meta_timestamp, status_updated_at, created_at FROM messages WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ConversationID,
		&i.PhoneNumberID,
		&i.ContactID,
		&i.Direction,
		&i.Origin,
		&i.Wamid,
		&i.Type,
		&i.Content,
		&i.MediaID,
		&i.TemplateID,
		&i.ReplyToWamid,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorTitle,
		&i.SentByUserID,
		&i.ApiKeyID,
		&i.CampaignID,
		&i.IdempotencyKey,
		&i.PricingCategory,
		&i.PricingBillable,
		&i.RecipientCountry,
		&i.MetaTimestamp,
		&i.StatusUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageForSend = `-- name: GetMessageForSend :one
SELECT m.id, m.tenant_id, m.conversation_id, m.phone_number_id, m.contact_id, m.direction, m.origin, m.wamid, m.type, m.content, m.media_id, m.template_id, m.reply_to_wamid, m.status, m.error_code, m.error_title, m.sent_by_user_id, m.api_key_id, m.campaign_id, m.idempotency_key, m.pricing_category, m.pricing_billable, m.recipient_country, m.meta_timestamp, m.status_updated_at, m.created_at, c.wa_id AS contact_wa_id, p.phone_number_id AS meta_phone_number_id,
       p.whatsapp_account_id, p.status AS phone_status
FROM messages m
JOIN contacts c ON c.id = m.contact_id
JOIN phone_numbers p ON p.id = m.phone_number_id
WHERE m.id = $1
`

type GetMessageForSendRow struct {
	Message           Message
	ContactWaID       string
	MetaPhoneNumberID string
	WhatsappAccountID uuid.UUID
	PhoneStatus       ConnectionStatus
}

func (q *Queries) GetMessageForSend(ctx context.Context, id uuid.UUID) (GetMessageForSendRow, error) {
	row := q.db.QueryRow(ctx, getMessageForSend, id)
	var i GetMessageForSendRow
	err := row.Scan(
		&i.Message.ID,
		&i.Message.TenantID,
		&i.Message.ConversationID,
		&i.Message.PhoneNumberID,
		&i.Message.ContactID,
		&i.Message.Direction,
		&i.Message.Origin,
		&i.Message.Wamid,
		&i.Message.Type,
		&i.Message.Content,
		&i.Message.MediaID,
		&i.Message.TemplateID,
		&i.Message.ReplyToWamid,
		&i.Message.Status,
		&i.Message.ErrorCode,
		&i.Message.ErrorTitle,
		&i.Message.SentByUserID,
		&i.Message.ApiKeyID,
		&i.Message.CampaignID,
		&i.Message.IdempotencyKey,
		&i.Message.PricingCategory,
		&i.Message.PricingBillable,
		&i.Message.RecipientCountry,
		&i.Message.MetaTimestamp,
		&i.Message.StatusUpdatedAt,
		&i.Message.CreatedAt,
		&i.ContactWaID,
		&i.MetaPhoneNumberID,
		&i.WhatsappAccountID,
		&i.PhoneStatus,
	)
	return i, err
}

const getMessageView = `-- name: GetMessageView :one
SELECT m.id, m.tenant_id, m.conversation_id, m.phone_number_id, m.contact_id, m.direction, m.origin, m.wamid, m.type, m.content, m.media_id, m.template_id, m.reply_to_wamid, m.status, m.error_code, m.error_title, m.sent_by_user_id, m.api_key_id, m.campaign_id, m.idempotency_key, m.pricing_category, m.pricing_billable, m.recipient_country, m.meta_timestamp, m.status_updated_at, m.created_at, c.wa_id AS contact_wa_id, coalesce(c.name, c.profile_name) AS contact_name
FROM messages m JOIN contacts c ON c.id = m.contact_id
WHERE m.id = $1
`

type GetMessageViewRow struct {
	Message     Message
	ContactWaID string
	ContactName *string
}

func (q *Queries) GetMessageView(ctx context.Context, id uuid.UUID) (GetMessageViewRow, error) {
	row := q.db.QueryRow(ctx, getMessageView, id)
	var i GetMessageViewRow
	err := row.Scan(
		&i.Message.ID,
		&i.Message.TenantID,
		&i.Message.ConversationID,
		&i.Message.PhoneNumberID,
		&i.Message.ContactID,
		&i.Message.Direction,
		&i.Message.Origin,
		&i.Message.Wamid,
		&i.Message.Type,
		&i.Message.Content,
		&i.Message.MediaID,
		&i.Message.TemplateID,
		&i.Message.ReplyToWamid,
		&i.Message.Status,
		&i.Message.ErrorCode,
		&i.Message.ErrorTitle,
		&i.Message.SentByUserID,
		&i.Message.ApiKeyID,
		&i.Message.CampaignID,
		&i.Message.IdempotencyKey,
		&i.Message.PricingCategory,
		&i.Message.PricingBillable,
		&i.Message.RecipientCountry,
		&i.Message.MetaTimestamp,
		&i.Message.StatusUpdatedAt,
		&i.Message.CreatedAt,
		&i.ContactWaID,
		&i.ContactName,
	)
	return i, err
}

const getSendingNumber = `-- name: GetSendingNumber :one
SELECT p.id, p.tenant_id, p.whatsapp_account_id, p.phone_number_id, p.display_phone_number, p.verified_name, p.name_status, p.quality_rating, p.messaging_limit_tier, p.code_verification_status, p.is_coexistence, p.registered_at, p.two_step_pin_enc, p.status, p.business_profile, p.last_synced_at, p.created_at, p.updated_at, w.id, w.tenant_id, w.waba_id, w.business_id, w.name, w.currency, w.timezone_id, w.onboarding_flow, w.status, w.webhooks_subscribed_at, w.connected_at, w.disconnected_at, w.created_at, w.updated_at
FROM phone_numbers p JOIN whatsapp_accounts w ON w.id = p.whatsapp_account_id
WHERE p.id = $1
`

type GetSendingNumberRow struct {
	PhoneNumber     PhoneNumber
	WhatsappAccount WhatsappAccount
}

func (q *Queries) GetSendingNumber(ctx context.Context, id uuid.UUID) (GetSendingNumberRow, error) {
	row := q.db.QueryRow(ctx, getSendingNumber, id)
	var i GetSendingNumberRow
	err := row.Scan(
		&i.PhoneNumber.ID,
		&i.PhoneNumber.TenantID,
		&i.PhoneNumber.WhatsappAccountID,
		&i.PhoneNumber.PhoneNumberID,
		&i.PhoneNumber.DisplayPhoneNumber,
		&i.PhoneNumber.VerifiedName,
		&i.PhoneNumber.NameStatus,
		&i.PhoneNumber.QualityRating,
		&i.PhoneNumber.MessagingLimitTier,
		&i.PhoneNumber.CodeVerificationStatus,
		&i.PhoneNumber.IsCoexistence,
		&i.PhoneNumber.RegisteredAt,
		&i.PhoneNumber.TwoStepPinEnc,
		&i.PhoneNumber.Status,
		&i.PhoneNumber.BusinessProfile,
		&i.PhoneNumber.LastSyncedAt,
		&i.PhoneNumber.CreatedAt,
		&i.PhoneNumber.UpdatedAt,
		&i.WhatsappAccount.ID,
		&i.WhatsappAccount.TenantID,
		&i.WhatsappAccount.WabaID,
		&i.WhatsappAccount.BusinessID,
		&i.WhatsappAccount.Name,
		&i.WhatsappAccount.Currency,
		&i.WhatsappAccount.TimezoneID,
		&i.WhatsappAccount.OnboardingFlow,
		&i.WhatsappAccount.Status,
		&i.WhatsappAccount.WebhooksSubscribedAt,
		&i.WhatsappAccount.ConnectedAt,
		&i.WhatsappAccount.DisconnectedAt,
		&i.WhatsappAccount.CreatedAt,
		&i.WhatsappAccount.UpdatedAt,
	)
	return i, err
}

const hasUnsentMessageTo = `-- name: HasUnsentMessageTo :one
SELECT EXISTS (
    SELECT 1 FROM messages m JOIN contacts c ON c.id = m.contact_id
    WHERE m.phone_number_id = $1 AND c.wa_id = $2
      AND m.direction = 'outbound' AND m.status = 'queued' AND m.wamid IS NULL
)::boolean
`

type HasUnsentMessageToParams struct {
	PhoneNumberID uuid.UUID
	WaID          string
}

// True while an outbound message to this customer is still waiting for Meta's message ID.
func (q *Queries) HasUnsentMessageTo(ctx context.Context, arg HasUnsentMessageToParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnsentMessageTo, arg.PhoneNumberID, arg.WaID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const insertOutboundMessage = `-- name: InsertOutboundMessage :one
INSERT INTO messages (id, tenant_id, conversation_id, phone_number_id, contact_id, direction, origin,
                      type, content, template_id, reply_to_wamid, status, sent_by_user_id, idempotency_key, media_id)
VALUES ($1, $2, $3, $4, $5, 'outbound', $6, $7, $8, $9, $10, 'queued', $11, $12, $13)
RETURNING id, tenant_id, conversation_id, phone_number_id, contact_id, direction, origin, wamid, type, content, media_id, template_id, reply_to_wamid, status, error_code, error_title, sent_by_user_id, api_key_id, campaign_id, idempotency_key, pricing_category, pricing_billable, recipient_country, meta_timestamp, status_updated_at, created_at
`

type InsertOutboundMessageParams struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ConversationID uuid.UUID
	PhoneNumberID  uuid.UUID
	ContactID      uuid.UUID
	Origin         MessageOrigin
	Type           MessageType
	Content        []byte
	TemplateID     *uuid.UUID
	ReplyToWamid   *string
	SentByUserID   *uuid.UUID
	IdempotencyKey *string
	MediaID        *uuid.UUID
}

func (q *Queries) InsertOutboundMessage(ctx context.Context, arg InsertOutboundMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertOutboundMessage,
		arg.ID,
		arg.TenantID,
		arg.ConversationID,
		arg.PhoneNumberID,
		arg.ContactID,
		arg.Origin,
		arg.Type,
		arg.Content,
		arg.TemplateID,
		arg.ReplyToWamid,
		arg.SentByUserID,
		arg.IdempotencyKey,
		arg.MediaID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ConversationID,
		&i.PhoneNumberID,
		&i.ContactID,
		&i.Direction,
		&i.Origin,
		&i.Wamid,
		&i.Type,
		&i.Content,
		&i.MediaID,
		&i.TemplateID,
		&i.ReplyToWamid,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorTitle,
		&i.SentByUserID,
		&i.ApiKeyID,
		&i.CampaignID,
		&i.IdempotencyKey,
		&i.PricingCategory,
		&i.PricingBillable,
		&i.RecipientCountry,
		&i.MetaTimestamp,
		&i.StatusUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markMessageFailed = `-- name: MarkMessageFailed :execrows
UPDATE messages SET status = 'failed', error_code = $2, error_title = $3, status_updated_at = now()
WHERE id = $1 AND status = 'queued'
`

type MarkMessageFailedParams struct {
	ID         uuid.UUID
	ErrorCode  *int32
	ErrorTitle *string
}

func (q *Queries) MarkMessageFailed(ctx context.Context, arg MarkMessageFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMessageFailed, arg.ID, arg.ErrorCode, arg.ErrorTitle)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markMessageSent = `-- name: MarkMessageSent :execrows
UPDATE messages SET wamid = $2, status = 'sent', status_updated_at = now()
WHERE id = $1 AND status = 'queued'
`

type MarkMessageSentParams struct {
	ID    uuid.UUID
	Wamid *string
}

func (q *Queries) MarkMessageSent(ctx context.Context, arg MarkMessageSentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMessageSent, arg.ID, arg.Wamid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetConversationUnread = `-- name: ResetConversationUnread :exec
UPDATE conversations SET unread_count = 0, updated_at = now() WHERE id = $1
`

func (q *Queries) ResetConversationUnread(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetConversationUnread, id)
	return err
}

const restartIdempotencyRecord = `-- name: RestartIdempotencyRecord :exec
UPDATE idempotency_records
SET request_hash = $3, response_status = NULL, response_body = NULL, created_at = now()
WHERE tenant_id = $1 AND key = $2
`

type RestartIdempotencyRecordParams struct {
	TenantID    uuid.UUID
	Key         string
	RequestHash []byte
}

// Reuses a key whose 24 hours have passed.
func (q *Queries) RestartIdempotencyRecord(ctx context.Context, arg RestartIdempotencyRecordParams) error {
	_, err := q.db.Exec(ctx, restartIdempotencyRecord, arg.TenantID, arg.Key, arg.RequestHash)
	return err
}

const saveIdempotencyResponse = `-- name: SaveIdempotencyResponse :exec
UPDATE idempotency_records SET response_status = $3, response_body = $4 WHERE tenant_id = $1 AND key = $2
`

type SaveIdempotencyResponseParams struct {
	TenantID       uuid.UUID
	Key            string
	ResponseStatus *int32
	ResponseBody   []byte
}

func (q *Queries) SaveIdempotencyResponse(ctx context.Context, arg SaveIdempotencyResponseParams) error {
	_, err := q.db.Exec(ctx, saveIdempotencyResponse,
		arg.TenantID,
		arg.Key,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	return err
}
