// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metaevents.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const advanceMessageStatus = `-- name: AdvanceMessageStatus :execrows
UPDATE messages
SET status = $1, error_code = coalesce($2, error_code), error_title = coalesce($3, error_title),
    pricing_category = coalesce($4, pricing_category),
    pricing_billable = coalesce($5, pricing_billable),
    status_updated_at = now()
WHERE id = $6 AND message_status_rank($1) > message_status_rank(status)
`

type AdvanceMessageStatusParams struct {
	Status          MessageStatus
	ErrorCode       *int32
	ErrorTitle      *string
	PricingCategory *string
	PricingBillable *bool
	ID              uuid.UUID
}

func (q *Queries) AdvanceMessageStatus(ctx context.Context, arg AdvanceMessageStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceMessageStatus,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorTitle,
		arg.PricingCategory,
		arg.PricingBillable,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishMetaWebhookEvent = `-- name: FinishMetaWebhookEvent :exec
UPDATE meta_webhook_events SET processed_at = now(), error = $2 WHERE id = $1
`

type FinishMetaWebhookEventParams struct {
	ID    int64
	Error *string
}

func (q *Queries) FinishMetaWebhookEvent(ctx context.Context, arg FinishMetaWebhookEventParams) error {
	_, err := q.db.Exec(ctx, finishMetaWebhookEvent, arg.ID, arg.Error)
	return err
}

const getMessageByWamid = `-- name: GetMessageByWamid :one
SELECT id, tenant_id, conversation_id, phone_number_id, contact_id, direction, origin, wamid, type, content, media_id, template_id, reply_to_wamid, status, error_code, error_title, sent_by_user_id, api_key_id, campaign_id, idempotency_key, pricing_category, pricing_billable, recipient_country, meta_timestamp, status_updated_at, created_at FROM messages WHERE wamid = $1
`

func (q *Queries) GetMessageByWamid(ctx context.Context, wamid *string) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByWamid, wamid)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ConversationID,
		&i.PhoneNumberID,
		&i.ContactID,
		&i.Direction,
		&i.Origin,
		&i.Wamid,
		&i.Type,
		&i.Content,
		&i.MediaID,
		&i.TemplateID,
		&i.ReplyToWamid,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorTitle,
		&i.SentByUserID,
		&i.ApiKeyID,
		&i.CampaignID,
		&i.IdempotencyKey,
		&i.PricingCategory,
		&i.PricingBillable,
		&i.RecipientCountry,
		&i.MetaTimestamp,
		&i.StatusUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMetaWebhookEventByHash = `-- name: GetMetaWebhookEventByHash :one
SELECT id, processed_at FROM meta_webhook_events WHERE payload_hash = $1
`

type GetMetaWebhookEventByHashRow struct {
	ID          int64
	ProcessedAt *time.Time
}

func (q *Queries) GetMetaWebhookEventByHash(ctx context.Context, payloadHash []byte) (GetMetaWebhookEventByHashRow, error) {
	row := q.db.QueryRow(ctx, getMetaWebhookEventByHash, payloadHash)
	var i GetMetaWebhookEventByHashRow
	err := row.Scan(&i.ID, &i.ProcessedAt)
	return i, err
}

const insertMessageStatusEvent = `-- name: InsertMessageStatusEvent :exec
INSERT INTO message_status_events (tenant_id, message_id, status, error_code, error_title, occurred_at, raw)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertMessageStatusEventParams struct {
	TenantID   uuid.UUID
	MessageID  uuid.UUID
	Status     MessageStatus
	ErrorCode  *int32
	ErrorTitle *string
	OccurredAt time.Time
	Raw        []byte
}

func (q *Queries) InsertMessageStatusEvent(ctx context.Context, arg InsertMessageStatusEventParams) error {
	_, err := q.db.Exec(ctx, insertMessageStatusEvent,
		arg.TenantID,
		arg.MessageID,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorTitle,
		arg.OccurredAt,
		arg.Raw,
	)
	return err
}

const insertMetaWebhookEvent = `-- name: InsertMetaWebhookEvent :one
INSERT INTO meta_webhook_events (payload_hash, received_at, object, field, waba_id, meta_phone_number_id, tenant_id, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (payload_hash) DO NOTHING
RETURNING id
`

type InsertMetaWebhookEventParams struct {
	PayloadHash       []byte
	ReceivedAt        time.Time
	Object            string
	Field             *string
	WabaID            *string
	MetaPhoneNumberID *string
	TenantID          *uuid.UUID
	Payload           []byte
}

func (q *Queries) InsertMetaWebhookEvent(ctx context.Context, arg InsertMetaWebhookEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertMetaWebhookEvent,
		arg.PayloadHash,
		arg.ReceivedAt,
		arg.Object,
		arg.Field,
		arg.WabaID,
		arg.MetaPhoneNumberID,
		arg.TenantID,
		arg.Payload,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertWhatsAppMessage = `-- name: InsertWhatsAppMessage :one
INSERT INTO messages (id, tenant_id, conversation_id, phone_number_id, contact_id, direction, origin,
                      wamid, type, content, reply_to_wamid, status, meta_timestamp)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (wamid) DO NOTHING
RETURNING id
`

type InsertWhatsAppMessageParams struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ConversationID uuid.UUID
	PhoneNumberID  uuid.UUID
	ContactID      uuid.UUID
	Direction      MessageDirection
	Origin         MessageOrigin
	Wamid          *string
	Type           MessageType
	Content        []byte
	ReplyToWamid   *string
	Status         MessageStatus
	MetaTimestamp  *time.Time
}

// Inserts a message that came from WhatsApp (inbound, or an echo from the Business app).
// A replayed wamid inserts nothing.
func (q *Queries) InsertWhatsAppMessage(ctx context.Context, arg InsertWhatsAppMessageParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertWhatsAppMessage,
		arg.ID,
		arg.TenantID,
		arg.ConversationID,
		arg.PhoneNumberID,
		arg.ContactID,
		arg.Direction,
		arg.Origin,
		arg.Wamid,
		arg.Type,
		arg.Content,
		arg.ReplyToWamid,
		arg.Status,
		arg.MetaTimestamp,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const revokeWhatsAppAccount = `-- name: RevokeWhatsAppAccount :exec
UPDATE whatsapp_accounts SET status = 'revoked', disconnected_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) RevokeWhatsAppAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeWhatsAppAccount, id)
	return err
}

const routeMetaEvent = `-- name: RouteMetaEvent :one
SELECT coalesce(route_meta_event($1::text, $2::text), '00000000-0000-0000-0000-000000000000')::uuid AS tenant_id
`

type RouteMetaEventParams struct {
	PhoneNumberID string
	WabaID        string
}

func (q *Queries) RouteMetaEvent(ctx context.Context, arg RouteMetaEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, routeMetaEvent, arg.PhoneNumberID, arg.WabaID)
	var tenant_id uuid.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}

const setAccountPhoneNumbersStatus = `-- name: SetAccountPhoneNumbersStatus :exec
UPDATE phone_numbers SET status = $2, updated_at = now() WHERE whatsapp_account_id = $1
`

type SetAccountPhoneNumbersStatusParams struct {
	WhatsappAccountID uuid.UUID
	Status            ConnectionStatus
}

func (q *Queries) SetAccountPhoneNumbersStatus(ctx context.Context, arg SetAccountPhoneNumbersStatusParams) error {
	_, err := q.db.Exec(ctx, setAccountPhoneNumbersStatus, arg.WhatsappAccountID, arg.Status)
	return err
}

const touchConversationInbound = `-- name: TouchConversationInbound :exec
UPDATE conversations
SET last_inbound_at = greatest(coalesce(last_inbound_at, $1::timestamptz), $1::timestamptz),
    last_message_at = greatest(coalesce(last_message_at, $1::timestamptz), $1::timestamptz),
    last_message_preview = CASE WHEN last_message_at IS NULL OR last_message_at <= $1::timestamptz
                                THEN $2::text ELSE last_message_preview END,
    unread_count = unread_count + 1,
    status = CASE WHEN status = 'closed' THEN 'open'::conversation_status ELSE status END,
    updated_at = now()
WHERE id = $3
`

type TouchConversationInboundParams struct {
	At      time.Time
	Preview string
	ID      uuid.UUID
}

func (q *Queries) TouchConversationInbound(ctx context.Context, arg TouchConversationInboundParams) error {
	_, err := q.db.Exec(ctx, touchConversationInbound, arg.At, arg.Preview, arg.ID)
	return err
}

const touchConversationOutbound = `-- name: TouchConversationOutbound :exec
UPDATE conversations
SET last_message_at = greatest(coalesce(last_message_at, $1::timestamptz), $1::timestamptz),
    last_message_preview = CASE WHEN last_message_at IS NULL OR last_message_at <= $1::timestamptz
                                THEN $2::text ELSE last_message_preview END,
    updated_at = now()
WHERE id = $3
`

type TouchConversationOutboundParams struct {
	At      time.Time
	Preview string
	ID      uuid.UUID
}

func (q *Queries) TouchConversationOutbound(ctx context.Context, arg TouchConversationOutboundParams) error {
	_, err := q.db.Exec(ctx, touchConversationOutbound, arg.At, arg.Preview, arg.ID)
	return err
}

const updatePhoneLimitTierByDisplay = `-- name: UpdatePhoneLimitTierByDisplay :execrows
UPDATE phone_numbers p
SET messaging_limit_tier = $1, updated_at = now()
FROM whatsapp_accounts w
WHERE w.id = p.whatsapp_account_id AND w.waba_id = $2
  AND regexp_replace(p.display_phone_number, '[^0-9]', '', 'g') = $3::text
`

type UpdatePhoneLimitTierByDisplayParams struct {
	Tier          *string
	WabaID        string
	DisplayDigits string
}

func (q *Queries) UpdatePhoneLimitTierByDisplay(ctx context.Context, arg UpdatePhoneLimitTierByDisplayParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePhoneLimitTierByDisplay, arg.Tier, arg.WabaID, arg.DisplayDigits)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTemplateStatusByMetaID = `-- name: UpdateTemplateStatusByMetaID :execrows
UPDATE templates
SET status = $1, rejected_reason = $2, status_updated_at = now(), updated_at = now()
WHERE meta_template_id = $3
`

type UpdateTemplateStatusByMetaIDParams struct {
	Status         TemplateStatus
	RejectedReason *string
	MetaTemplateID *string
}

func (q *Queries) UpdateTemplateStatusByMetaID(ctx context.Context, arg UpdateTemplateStatusByMetaIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTemplateStatusByMetaID, arg.Status, arg.RejectedReason, arg.MetaTemplateID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertContactFromWhatsApp = `-- name: UpsertContactFromWhatsApp :one
INSERT INTO contacts (id, tenant_id, wa_id, profile_name, name)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, wa_id) DO UPDATE
SET profile_name = coalesce(EXCLUDED.profile_name, contacts.profile_name),
    name = coalesce(contacts.name, EXCLUDED.name),
    updated_at = now()
RETURNING id, tenant_id, wa_id, name, profile_name, language, custom_fields, opt_in_status, opted_in_at, opted_out_at, blocked, created_at, updated_at
`

type UpsertContactFromWhatsAppParams struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	WaID        string
	ProfileName *string
	Name        *string
}

func (q *Queries) UpsertContactFromWhatsApp(ctx context.Context, arg UpsertContactFromWhatsAppParams) (Contact, error) {
	row := q.db.QueryRow(ctx, upsertContactFromWhatsApp,
		arg.ID,
		arg.TenantID,
		arg.WaID,
		arg.ProfileName,
		arg.Name,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WaID,
		&i.Name,
		&i.ProfileName,
		&i.Language,
		&i.CustomFields,
		&i.OptInStatus,
		&i.OptedInAt,
		&i.OptedOutAt,
		&i.Blocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConversation = `-- name: UpsertConversation :one
INSERT INTO conversations (id, tenant_id, phone_number_id, contact_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (phone_number_id, contact_id) DO UPDATE SET updated_at = now()
RETURNING id, tenant_id, phone_number_id, contact_id, status, assignee_user_id, last_inbound_at, last_message_at, last_message_preview, unread_count, created_at, updated_at
`

type UpsertConversationParams struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	PhoneNumberID uuid.UUID
	ContactID     uuid.UUID
}

func (q *Queries) UpsertConversation(ctx context.Context, arg UpsertConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, upsertConversation,
		arg.ID,
		arg.TenantID,
		arg.PhoneNumberID,
		arg.ContactID,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneNumberID,
		&i.ContactID,
		&i.Status,
		&i.AssigneeUserID,
		&i.LastInboundAt,
		&i.LastMessageAt,
		&i.LastMessagePreview,
		&i.UnreadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
