// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metabilling.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminCreditLineProblems = `-- name: AdminCreditLineProblems :many
SELECT a.id, a.tenant_id, a.waba_id, a.business_id, a.name, a.currency, a.timezone_id, a.onboarding_flow, a.status, a.webhooks_subscribed_at, a.connected_at, a.disconnected_at, a.created_at, a.updated_at, a.credit_line_allocation_id, a.credit_line_attached_at, a.credit_line_error, t.name AS tenant_name FROM admin_credit_line_problems() a JOIN tenants t ON t.id = a.tenant_id
`

type AdminCreditLineProblemsRow struct {
	ID                     uuid.UUID
	TenantID               uuid.UUID
	WabaID                 string
	BusinessID             string
	Name                   *string
	Currency               *string
	TimezoneID             *string
	OnboardingFlow         OnboardingFlow
	Status                 ConnectionStatus
	WebhooksSubscribedAt   *time.Time
	ConnectedAt            *time.Time
	DisconnectedAt         *time.Time
	CreatedAt              time.Time
	UpdatedAt              time.Time
	CreditLineAllocationID *string
	CreditLineAttachedAt   *time.Time
	CreditLineError        *string
	TenantName             string
}

func (q *Queries) AdminCreditLineProblems(ctx context.Context) ([]AdminCreditLineProblemsRow, error) {
	rows, err := q.db.Query(ctx, adminCreditLineProblems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminCreditLineProblemsRow
	for rows.Next() {
		var i AdminCreditLineProblemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WabaID,
			&i.BusinessID,
			&i.Name,
			&i.Currency,
			&i.TimezoneID,
			&i.OnboardingFlow,
			&i.Status,
			&i.WebhooksSubscribedAt,
			&i.ConnectedAt,
			&i.DisconnectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreditLineAllocationID,
			&i.CreditLineAttachedAt,
			&i.CreditLineError,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListReconciliation = `-- name: AdminListReconciliation :many
SELECT r.tenant_id, r.waba_id, r.day, r.category, r.country, r.our_messages, r.meta_messages, r.our_cost_minor, r.meta_cost_minor, r.currency, r.status, r.checked_at, t.name AS tenant_name
FROM admin_meta_reconciliation($1::text, $2::date) r
JOIN tenants t ON t.id = r.tenant_id
LIMIT $3
`

type AdminListReconciliationParams struct {
	Status *string
	Since  pgtype.Date
	Lim    int32
}

type AdminListReconciliationRow struct {
	TenantID      uuid.UUID
	WabaID        string
	Day           pgtype.Date
	Category      string
	Country       string
	OurMessages   int64
	MetaMessages  int64
	OurCostMinor  int64
	MetaCostMinor int64
	Currency      string
	Status        string
	CheckedAt     time.Time
	TenantName    string
}

func (q *Queries) AdminListReconciliation(ctx context.Context, arg AdminListReconciliationParams) ([]AdminListReconciliationRow, error) {
	rows, err := q.db.Query(ctx, adminListReconciliation, arg.Status, arg.Since, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListReconciliationRow
	for rows.Next() {
		var i AdminListReconciliationRow
		if err := rows.Scan(
			&i.TenantID,
			&i.WabaID,
			&i.Day,
			&i.Category,
			&i.Country,
			&i.OurMessages,
			&i.MetaMessages,
			&i.OurCostMinor,
			&i.MetaCostMinor,
			&i.Currency,
			&i.Status,
			&i.CheckedAt,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreditLineCandidates = `-- name: ListCreditLineCandidates :many
SELECT id, tenant_id, waba_id, business_id, name, currency, timezone_id, onboarding_flow, status, webhooks_subscribed_at, connected_at, disconnected_at, created_at, updated_at, credit_line_allocation_id, credit_line_attached_at, credit_line_error FROM credit_line_candidates()
`

// Connected WABAs of workspaces paid through Ecogo that have no credit line yet.
func (q *Queries) ListCreditLineCandidates(ctx context.Context) ([]WhatsappAccount, error) {
	rows, err := q.db.Query(ctx, listCreditLineCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WhatsappAccount
	for rows.Next() {
		var i WhatsappAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WabaID,
			&i.BusinessID,
			&i.Name,
			&i.Currency,
			&i.TimezoneID,
			&i.OnboardingFlow,
			&i.Status,
			&i.WebhooksSubscribedAt,
			&i.ConnectedAt,
			&i.DisconnectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreditLineAllocationID,
			&i.CreditLineAttachedAt,
			&i.CreditLineError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetaBillingAccounts = `-- name: ListMetaBillingAccounts :many
SELECT id, tenant_id, waba_id, business_id, name, currency, timezone_id, onboarding_flow, status, webhooks_subscribed_at, connected_at, disconnected_at, created_at, updated_at, credit_line_allocation_id, credit_line_attached_at, credit_line_error FROM meta_billing_accounts()
`

// Connected WABAs of active workspaces, for the reconciliation job.
func (q *Queries) ListMetaBillingAccounts(ctx context.Context) ([]WhatsappAccount, error) {
	rows, err := q.db.Query(ctx, listMetaBillingAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WhatsappAccount
	for rows.Next() {
		var i WhatsappAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WabaID,
			&i.BusinessID,
			&i.Name,
			&i.Currency,
			&i.TimezoneID,
			&i.OnboardingFlow,
			&i.Status,
			&i.WebhooksSubscribedAt,
			&i.ConnectedAt,
			&i.DisconnectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreditLineAllocationID,
			&i.CreditLineAttachedAt,
			&i.CreditLineError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCreditLineResult = `-- name: SetCreditLineResult :exec
UPDATE whatsapp_accounts
SET credit_line_allocation_id = $1,
    credit_line_attached_at = CASE WHEN $1::text IS NOT NULL THEN now() END,
    credit_line_error = $2, updated_at = now()
WHERE id = $3
`

type SetCreditLineResultParams struct {
	AllocationID *string
	Error        *string
	ID           uuid.UUID
}

func (q *Queries) SetCreditLineResult(ctx context.Context, arg SetCreditLineResultParams) error {
	_, err := q.db.Exec(ctx, setCreditLineResult, arg.AllocationID, arg.Error, arg.ID)
	return err
}

const upsertReconciliation = `-- name: UpsertReconciliation :exec
INSERT INTO meta_reconciliation (tenant_id, waba_id, day, category, country, our_messages, meta_messages,
                                 our_cost_minor, meta_cost_minor, currency, status, checked_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, now())
ON CONFLICT (tenant_id, waba_id, day, category, country) DO UPDATE
SET our_messages = EXCLUDED.our_messages, meta_messages = EXCLUDED.meta_messages,
    our_cost_minor = EXCLUDED.our_cost_minor, meta_cost_minor = EXCLUDED.meta_cost_minor,
    currency = EXCLUDED.currency, status = EXCLUDED.status, checked_at = now()
`

type UpsertReconciliationParams struct {
	TenantID      uuid.UUID
	WabaID        string
	Day           pgtype.Date
	Category      string
	Country       string
	OurMessages   int64
	MetaMessages  int64
	OurCostMinor  int64
	MetaCostMinor int64
	Currency      string
	Status        string
}

func (q *Queries) UpsertReconciliation(ctx context.Context, arg UpsertReconciliationParams) error {
	_, err := q.db.Exec(ctx, upsertReconciliation,
		arg.TenantID,
		arg.WabaID,
		arg.Day,
		arg.Category,
		arg.Country,
		arg.OurMessages,
		arg.MetaMessages,
		arg.OurCostMinor,
		arg.MetaCostMinor,
		arg.Currency,
		arg.Status,
	)
	return err
}

const usageForReconciliation = `-- name: UsageForReconciliation :many
SELECT day, pricing_category, recipient_country, (sum(billable))::bigint AS billable
FROM usage_daily
WHERE day BETWEEN $1 AND $2 AND pricing_category <> 'service'
GROUP BY day, pricing_category, recipient_country
HAVING sum(billable) > 0
`

type UsageForReconciliationParams struct {
	FromDay pgtype.Date
	ToDay   pgtype.Date
}

type UsageForReconciliationRow struct {
	Day              pgtype.Date
	PricingCategory  string
	RecipientCountry string
	Billable         int64
}

func (q *Queries) UsageForReconciliation(ctx context.Context, arg UsageForReconciliationParams) ([]UsageForReconciliationRow, error) {
	rows, err := q.db.Query(ctx, usageForReconciliation, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageForReconciliationRow
	for rows.Next() {
		var i UsageForReconciliationRow
		if err := rows.Scan(
			&i.Day,
			&i.PricingCategory,
			&i.RecipientCountry,
			&i.Billable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
