// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metafees.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminGetMetaFeeStatement = `-- name: AdminGetMetaFeeStatement :one
SELECT id, tenant_id, month, number, lines, subscription, fee_minor, markup_bp, markup_minor, taxable_minor, gst_rate_bp, cgst_minor, sgst_minor, igst_minor, total_minor, place_of_supply, seller, buyer, status, paid_at, payment_reference, issued_at FROM admin_meta_fee_statement($1::uuid)
`

func (q *Queries) AdminGetMetaFeeStatement(ctx context.Context, id uuid.UUID) (MetaFeeStatement, error) {
	row := q.db.QueryRow(ctx, adminGetMetaFeeStatement, id)
	var i MetaFeeStatement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Month,
		&i.Number,
		&i.Lines,
		&i.Subscription,
		&i.FeeMinor,
		&i.MarkupBp,
		&i.MarkupMinor,
		&i.TaxableMinor,
		&i.GstRateBp,
		&i.CgstMinor,
		&i.SgstMinor,
		&i.IgstMinor,
		&i.TotalMinor,
		&i.PlaceOfSupply,
		&i.Seller,
		&i.Buyer,
		&i.Status,
		&i.PaidAt,
		&i.PaymentReference,
		&i.IssuedAt,
	)
	return i, err
}

const adminListMetaFeeStatements = `-- name: AdminListMetaFeeStatements :many
SELECT s.id, s.tenant_id, s.month, s.number, s.lines, s.subscription, s.fee_minor, s.markup_bp, s.markup_minor, s.taxable_minor, s.gst_rate_bp, s.cgst_minor, s.sgst_minor, s.igst_minor, s.total_minor, s.place_of_supply, s.seller, s.buyer, s.status, s.paid_at, s.payment_reference, s.issued_at, t.name AS tenant_name
FROM admin_meta_fee_statements($1::uuid, $2::text) s
JOIN tenants t ON t.id = s.tenant_id
LIMIT $3
`

type AdminListMetaFeeStatementsParams struct {
	TenantID *uuid.UUID
	Status   *string
	Lim      int32
}

type AdminListMetaFeeStatementsRow struct {
	ID               uuid.UUID
	TenantID         uuid.UUID
	Month            pgtype.Date
	Number           string
	Lines            []byte
	Subscription     []byte
	FeeMinor         int64
	MarkupBp         int32
	MarkupMinor      int64
	TaxableMinor     int64
	GstRateBp        int32
	CgstMinor        int64
	SgstMinor        int64
	IgstMinor        int64
	TotalMinor       int64
	PlaceOfSupply    string
	Seller           []byte
	Buyer            []byte
	Status           string
	PaidAt           *time.Time
	PaymentReference *string
	IssuedAt         time.Time
	TenantName       string
}

func (q *Queries) AdminListMetaFeeStatements(ctx context.Context, arg AdminListMetaFeeStatementsParams) ([]AdminListMetaFeeStatementsRow, error) {
	rows, err := q.db.Query(ctx, adminListMetaFeeStatements, arg.TenantID, arg.Status, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListMetaFeeStatementsRow
	for rows.Next() {
		var i AdminListMetaFeeStatementsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Month,
			&i.Number,
			&i.Lines,
			&i.Subscription,
			&i.FeeMinor,
			&i.MarkupBp,
			&i.MarkupMinor,
			&i.TaxableMinor,
			&i.GstRateBp,
			&i.CgstMinor,
			&i.SgstMinor,
			&i.IgstMinor,
			&i.TotalMinor,
			&i.PlaceOfSupply,
			&i.Seller,
			&i.Buyer,
			&i.Status,
			&i.PaidAt,
			&i.PaymentReference,
			&i.IssuedAt,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMetaRate = `-- name: DeleteMetaRate :execrows
DELETE FROM meta_rate_card WHERE id = $1
`

func (q *Queries) DeleteMetaRate(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMetaRate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMetaFeeStatement = `-- name: GetMetaFeeStatement :one
SELECT id, tenant_id, month, number, lines, subscription, fee_minor, markup_bp, markup_minor, taxable_minor, gst_rate_bp, cgst_minor, sgst_minor, igst_minor, total_minor, place_of_supply, seller, buyer, status, paid_at, payment_reference, issued_at FROM meta_fee_statements WHERE id = $1
`

func (q *Queries) GetMetaFeeStatement(ctx context.Context, id uuid.UUID) (MetaFeeStatement, error) {
	row := q.db.QueryRow(ctx, getMetaFeeStatement, id)
	var i MetaFeeStatement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Month,
		&i.Number,
		&i.Lines,
		&i.Subscription,
		&i.FeeMinor,
		&i.MarkupBp,
		&i.MarkupMinor,
		&i.TaxableMinor,
		&i.GstRateBp,
		&i.CgstMinor,
		&i.SgstMinor,
		&i.IgstMinor,
		&i.TotalMinor,
		&i.PlaceOfSupply,
		&i.Seller,
		&i.Buyer,
		&i.Status,
		&i.PaidAt,
		&i.PaymentReference,
		&i.IssuedAt,
	)
	return i, err
}

const insertMetaFeeStatement = `-- name: InsertMetaFeeStatement :execrows
INSERT INTO meta_fee_statements (id, tenant_id, month, number, lines, subscription, fee_minor, markup_bp, markup_minor,
                                 taxable_minor, gst_rate_bp, cgst_minor, sgst_minor, igst_minor, total_minor,
                                 place_of_supply, seller, buyer, issued_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11, $12, $13, $14, $15,
        $16, $17, $18, $19)
ON CONFLICT (tenant_id, month) DO NOTHING
`

type InsertMetaFeeStatementParams struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	Month         pgtype.Date
	Number        string
	Lines         []byte
	Subscription  []byte
	FeeMinor      int64
	MarkupBp      int32
	MarkupMinor   int64
	TaxableMinor  int64
	GstRateBp     int32
	CgstMinor     int64
	SgstMinor     int64
	IgstMinor     int64
	TotalMinor    int64
	PlaceOfSupply string
	Seller        []byte
	Buyer         []byte
	IssuedAt      time.Time
}

func (q *Queries) InsertMetaFeeStatement(ctx context.Context, arg InsertMetaFeeStatementParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertMetaFeeStatement,
		arg.ID,
		arg.TenantID,
		arg.Month,
		arg.Number,
		arg.Lines,
		arg.Subscription,
		arg.FeeMinor,
		arg.MarkupBp,
		arg.MarkupMinor,
		arg.TaxableMinor,
		arg.GstRateBp,
		arg.CgstMinor,
		arg.SgstMinor,
		arg.IgstMinor,
		arg.TotalMinor,
		arg.PlaceOfSupply,
		arg.Seller,
		arg.Buyer,
		arg.IssuedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listMetaFeeStatements = `-- name: ListMetaFeeStatements :many
SELECT id, tenant_id, month, number, lines, subscription, fee_minor, markup_bp, markup_minor, taxable_minor, gst_rate_bp, cgst_minor, sgst_minor, igst_minor, total_minor, place_of_supply, seller, buyer, status, paid_at, payment_reference, issued_at FROM meta_fee_statements ORDER BY month DESC
`

func (q *Queries) ListMetaFeeStatements(ctx context.Context) ([]MetaFeeStatement, error) {
	rows, err := q.db.Query(ctx, listMetaFeeStatements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetaFeeStatement
	for rows.Next() {
		var i MetaFeeStatement
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Month,
			&i.Number,
			&i.Lines,
			&i.Subscription,
			&i.FeeMinor,
			&i.MarkupBp,
			&i.MarkupMinor,
			&i.TaxableMinor,
			&i.GstRateBp,
			&i.CgstMinor,
			&i.SgstMinor,
			&i.IgstMinor,
			&i.TotalMinor,
			&i.PlaceOfSupply,
			&i.Seller,
			&i.Buyer,
			&i.Status,
			&i.PaidAt,
			&i.PaymentReference,
			&i.IssuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetaFeeTenants = `-- name: ListMetaFeeTenants :many
SELECT id, timezone, coalesce(meta_payment_mode_since, created_at)::timestamptz AS since
FROM tenants WHERE meta_payment_mode = 'through_us' AND status <> 'closed' ORDER BY id
`

type ListMetaFeeTenantsRow struct {
	ID       uuid.UUID
	Timezone string
	Since    time.Time
}

func (q *Queries) ListMetaFeeTenants(ctx context.Context) ([]ListMetaFeeTenantsRow, error) {
	rows, err := q.db.Query(ctx, listMetaFeeTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMetaFeeTenantsRow
	for rows.Next() {
		var i ListMetaFeeTenantsRow
		if err := rows.Scan(&i.ID, &i.Timezone, &i.Since); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetaRates = `-- name: ListMetaRates :many
SELECT id, category, country, rate_hundredths, effective_from, created_at FROM meta_rate_card ORDER BY category, country, effective_from DESC
`

func (q *Queries) ListMetaRates(ctx context.Context) ([]MetaRateCard, error) {
	rows, err := q.db.Query(ctx, listMetaRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetaRateCard
	for rows.Next() {
		var i MetaRateCard
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Country,
			&i.RateHundredths,
			&i.EffectiveFrom,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const metaFeeStatementExists = `-- name: MetaFeeStatementExists :one
SELECT EXISTS (SELECT 1 FROM meta_fee_statements WHERE month = $1)::boolean
`

func (q *Queries) MetaFeeStatementExists(ctx context.Context, month pgtype.Date) (bool, error) {
	row := q.db.QueryRow(ctx, metaFeeStatementExists, month)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const metaFeeUsage = `-- name: MetaFeeUsage :many
SELECT day, pricing_category, recipient_country, (sum(billable))::bigint AS billable
FROM usage_daily
WHERE day BETWEEN $1 AND $2 AND billable > 0 AND pricing_category <> 'service'
GROUP BY day, pricing_category, recipient_country
ORDER BY day
`

type MetaFeeUsageParams struct {
	FromDay pgtype.Date
	ToDay   pgtype.Date
}

type MetaFeeUsageRow struct {
	Day              pgtype.Date
	PricingCategory  string
	RecipientCountry string
	Billable         int64
}

// Billable messages of one workspace between two dates (inclusive), by day, category and country.
func (q *Queries) MetaFeeUsage(ctx context.Context, arg MetaFeeUsageParams) ([]MetaFeeUsageRow, error) {
	rows, err := q.db.Query(ctx, metaFeeUsage, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetaFeeUsageRow
	for rows.Next() {
		var i MetaFeeUsageRow
		if err := rows.Scan(
			&i.Day,
			&i.PricingCategory,
			&i.RecipientCountry,
			&i.Billable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMetaFeeStatementPaid = `-- name: SetMetaFeeStatementPaid :one
UPDATE meta_fee_statements
SET status = $1, paid_at = CASE WHEN $1 = 'paid' THEN now() END, payment_reference = $2
WHERE id = $3 RETURNING id, tenant_id, month, number, lines, subscription, fee_minor, markup_bp, markup_minor, taxable_minor, gst_rate_bp, cgst_minor, sgst_minor, igst_minor, total_minor, place_of_supply, seller, buyer, status, paid_at, payment_reference, issued_at
`

type SetMetaFeeStatementPaidParams struct {
	Status           string
	PaymentReference *string
	ID               uuid.UUID
}

func (q *Queries) SetMetaFeeStatementPaid(ctx context.Context, arg SetMetaFeeStatementPaidParams) (MetaFeeStatement, error) {
	row := q.db.QueryRow(ctx, setMetaFeeStatementPaid, arg.Status, arg.PaymentReference, arg.ID)
	var i MetaFeeStatement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Month,
		&i.Number,
		&i.Lines,
		&i.Subscription,
		&i.FeeMinor,
		&i.MarkupBp,
		&i.MarkupMinor,
		&i.TaxableMinor,
		&i.GstRateBp,
		&i.CgstMinor,
		&i.SgstMinor,
		&i.IgstMinor,
		&i.TotalMinor,
		&i.PlaceOfSupply,
		&i.Seller,
		&i.Buyer,
		&i.Status,
		&i.PaidAt,
		&i.PaymentReference,
		&i.IssuedAt,
	)
	return i, err
}

const setMetaPaymentMode = `-- name: SetMetaPaymentMode :one
UPDATE tenants SET meta_payment_mode = $1, meta_payment_mode_since = now(), updated_at = now()
WHERE id = $2 RETURNING id, name, slug, legal_name, status, suspended_reason, default_locale, timezone, message_retention_days, created_at, updated_at, meta_payment_mode, meta_payment_mode_since, require_two_factor
`

type SetMetaPaymentModeParams struct {
	Mode string
	ID   uuid.UUID
}

func (q *Queries) SetMetaPaymentMode(ctx context.Context, arg SetMetaPaymentModeParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, setMetaPaymentMode, arg.Mode, arg.ID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LegalName,
		&i.Status,
		&i.SuspendedReason,
		&i.DefaultLocale,
		&i.Timezone,
		&i.MessageRetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MetaPaymentMode,
		&i.MetaPaymentModeSince,
		&i.RequireTwoFactor,
	)
	return i, err
}

const subscriptionInvoicesBetween = `-- name: SubscriptionInvoicesBetween :many
SELECT number, total_minor, issued_at FROM invoices
WHERE issued_at >= $1 AND issued_at < $2 ORDER BY issued_at
`

type SubscriptionInvoicesBetweenParams struct {
	Start time.Time
	EndAt time.Time
}

type SubscriptionInvoicesBetweenRow struct {
	Number     string
	TotalMinor int64
	IssuedAt   time.Time
}

func (q *Queries) SubscriptionInvoicesBetween(ctx context.Context, arg SubscriptionInvoicesBetweenParams) ([]SubscriptionInvoicesBetweenRow, error) {
	rows, err := q.db.Query(ctx, subscriptionInvoicesBetween, arg.Start, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriptionInvoicesBetweenRow
	for rows.Next() {
		var i SubscriptionInvoicesBetweenRow
		if err := rows.Scan(&i.Number, &i.TotalMinor, &i.IssuedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMetaRate = `-- name: UpsertMetaRate :one
INSERT INTO meta_rate_card (id, category, country, rate_hundredths, effective_from)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (category, country, effective_from) DO UPDATE SET rate_hundredths = EXCLUDED.rate_hundredths
RETURNING id, category, country, rate_hundredths, effective_from, created_at
`

type UpsertMetaRateParams struct {
	ID             uuid.UUID
	Category       string
	Country        string
	RateHundredths int64
	EffectiveFrom  pgtype.Date
}

func (q *Queries) UpsertMetaRate(ctx context.Context, arg UpsertMetaRateParams) (MetaRateCard, error) {
	row := q.db.QueryRow(ctx, upsertMetaRate,
		arg.ID,
		arg.Category,
		arg.Country,
		arg.RateHundredths,
		arg.EffectiveFrom,
	)
	var i MetaRateCard
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Country,
		&i.RateHundredths,
		&i.EffectiveFrom,
		&i.CreatedAt,
	)
	return i, err
}
