// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ActorType string

const (
	ActorTypeUser          ActorType = "user"
	ActorTypePlatformAdmin ActorType = "platform_admin"
	ActorTypeApiKey        ActorType = "api_key"
	ActorTypeSystem        ActorType = "system"
	ActorTypeMeta          ActorType = "meta"
)

func (e *ActorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActorType(s)
	case string:
		*e = ActorType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActorType: %T", src)
	}
	return nil
}

type NullActorType struct {
	ActorType ActorType
	Valid     bool // Valid is true if ActorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActorType) Scan(value interface{}) error {
	if value == nil {
		ns.ActorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActorType), nil
}

func (e ActorType) Valid() bool {
	switch e {
	case ActorTypeUser,
		ActorTypePlatformAdmin,
		ActorTypeApiKey,
		ActorTypeSystem,
		ActorTypeMeta:
		return true
	}
	return false
}

type ApiKeyMode string

const (
	ApiKeyModeLive    ApiKeyMode = "live"
	ApiKeyModeSandbox ApiKeyMode = "sandbox"
)

func (e *ApiKeyMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApiKeyMode(s)
	case string:
		*e = ApiKeyMode(s)
	default:
		return fmt.Errorf("unsupported scan type for ApiKeyMode: %T", src)
	}
	return nil
}

type NullApiKeyMode struct {
	ApiKeyMode ApiKeyMode
	Valid      bool // Valid is true if ApiKeyMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApiKeyMode) Scan(value interface{}) error {
	if value == nil {
		ns.ApiKeyMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApiKeyMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApiKeyMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApiKeyMode), nil
}

func (e ApiKeyMode) Valid() bool {
	switch e {
	case ApiKeyModeLive,
		ApiKeyModeSandbox:
		return true
	}
	return false
}

type CampaignStatus string

const (
	CampaignStatusDraft     CampaignStatus = "draft"
	CampaignStatusScheduled CampaignStatus = "scheduled"
	CampaignStatusRunning   CampaignStatus = "running"
	CampaignStatusPaused    CampaignStatus = "paused"
	CampaignStatusCompleted CampaignStatus = "completed"
	CampaignStatusCancelled CampaignStatus = "cancelled"
	CampaignStatusFailed    CampaignStatus = "failed"
)

func (e *CampaignStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CampaignStatus(s)
	case string:
		*e = CampaignStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CampaignStatus: %T", src)
	}
	return nil
}

type NullCampaignStatus struct {
	CampaignStatus CampaignStatus
	Valid          bool // Valid is true if CampaignStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCampaignStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CampaignStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CampaignStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCampaignStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CampaignStatus), nil
}

func (e CampaignStatus) Valid() bool {
	switch e {
	case CampaignStatusDraft,
		CampaignStatusScheduled,
		CampaignStatusRunning,
		CampaignStatusPaused,
		CampaignStatusCompleted,
		CampaignStatusCancelled,
		CampaignStatusFailed:
		return true
	}
	return false
}

type ConnectionStatus string

const (
	ConnectionStatusPending      ConnectionStatus = "pending"
	ConnectionStatusConnected    ConnectionStatus = "connected"
	ConnectionStatusDisconnected ConnectionStatus = "disconnected"
	ConnectionStatusRevoked      ConnectionStatus = "revoked"
	ConnectionStatusError        ConnectionStatus = "error"
)

func (e *ConnectionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConnectionStatus(s)
	case string:
		*e = ConnectionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ConnectionStatus: %T", src)
	}
	return nil
}

type NullConnectionStatus struct {
	ConnectionStatus ConnectionStatus
	Valid            bool // Valid is true if ConnectionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConnectionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ConnectionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConnectionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConnectionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConnectionStatus), nil
}

func (e ConnectionStatus) Valid() bool {
	switch e {
	case ConnectionStatusPending,
		ConnectionStatusConnected,
		ConnectionStatusDisconnected,
		ConnectionStatusRevoked,
		ConnectionStatusError:
		return true
	}
	return false
}

type ConsentKind string

const (
	ConsentKindOptIn  ConsentKind = "opt_in"
	ConsentKindOptOut ConsentKind = "opt_out"
)

func (e *ConsentKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConsentKind(s)
	case string:
		*e = ConsentKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ConsentKind: %T", src)
	}
	return nil
}

type NullConsentKind struct {
	ConsentKind ConsentKind
	Valid       bool // Valid is true if ConsentKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConsentKind) Scan(value interface{}) error {
	if value == nil {
		ns.ConsentKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConsentKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConsentKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConsentKind), nil
}

func (e ConsentKind) Valid() bool {
	switch e {
	case ConsentKindOptIn,
		ConsentKindOptOut:
		return true
	}
	return false
}

type ConsentSource string

const (
	ConsentSourceDashboard         ConsentSource = "dashboard"
	ConsentSourceApi               ConsentSource = "api"
	ConsentSourceCsvImport         ConsentSource = "csv_import"
	ConsentSourceKeyword           ConsentSource = "keyword"
	ConsentSourceInboundMessage    ConsentSource = "inbound_message"
	ConsentSourceWhatsappFlow      ConsentSource = "whatsapp_flow"
	ConsentSourceCoexistenceImport ConsentSource = "coexistence_import"
)

func (e *ConsentSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConsentSource(s)
	case string:
		*e = ConsentSource(s)
	default:
		return fmt.Errorf("unsupported scan type for ConsentSource: %T", src)
	}
	return nil
}

type NullConsentSource struct {
	ConsentSource ConsentSource
	Valid         bool // Valid is true if ConsentSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConsentSource) Scan(value interface{}) error {
	if value == nil {
		ns.ConsentSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConsentSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConsentSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConsentSource), nil
}

func (e ConsentSource) Valid() bool {
	switch e {
	case ConsentSourceDashboard,
		ConsentSourceApi,
		ConsentSourceCsvImport,
		ConsentSourceKeyword,
		ConsentSourceInboundMessage,
		ConsentSourceWhatsappFlow,
		ConsentSourceCoexistenceImport:
		return true
	}
	return false
}

type ConversationStatus string

const (
	ConversationStatusOpen    ConversationStatus = "open"
	ConversationStatusPending ConversationStatus = "pending"
	ConversationStatusClosed  ConversationStatus = "closed"
)

func (e *ConversationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConversationStatus(s)
	case string:
		*e = ConversationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ConversationStatus: %T", src)
	}
	return nil
}

type NullConversationStatus struct {
	ConversationStatus ConversationStatus
	Valid              bool // Valid is true if ConversationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConversationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ConversationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConversationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConversationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConversationStatus), nil
}

func (e ConversationStatus) Valid() bool {
	switch e {
	case ConversationStatusOpen,
		ConversationStatusPending,
		ConversationStatusClosed:
		return true
	}
	return false
}

type DeliveryStatus string

const (
	DeliveryStatusPending   DeliveryStatus = "pending"
	DeliveryStatusSucceeded DeliveryStatus = "succeeded"
	DeliveryStatusRetrying  DeliveryStatus = "retrying"
	DeliveryStatusDead      DeliveryStatus = "dead"
)

func (e *DeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryStatus(s)
	case string:
		*e = DeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryStatus: %T", src)
	}
	return nil
}

type NullDeliveryStatus struct {
	DeliveryStatus DeliveryStatus
	Valid          bool // Valid is true if DeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryStatus), nil
}

func (e DeliveryStatus) Valid() bool {
	switch e {
	case DeliveryStatusPending,
		DeliveryStatusSucceeded,
		DeliveryStatusRetrying,
		DeliveryStatusDead:
		return true
	}
	return false
}

type MemberRole string

const (
	MemberRoleOwner     MemberRole = "owner"
	MemberRoleAdmin     MemberRole = "admin"
	MemberRoleAgent     MemberRole = "agent"
	MemberRoleDeveloper MemberRole = "developer"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole
	Valid      bool // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

func (e MemberRole) Valid() bool {
	switch e {
	case MemberRoleOwner,
		MemberRoleAdmin,
		MemberRoleAgent,
		MemberRoleDeveloper:
		return true
	}
	return false
}

type MessageDirection string

const (
	MessageDirectionInbound  MessageDirection = "inbound"
	MessageDirectionOutbound MessageDirection = "outbound"
)

func (e *MessageDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageDirection(s)
	case string:
		*e = MessageDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageDirection: %T", src)
	}
	return nil
}

type NullMessageDirection struct {
	MessageDirection MessageDirection
	Valid            bool // Valid is true if MessageDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageDirection) Scan(value interface{}) error {
	if value == nil {
		ns.MessageDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageDirection), nil
}

func (e MessageDirection) Valid() bool {
	switch e {
	case MessageDirectionInbound,
		MessageDirectionOutbound:
		return true
	}
	return false
}

type MessageOrigin string

const (
	MessageOriginCustomer  MessageOrigin = "customer"
	MessageOriginDashboard MessageOrigin = "dashboard"
	MessageOriginApi       MessageOrigin = "api"
	MessageOriginCampaign  MessageOrigin = "campaign"
	MessageOriginPhoneApp  MessageOrigin = "phone_app"
	MessageOriginBot       MessageOrigin = "bot"
)

func (e *MessageOrigin) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageOrigin(s)
	case string:
		*e = MessageOrigin(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageOrigin: %T", src)
	}
	return nil
}

type NullMessageOrigin struct {
	MessageOrigin MessageOrigin
	Valid         bool // Valid is true if MessageOrigin is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageOrigin) Scan(value interface{}) error {
	if value == nil {
		ns.MessageOrigin, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageOrigin.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageOrigin) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageOrigin), nil
}

func (e MessageOrigin) Valid() bool {
	switch e {
	case MessageOriginCustomer,
		MessageOriginDashboard,
		MessageOriginApi,
		MessageOriginCampaign,
		MessageOriginPhoneApp,
		MessageOriginBot:
		return true
	}
	return false
}

type MessageStatus string

const (
	MessageStatusQueued    MessageStatus = "queued"
	MessageStatusSent      MessageStatus = "sent"
	MessageStatusDelivered MessageStatus = "delivered"
	MessageStatusRead      MessageStatus = "read"
	MessageStatusFailed    MessageStatus = "failed"
	MessageStatusReceived  MessageStatus = "received"
	MessageStatusDeleted   MessageStatus = "deleted"
)

func (e *MessageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageStatus(s)
	case string:
		*e = MessageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageStatus: %T", src)
	}
	return nil
}

type NullMessageStatus struct {
	MessageStatus MessageStatus
	Valid         bool // Valid is true if MessageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MessageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageStatus), nil
}

func (e MessageStatus) Valid() bool {
	switch e {
	case MessageStatusQueued,
		MessageStatusSent,
		MessageStatusDelivered,
		MessageStatusRead,
		MessageStatusFailed,
		MessageStatusReceived,
		MessageStatusDeleted:
		return true
	}
	return false
}

type MessageType string

const (
	MessageTypeText        MessageType = "text"
	MessageTypeImage       MessageType = "image"
	MessageTypeVideo       MessageType = "video"
	MessageTypeAudio       MessageType = "audio"
	MessageTypeDocument    MessageType = "document"
	MessageTypeSticker     MessageType = "sticker"
	MessageTypeLocation    MessageType = "location"
	MessageTypeContacts    MessageType = "contacts"
	MessageTypeTemplate    MessageType = "template"
	MessageTypeInteractive MessageType = "interactive"
	MessageTypeReaction    MessageType = "reaction"
	MessageTypeButton      MessageType = "button"
	MessageTypeOrder       MessageType = "order"
	MessageTypeSystem      MessageType = "system"
	MessageTypeUnsupported MessageType = "unsupported"
)

func (e *MessageType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageType(s)
	case string:
		*e = MessageType(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageType: %T", src)
	}
	return nil
}

type NullMessageType struct {
	MessageType MessageType
	Valid       bool // Valid is true if MessageType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageType) Scan(value interface{}) error {
	if value == nil {
		ns.MessageType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageType), nil
}

func (e MessageType) Valid() bool {
	switch e {
	case MessageTypeText,
		MessageTypeImage,
		MessageTypeVideo,
		MessageTypeAudio,
		MessageTypeDocument,
		MessageTypeSticker,
		MessageTypeLocation,
		MessageTypeContacts,
		MessageTypeTemplate,
		MessageTypeInteractive,
		MessageTypeReaction,
		MessageTypeButton,
		MessageTypeOrder,
		MessageTypeSystem,
		MessageTypeUnsupported:
		return true
	}
	return false
}

type OnboardingFlow string

const (
	OnboardingFlowStandard    OnboardingFlow = "standard"
	OnboardingFlowCoexistence OnboardingFlow = "coexistence"
)

func (e *OnboardingFlow) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OnboardingFlow(s)
	case string:
		*e = OnboardingFlow(s)
	default:
		return fmt.Errorf("unsupported scan type for OnboardingFlow: %T", src)
	}
	return nil
}

type NullOnboardingFlow struct {
	OnboardingFlow OnboardingFlow
	Valid          bool // Valid is true if OnboardingFlow is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOnboardingFlow) Scan(value interface{}) error {
	if value == nil {
		ns.OnboardingFlow, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OnboardingFlow.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOnboardingFlow) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OnboardingFlow), nil
}

func (e OnboardingFlow) Valid() bool {
	switch e {
	case OnboardingFlowStandard,
		OnboardingFlowCoexistence:
		return true
	}
	return false
}

type OnboardingStep string

const (
	OnboardingStepStarted               OnboardingStep = "started"
	OnboardingStepCodeReceived          OnboardingStep = "code_received"
	OnboardingStepTokenExchanged        OnboardingStep = "token_exchanged"
	OnboardingStepWebhooksSubscribed    OnboardingStep = "webhooks_subscribed"
	OnboardingStepNumberRegistered      OnboardingStep = "number_registered"
	OnboardingStepContactsSyncRequested OnboardingStep = "contacts_sync_requested"
	OnboardingStepHistorySyncRequested  OnboardingStep = "history_sync_requested"
	OnboardingStepDetailsSynced         OnboardingStep = "details_synced"
	OnboardingStepCompleted             OnboardingStep = "completed"
	OnboardingStepFailed                OnboardingStep = "failed"
	OnboardingStepCancelled             OnboardingStep = "cancelled"
)

func (e *OnboardingStep) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OnboardingStep(s)
	case string:
		*e = OnboardingStep(s)
	default:
		return fmt.Errorf("unsupported scan type for OnboardingStep: %T", src)
	}
	return nil
}

type NullOnboardingStep struct {
	OnboardingStep OnboardingStep
	Valid          bool // Valid is true if OnboardingStep is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOnboardingStep) Scan(value interface{}) error {
	if value == nil {
		ns.OnboardingStep, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OnboardingStep.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOnboardingStep) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OnboardingStep), nil
}

func (e OnboardingStep) Valid() bool {
	switch e {
	case OnboardingStepStarted,
		OnboardingStepCodeReceived,
		OnboardingStepTokenExchanged,
		OnboardingStepWebhooksSubscribed,
		OnboardingStepNumberRegistered,
		OnboardingStepContactsSyncRequested,
		OnboardingStepHistorySyncRequested,
		OnboardingStepDetailsSynced,
		OnboardingStepCompleted,
		OnboardingStepFailed,
		OnboardingStepCancelled:
		return true
	}
	return false
}

type OptInStatus string

const (
	OptInStatusUnknown  OptInStatus = "unknown"
	OptInStatusOptedIn  OptInStatus = "opted_in"
	OptInStatusOptedOut OptInStatus = "opted_out"
)

func (e *OptInStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OptInStatus(s)
	case string:
		*e = OptInStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OptInStatus: %T", src)
	}
	return nil
}

type NullOptInStatus struct {
	OptInStatus OptInStatus
	Valid       bool // Valid is true if OptInStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOptInStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OptInStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OptInStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOptInStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OptInStatus), nil
}

func (e OptInStatus) Valid() bool {
	switch e {
	case OptInStatusUnknown,
		OptInStatusOptedIn,
		OptInStatusOptedOut:
		return true
	}
	return false
}

type QualityRating string

const (
	QualityRatingGreen   QualityRating = "green"
	QualityRatingYellow  QualityRating = "yellow"
	QualityRatingRed     QualityRating = "red"
	QualityRatingUnknown QualityRating = "unknown"
)

func (e *QualityRating) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QualityRating(s)
	case string:
		*e = QualityRating(s)
	default:
		return fmt.Errorf("unsupported scan type for QualityRating: %T", src)
	}
	return nil
}

type NullQualityRating struct {
	QualityRating QualityRating
	Valid         bool // Valid is true if QualityRating is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQualityRating) Scan(value interface{}) error {
	if value == nil {
		ns.QualityRating, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QualityRating.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQualityRating) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QualityRating), nil
}

func (e QualityRating) Valid() bool {
	switch e {
	case QualityRatingGreen,
		QualityRatingYellow,
		QualityRatingRed,
		QualityRatingUnknown:
		return true
	}
	return false
}

type RecipientStatus string

const (
	RecipientStatusPending   RecipientStatus = "pending"
	RecipientStatusSkipped   RecipientStatus = "skipped"
	RecipientStatusQueued    RecipientStatus = "queued"
	RecipientStatusSent      RecipientStatus = "sent"
	RecipientStatusDelivered RecipientStatus = "delivered"
	RecipientStatusRead      RecipientStatus = "read"
	RecipientStatusFailed    RecipientStatus = "failed"
)

func (e *RecipientStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecipientStatus(s)
	case string:
		*e = RecipientStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RecipientStatus: %T", src)
	}
	return nil
}

type NullRecipientStatus struct {
	RecipientStatus RecipientStatus
	Valid           bool // Valid is true if RecipientStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecipientStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RecipientStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecipientStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecipientStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecipientStatus), nil
}

func (e RecipientStatus) Valid() bool {
	switch e {
	case RecipientStatusPending,
		RecipientStatusSkipped,
		RecipientStatusQueued,
		RecipientStatusSent,
		RecipientStatusDelivered,
		RecipientStatusRead,
		RecipientStatusFailed:
		return true
	}
	return false
}

type SubscriptionStatus string

const (
	SubscriptionStatusTrialing  SubscriptionStatus = "trialing"
	SubscriptionStatusActive    SubscriptionStatus = "active"
	SubscriptionStatusPastDue   SubscriptionStatus = "past_due"
	SubscriptionStatusCancelled SubscriptionStatus = "cancelled"
)

func (e *SubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionStatus(s)
	case string:
		*e = SubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionStatus: %T", src)
	}
	return nil
}

type NullSubscriptionStatus struct {
	SubscriptionStatus SubscriptionStatus
	Valid              bool // Valid is true if SubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionStatus), nil
}

func (e SubscriptionStatus) Valid() bool {
	switch e {
	case SubscriptionStatusTrialing,
		SubscriptionStatusActive,
		SubscriptionStatusPastDue,
		SubscriptionStatusCancelled:
		return true
	}
	return false
}

type TemplateCategory string

const (
	TemplateCategoryMarketing      TemplateCategory = "marketing"
	TemplateCategoryUtility        TemplateCategory = "utility"
	TemplateCategoryAuthentication TemplateCategory = "authentication"
)

func (e *TemplateCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TemplateCategory(s)
	case string:
		*e = TemplateCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for TemplateCategory: %T", src)
	}
	return nil
}

type NullTemplateCategory struct {
	TemplateCategory TemplateCategory
	Valid            bool // Valid is true if TemplateCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTemplateCategory) Scan(value interface{}) error {
	if value == nil {
		ns.TemplateCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TemplateCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTemplateCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TemplateCategory), nil
}

func (e TemplateCategory) Valid() bool {
	switch e {
	case TemplateCategoryMarketing,
		TemplateCategoryUtility,
		TemplateCategoryAuthentication:
		return true
	}
	return false
}

type TemplateStatus string

const (
	TemplateStatusDraft    TemplateStatus = "draft"
	TemplateStatusPending  TemplateStatus = "pending"
	TemplateStatusApproved TemplateStatus = "approved"
	TemplateStatusRejected TemplateStatus = "rejected"
	TemplateStatusPaused   TemplateStatus = "paused"
	TemplateStatusDisabled TemplateStatus = "disabled"
	TemplateStatusInAppeal TemplateStatus = "in_appeal"
	TemplateStatusDeleted  TemplateStatus = "deleted"
)

func (e *TemplateStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TemplateStatus(s)
	case string:
		*e = TemplateStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TemplateStatus: %T", src)
	}
	return nil
}

type NullTemplateStatus struct {
	TemplateStatus TemplateStatus
	Valid          bool // Valid is true if TemplateStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTemplateStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TemplateStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TemplateStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTemplateStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TemplateStatus), nil
}

func (e TemplateStatus) Valid() bool {
	switch e {
	case TemplateStatusDraft,
		TemplateStatusPending,
		TemplateStatusApproved,
		TemplateStatusRejected,
		TemplateStatusPaused,
		TemplateStatusDisabled,
		TemplateStatusInAppeal,
		TemplateStatusDeleted:
		return true
	}
	return false
}

type TenantStatus string

const (
	TenantStatusActive    TenantStatus = "active"
	TenantStatusSuspended TenantStatus = "suspended"
	TenantStatusClosed    TenantStatus = "closed"
)

func (e *TenantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantStatus(s)
	case string:
		*e = TenantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantStatus: %T", src)
	}
	return nil
}

type NullTenantStatus struct {
	TenantStatus TenantStatus
	Valid        bool // Valid is true if TenantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TenantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantStatus), nil
}

func (e TenantStatus) Valid() bool {
	switch e {
	case TenantStatusActive,
		TenantStatusSuspended,
		TenantStatusClosed:
		return true
	}
	return false
}

type AiLog struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	BotID          *uuid.UUID
	ConversationID *uuid.UUID
	Question       string
	Answer         *string
	Confidence     *float32
	Outcome        string
	SourceIds      []uuid.UUID
	InputTokens    int32
	OutputTokens   int32
	CreatedAt      time.Time
}

type ApiKey struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	Name          string
	Prefix        string
	KeyHash       []byte
	Mode          ApiKeyMode
	PhoneNumberID *uuid.UUID
	CreatedBy     *uuid.UUID
	LastUsedAt    *time.Time
	RevokedAt     *time.Time
	CreatedAt     time.Time
}

type AuditLog struct {
	ID         int64
	TenantID   *uuid.UUID
	ActorType  ActorType
	ActorID    *uuid.UUID
	Action     string
	TargetType *string
	TargetID   *string
	Reason     *string
	Ip         *netip.Addr
	Metadata   []byte
	OccurredAt time.Time
}

type BillingProfile struct {
	TenantID  uuid.UUID
	LegalName string
	Gstin     *string
	StateCode string
	Address   string
	UpdatedAt time.Time
}

type Bot struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	Name          string
	Status        string
	PhoneNumberID *uuid.UUID
	Flow          []byte
	CreatedBy     *uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type BotSession struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	BotID          uuid.UUID
	ConversationID uuid.UUID
	ContactID      uuid.UUID
	NodeID         *string
	Vars           []byte
	Status         string
	EndReason      *string
	StartedAt      time.Time
	UpdatedAt      time.Time
	EndedAt        *time.Time
}

type Campaign struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	PhoneNumberID  uuid.UUID
	TemplateID     uuid.UUID
	Name           string
	Audience       []byte
	Variables      []byte
	Status         CampaignStatus
	ScheduledAt    *time.Time
	StartedAt      *time.Time
	FinishedAt     *time.Time
	SendRatePerMin *int32
	Stats          []byte
	CreatedBy      *uuid.UUID
	ApiKeyID       *uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	RunGeneration  int32
}

type CampaignRecipient struct {
	TenantID   uuid.UUID
	CampaignID uuid.UUID
	ContactID  uuid.UUID
	Status     RecipientStatus
	SkipReason *string
	MessageID  *uuid.UUID
	ErrorCode  *int32
	UpdatedAt  time.Time
}

type ConsentEvent struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	ContactID  uuid.UUID
	Kind       ConsentKind
	Source     ConsentSource
	Evidence   *string
	RecordedBy *uuid.UUID
	OccurredAt time.Time
}

type Contact struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	WaID         string
	Name         *string
	ProfileName  *string
	Language     *string
	CustomFields []byte
	OptInStatus  OptInStatus
	OptedInAt    *time.Time
	OptedOutAt   *time.Time
	Blocked      bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type ContactTag struct {
	TenantID  uuid.UUID
	ContactID uuid.UUID
	TagID     uuid.UUID
}

type Conversation struct {
	ID                 uuid.UUID
	TenantID           uuid.UUID
	PhoneNumberID      uuid.UUID
	ContactID          uuid.UUID
	Status             ConversationStatus
	AssigneeUserID     *uuid.UUID
	LastInboundAt      *time.Time
	LastMessageAt      *time.Time
	LastMessagePreview *string
	UnreadCount        int32
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type ConversationNote struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ConversationID uuid.UUID
	AuthorUserID   uuid.UUID
	Body           string
	CreatedAt      time.Time
}

type DataDeletionRequest struct {
	ID               uuid.UUID
	ConfirmationCode string
	MetaUserID       string
	Status           string
	RequestedAt      time.Time
	CompletedAt      *time.Time
}

type Flow struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	WhatsappAccountID uuid.UUID
	MetaFlowID        string
	Name              string
	Categories        []string
	Status            string
	FlowJson          []byte
	ValidationErrors  []byte
	PreviewUrl        *string
	PreviewExpiresAt  *time.Time
	CreatedBy         *uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	PublishedAt       *time.Time
}

type FlowSubmission struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	FlowID         *uuid.UUID
	MetaFlowID     *string
	ContactID      uuid.UUID
	ConversationID uuid.UUID
	MessageID      uuid.UUID
	FlowToken      *string
	Response       []byte
	CreatedAt      time.Time
}

type IdempotencyRecord struct {
	TenantID       uuid.UUID
	Key            string
	RequestHash    []byte
	ResponseStatus *int32
	ResponseBody   []byte
	CreatedAt      time.Time
}

type Invite struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Email      string
	Role       MemberRole
	TokenHash  []byte
	InvitedBy  uuid.UUID
	ExpiresAt  time.Time
	AcceptedAt *time.Time
	CreatedAt  time.Time
}

type Invoice struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	Number            string
	RazorpayPaymentID string
	Description       string
	PeriodStart       *time.Time
	PeriodEnd         *time.Time
	Sac               *string
	TotalMinor        int64
	TaxableMinor      int64
	GstRateBp         int32
	CgstMinor         int64
	SgstMinor         int64
	IgstMinor         int64
	PlaceOfSupply     string
	Seller            []byte
	Buyer             []byte
	IssuedAt          time.Time
	EmailedAt         *time.Time
}

type InvoiceCounter struct {
	Fy   string
	Last int32
}

type KbChunk struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	SourceID uuid.UUID
	Ord      int32
	Content  string
	Tsv      interface{}
}

type KbSource struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Kind       string
	Title      string
	Url        *string
	Status     string
	Error      *string
	ChunkCount int32
	CreatedBy  *uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Medium struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	PhoneNumberID  *uuid.UUID
	StorageKey     string
	MimeType       string
	SizeBytes      int64
	Sha256         []byte
	Filename       *string
	MetaMediaID    *string
	MetaUploadedAt *time.Time
	CreatedAt      time.Time
}

type Membership struct {
	TenantID  uuid.UUID
	UserID    uuid.UUID
	Role      MemberRole
	CreatedAt time.Time
}

type Message struct {
	ID               uuid.UUID
	TenantID         uuid.UUID
	ConversationID   uuid.UUID
	PhoneNumberID    uuid.UUID
	ContactID        uuid.UUID
	Direction        MessageDirection
	Origin           MessageOrigin
	Wamid            *string
	Type             MessageType
	Content          []byte
	MediaID          *uuid.UUID
	TemplateID       *uuid.UUID
	ReplyToWamid     *string
	Status           MessageStatus
	ErrorCode        *int32
	ErrorTitle       *string
	SentByUserID     *uuid.UUID
	ApiKeyID         *uuid.UUID
	CampaignID       *uuid.UUID
	IdempotencyKey   *string
	PricingCategory  *string
	PricingBillable  *bool
	RecipientCountry *string
	MetaTimestamp    *time.Time
	StatusUpdatedAt  time.Time
	CreatedAt        time.Time
	BotID            *uuid.UUID
}

type MessageStatusEvent struct {
	ID         int64
	TenantID   uuid.UUID
	MessageID  uuid.UUID
	Status     MessageStatus
	ErrorCode  *int32
	ErrorTitle *string
	OccurredAt time.Time
	Raw        []byte
}

type MetaApiError struct {
	ID         int64
	TenantID   *uuid.UUID
	Method     string
	Path       string
	HttpStatus int32
	Code       *int32
	Subcode    *int32
	Message    *string
	FbtraceID  *string
	OccurredAt time.Time
}

type MetaCredential struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	WhatsappAccountID uuid.UUID
	TokenCiphertext   []byte
	DataKeyCiphertext []byte
	MasterKeyVersion  int32
	Scopes            []string
	IsActive          bool
	LastUsedAt        *time.Time
	RevokedAt         *time.Time
	CreatedAt         time.Time
}

type MetaFeeStatement struct {
	ID               uuid.UUID
	TenantID         uuid.UUID
	Month            pgtype.Date
	Number           string
	Lines            []byte
	Subscription     []byte
	FeeMinor         int64
	MarkupBp         int32
	MarkupMinor      int64
	TaxableMinor     int64
	GstRateBp        int32
	CgstMinor        int64
	SgstMinor        int64
	IgstMinor        int64
	TotalMinor       int64
	PlaceOfSupply    string
	Seller           []byte
	Buyer            []byte
	Status           string
	PaidAt           *time.Time
	PaymentReference *string
	IssuedAt         time.Time
}

type MetaRateCard struct {
	ID             uuid.UUID
	Category       string
	Country        string
	RateHundredths int64
	EffectiveFrom  pgtype.Date
	CreatedAt      time.Time
}

type MetaReconciliation struct {
	TenantID      uuid.UUID
	WabaID        string
	Day           pgtype.Date
	Category      string
	Country       string
	OurMessages   int64
	MetaMessages  int64
	OurCostMinor  int64
	MetaCostMinor int64
	Currency      string
	Status        string
	CheckedAt     time.Time
}

type MetaWebhookEvent struct {
	ID                int64
	PayloadHash       []byte
	ReceivedAt        time.Time
	Object            string
	Field             *string
	WabaID            *string
	MetaPhoneNumberID *string
	TenantID          *uuid.UUID
	Payload           []byte
	ProcessedAt       *time.Time
	Error             *string
}

type OnboardingSession struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	UserID        uuid.UUID
	Flow          OnboardingFlow
	Step          OnboardingStep
	WabaID        *string
	PhoneNumberID *string
	BusinessID    *string
	ErrorCode     *string
	ErrorMessage  *string
	Attempts      int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	StepTimes     []byte
}

type PhoneNumber struct {
	ID                     uuid.UUID
	TenantID               uuid.UUID
	WhatsappAccountID      uuid.UUID
	PhoneNumberID          string
	DisplayPhoneNumber     string
	VerifiedName           *string
	NameStatus             *string
	QualityRating          QualityRating
	MessagingLimitTier     *string
	CodeVerificationStatus *string
	IsCoexistence          bool
	RegisteredAt           *time.Time
	TwoStepPinEnc          []byte
	Status                 ConnectionStatus
	BusinessProfile        []byte
	LastSyncedAt           *time.Time
	CreatedAt              time.Time
	UpdatedAt              time.Time
	PreviousQualityRating  *QualityRating
	QualityChangedAt       *time.Time
}

type Plan struct {
	Code                    string
	Name                    string
	PriceMinor              int64
	Currency                string
	IncludedNumbers         int32
	IncludedSeats           int32
	ExtraSeatMinor          int64
	Features                []byte
	IsActive                bool
	RazorpayPlanID          *string
	SortOrder               int32
	CreatedAt               time.Time
	UpdatedAt               time.Time
	ExtraSeatRazorpayPlanID *string
	AiRepliesPerMonth       int32
}

type QuickReply struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Shortcut  string
	Body      string
	CreatedBy *uuid.UUID
	CreatedAt time.Time
}

type RazorpayEvent struct {
	ID         string
	Event      string
	ReceivedAt time.Time
}

type Session struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TenantID   *uuid.UUID
	TokenHash  []byte
	MfaPassed  bool
	Ip         *netip.Addr
	UserAgent  *string
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
}

type Subscription struct {
	ID                         uuid.UUID
	TenantID                   uuid.UUID
	PlanCode                   *string
	Status                     SubscriptionStatus
	Seats                      int32
	CurrentPeriodStart         time.Time
	CurrentPeriodEnd           time.Time
	PaymentProvider            string
	ProviderCustomerID         *string
	ProviderSubscriptionID     *string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	CancelAtPeriodEnd          bool
	ExtraSeats                 int32
	SeatProviderSubscriptionID *string
}

type Tag struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Name     string
	Color    *string
}

type Template struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	WhatsappAccountID uuid.UUID
	MetaTemplateID    *string
	Name              string
	Language          string
	Category          TemplateCategory
	Status            TemplateStatus
	RejectedReason    *string
	QualityScore      *string
	ParameterFormat   string
	Components        []byte
	CreatedBy         *uuid.UUID
	SubmittedAt       *time.Time
	StatusUpdatedAt   *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Tenant struct {
	ID                   uuid.UUID
	Name                 string
	Slug                 string
	LegalName            *string
	Status               TenantStatus
	SuspendedReason      *string
	DefaultLocale        string
	Timezone             string
	MessageRetentionDays *int32
	CreatedAt            time.Time
	UpdatedAt            time.Time
	MetaPaymentMode      string
	MetaPaymentModeSince *time.Time
}

type UsageDaily struct {
	TenantID         uuid.UUID
	PhoneNumberID    uuid.UUID
	Day              pgtype.Date
	PricingCategory  string
	RecipientCountry string
	Origin           MessageOrigin
	Sent             int32
	Delivered        int32
	Read             int32
	Failed           int32
	Billable         int32
	EstMetaCostMinor int64
	Received         int32
}

type User struct {
	ID              uuid.UUID
	Email           string
	Name            string
	PasswordHash    string
	EmailVerifiedAt *time.Time
	TotpSecretEnc   []byte
	PreferredLocale *string
	IsPlatformAdmin bool
	LastLoginAt     *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type WebhookDelivery struct {
	ID               uuid.UUID
	TenantID         uuid.UUID
	EndpointID       uuid.UUID
	EventID          uuid.UUID
	EventType        string
	Payload          []byte
	Status           DeliveryStatus
	AttemptCount     int32
	NextAttemptAt    time.Time
	LastResponseCode *int32
	LastError        *string
	LastAttemptAt    *time.Time
	CreatedAt        time.Time
}

type WebhookEndpoint struct {
	ID               uuid.UUID
	TenantID         uuid.UUID
	Url              string
	Description      *string
	SecretCiphertext []byte
	EventTypes       []string
	PhoneNumberID    *uuid.UUID
	IsEnabled        bool
	DisabledReason   *string
	CreatedAt        time.Time
}

type WhatsappAccount struct {
	ID                     uuid.UUID
	TenantID               uuid.UUID
	WabaID                 string
	BusinessID             string
	Name                   *string
	Currency               *string
	TimezoneID             *string
	OnboardingFlow         OnboardingFlow
	Status                 ConnectionStatus
	WebhooksSubscribedAt   *time.Time
	ConnectedAt            *time.Time
	DisconnectedAt         *time.Time
	CreatedAt              time.Time
	UpdatedAt              time.Time
	CreditLineAllocationID *string
	CreditLineAttachedAt   *time.Time
	CreditLineError        *string
}
