// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const claimNotificationEmails = `-- name: ClaimNotificationEmails :many
SELECT n.id, n.title, n.body, n.link, u.email AS user_email, u.name AS user_name
FROM notifications n JOIN users u ON u.id = n.user_id
WHERE n.email = 'pending'
ORDER BY n.created_at
LIMIT $1
FOR UPDATE OF n SKIP LOCKED
`

type ClaimNotificationEmailsRow struct {
	ID        uuid.UUID
	Title     string
	Body      string
	Link      *string
	UserEmail string
	UserName  string
}

func (q *Queries) ClaimNotificationEmails(ctx context.Context, lim int32) ([]ClaimNotificationEmailsRow, error) {
	rows, err := q.db.Query(ctx, claimNotificationEmails, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimNotificationEmailsRow
	for rows.Next() {
		var i ClaimNotificationEmailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.UserEmail,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)::int FROM notifications WHERE user_id = $1 AND in_app AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listNotificationSettings = `-- name: ListNotificationSettings :many
SELECT tenant_id, user_id, kind, in_app, email FROM notification_settings WHERE user_id = $1
`

func (q *Queries) ListNotificationSettings(ctx context.Context, userID uuid.UUID) ([]NotificationSetting, error) {
	rows, err := q.db.Query(ctx, listNotificationSettings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationSetting
	for rows.Next() {
		var i NotificationSetting
		if err := rows.Scan(
			&i.TenantID,
			&i.UserID,
			&i.Kind,
			&i.InApp,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, tenant_id, user_id, kind, title, body, link, in_app, email, read_at, created_at FROM notifications WHERE user_id = $1 AND in_app ORDER BY created_at DESC, id DESC LIMIT $2
`

type ListNotificationsParams struct {
	UserID uuid.UUID
	Lim    int32
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.InApp,
			&i.Email,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationsRead = `-- name: MarkNotificationsRead :exec
UPDATE notifications SET read_at = now()
WHERE user_id = $1 AND in_app AND read_at IS NULL AND ($2::uuid[] IS NULL OR id = ANY($2::uuid[]))
`

type MarkNotificationsReadParams struct {
	UserID uuid.UUID
	Ids    []uuid.UUID
}

func (q *Queries) MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationsRead, arg.UserID, arg.Ids)
	return err
}

const notificationEmailTenants = `-- name: NotificationEmailTenants :many
SELECT t::uuid AS tenant_id FROM notification_email_tenants() t
`

func (q *Queries) NotificationEmailTenants(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, notificationEmailTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var tenant_id uuid.UUID
		if err := rows.Scan(&tenant_id); err != nil {
			return nil, err
		}
		items = append(items, tenant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNotificationEmail = `-- name: SetNotificationEmail :exec
UPDATE notifications SET email = $1 WHERE id = $2
`

type SetNotificationEmailParams struct {
	Email string
	ID    uuid.UUID
}

func (q *Queries) SetNotificationEmail(ctx context.Context, arg SetNotificationEmailParams) error {
	_, err := q.db.Exec(ctx, setNotificationEmail, arg.Email, arg.ID)
	return err
}

const upsertNotificationSetting = `-- name: UpsertNotificationSetting :exec
INSERT INTO notification_settings (tenant_id, user_id, kind, in_app, email)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, user_id, kind) DO UPDATE SET in_app = EXCLUDED.in_app, email = EXCLUDED.email
`

type UpsertNotificationSettingParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
	Kind     string
	InApp    bool
	Email    bool
}

func (q *Queries) UpsertNotificationSetting(ctx context.Context, arg UpsertNotificationSettingParams) error {
	_, err := q.db.Exec(ctx, upsertNotificationSetting,
		arg.TenantID,
		arg.UserID,
		arg.Kind,
		arg.InApp,
		arg.Email,
	)
	return err
}
