// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: numbers.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const disconnectPhoneNumber = `-- name: DisconnectPhoneNumber :exec
UPDATE phone_numbers SET status = 'disconnected', registered_at = NULL, updated_at = now() WHERE id = $1
`

// The number must register with Meta again when it is reconnected.
func (q *Queries) DisconnectPhoneNumber(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disconnectPhoneNumber, id)
	return err
}

const getPhoneNumber = `-- name: GetPhoneNumber :one
SELECT p.id, p.tenant_id, p.whatsapp_account_id, p.phone_number_id, p.display_phone_number, p.verified_name, p.name_status, p.quality_rating, p.messaging_limit_tier, p.code_verification_status, p.is_coexistence, p.registered_at, p.two_step_pin_enc, p.status, p.business_profile, p.last_synced_at, p.created_at, p.updated_at, w.waba_id
FROM phone_numbers p JOIN whatsapp_accounts w ON w.id = p.whatsapp_account_id
WHERE p.id = $1
`

type GetPhoneNumberRow struct {
	PhoneNumber PhoneNumber
	WabaID      string
}

func (q *Queries) GetPhoneNumber(ctx context.Context, id uuid.UUID) (GetPhoneNumberRow, error) {
	row := q.db.QueryRow(ctx, getPhoneNumber, id)
	var i GetPhoneNumberRow
	err := row.Scan(
		&i.PhoneNumber.ID,
		&i.PhoneNumber.TenantID,
		&i.PhoneNumber.WhatsappAccountID,
		&i.PhoneNumber.PhoneNumberID,
		&i.PhoneNumber.DisplayPhoneNumber,
		&i.PhoneNumber.VerifiedName,
		&i.PhoneNumber.NameStatus,
		&i.PhoneNumber.QualityRating,
		&i.PhoneNumber.MessagingLimitTier,
		&i.PhoneNumber.CodeVerificationStatus,
		&i.PhoneNumber.IsCoexistence,
		&i.PhoneNumber.RegisteredAt,
		&i.PhoneNumber.TwoStepPinEnc,
		&i.PhoneNumber.Status,
		&i.PhoneNumber.BusinessProfile,
		&i.PhoneNumber.LastSyncedAt,
		&i.PhoneNumber.CreatedAt,
		&i.PhoneNumber.UpdatedAt,
		&i.WabaID,
	)
	return i, err
}

const listPhoneNumbers = `-- name: ListPhoneNumbers :many
SELECT p.id, p.tenant_id, p.whatsapp_account_id, p.phone_number_id, p.display_phone_number, p.verified_name, p.name_status, p.quality_rating, p.messaging_limit_tier, p.code_verification_status, p.is_coexistence, p.registered_at, p.two_step_pin_enc, p.status, p.business_profile, p.last_synced_at, p.created_at, p.updated_at, w.waba_id
FROM phone_numbers p JOIN whatsapp_accounts w ON w.id = p.whatsapp_account_id
ORDER BY p.created_at
`

type ListPhoneNumbersRow struct {
	PhoneNumber PhoneNumber
	WabaID      string
}

func (q *Queries) ListPhoneNumbers(ctx context.Context) ([]ListPhoneNumbersRow, error) {
	rows, err := q.db.Query(ctx, listPhoneNumbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPhoneNumbersRow
	for rows.Next() {
		var i ListPhoneNumbersRow
		if err := rows.Scan(
			&i.PhoneNumber.ID,
			&i.PhoneNumber.TenantID,
			&i.PhoneNumber.WhatsappAccountID,
			&i.PhoneNumber.PhoneNumberID,
			&i.PhoneNumber.DisplayPhoneNumber,
			&i.PhoneNumber.VerifiedName,
			&i.PhoneNumber.NameStatus,
			&i.PhoneNumber.QualityRating,
			&i.PhoneNumber.MessagingLimitTier,
			&i.PhoneNumber.CodeVerificationStatus,
			&i.PhoneNumber.IsCoexistence,
			&i.PhoneNumber.RegisteredAt,
			&i.PhoneNumber.TwoStepPinEnc,
			&i.PhoneNumber.Status,
			&i.PhoneNumber.BusinessProfile,
			&i.PhoneNumber.LastSyncedAt,
			&i.PhoneNumber.CreatedAt,
			&i.PhoneNumber.UpdatedAt,
			&i.WabaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
