// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: onboarding.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const cancelOnboardingSession = `-- name: CancelOnboardingSession :exec
UPDATE onboarding_sessions
SET step = 'cancelled', error_code = $2, error_message = $3, updated_at = now()
WHERE id = $1 AND step IN ('started', 'code_received')
`

type CancelOnboardingSessionParams struct {
	ID           uuid.UUID
	ErrorCode    *string
	ErrorMessage *string
}

func (q *Queries) CancelOnboardingSession(ctx context.Context, arg CancelOnboardingSessionParams) error {
	_, err := q.db.Exec(ctx, cancelOnboardingSession, arg.ID, arg.ErrorCode, arg.ErrorMessage)
	return err
}

const createOnboardingSession = `-- name: CreateOnboardingSession :one
INSERT INTO onboarding_sessions (id, tenant_id, user_id, flow)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, user_id, flow, step, waba_id, phone_number_id, business_id, error_code, error_message, attempts, created_at, updated_at
`

type CreateOnboardingSessionParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	UserID   uuid.UUID
	Flow     OnboardingFlow
}

func (q *Queries) CreateOnboardingSession(ctx context.Context, arg CreateOnboardingSessionParams) (OnboardingSession, error) {
	row := q.db.QueryRow(ctx, createOnboardingSession,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Flow,
	)
	var i OnboardingSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Flow,
		&i.Step,
		&i.WabaID,
		&i.PhoneNumberID,
		&i.BusinessID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateCredentials = `-- name: DeactivateCredentials :exec
UPDATE meta_credentials SET is_active = false, revoked_at = now()
WHERE whatsapp_account_id = $1 AND is_active
`

func (q *Queries) DeactivateCredentials(ctx context.Context, whatsappAccountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateCredentials, whatsappAccountID)
	return err
}

const failOnboardingSession = `-- name: FailOnboardingSession :exec
UPDATE onboarding_sessions
SET error_code = $2, error_message = $3, attempts = attempts + 1, updated_at = now()
WHERE id = $1
`

type FailOnboardingSessionParams struct {
	ID           uuid.UUID
	ErrorCode    *string
	ErrorMessage *string
}

func (q *Queries) FailOnboardingSession(ctx context.Context, arg FailOnboardingSessionParams) error {
	_, err := q.db.Exec(ctx, failOnboardingSession, arg.ID, arg.ErrorCode, arg.ErrorMessage)
	return err
}

const getActiveCredential = `-- name: GetActiveCredential :one
SELECT id, tenant_id, whatsapp_account_id, token_ciphertext, data_key_ciphertext, master_key_version, scopes, is_active, last_used_at, revoked_at, created_at FROM meta_credentials WHERE whatsapp_account_id = $1 AND is_active
`

func (q *Queries) GetActiveCredential(ctx context.Context, whatsappAccountID uuid.UUID) (MetaCredential, error) {
	row := q.db.QueryRow(ctx, getActiveCredential, whatsappAccountID)
	var i MetaCredential
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WhatsappAccountID,
		&i.TokenCiphertext,
		&i.DataKeyCiphertext,
		&i.MasterKeyVersion,
		&i.Scopes,
		&i.IsActive,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOnboardingSession = `-- name: GetOnboardingSession :one
SELECT id, tenant_id, user_id, flow, step, waba_id, phone_number_id, business_id, error_code, error_message, attempts, created_at, updated_at FROM onboarding_sessions WHERE id = $1
`

func (q *Queries) GetOnboardingSession(ctx context.Context, id uuid.UUID) (OnboardingSession, error) {
	row := q.db.QueryRow(ctx, getOnboardingSession, id)
	var i OnboardingSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Flow,
		&i.Step,
		&i.WabaID,
		&i.PhoneNumberID,
		&i.BusinessID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOnboardingSessionForUpdate = `-- name: GetOnboardingSessionForUpdate :one
SELECT id, tenant_id, user_id, flow, step, waba_id, phone_number_id, business_id, error_code, error_message, attempts, created_at, updated_at FROM onboarding_sessions WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetOnboardingSessionForUpdate(ctx context.Context, id uuid.UUID) (OnboardingSession, error) {
	row := q.db.QueryRow(ctx, getOnboardingSessionForUpdate, id)
	var i OnboardingSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Flow,
		&i.Step,
		&i.WabaID,
		&i.PhoneNumberID,
		&i.BusinessID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPhoneNumberByMetaID = `-- name: GetPhoneNumberByMetaID :one
SELECT id, tenant_id, whatsapp_account_id, phone_number_id, display_phone_number, verified_name, name_status, quality_rating, messaging_limit_tier, code_verification_status, is_coexistence, registered_at, two_step_pin_enc, status, business_profile, last_synced_at, created_at, updated_at FROM phone_numbers WHERE phone_number_id = $1
`

func (q *Queries) GetPhoneNumberByMetaID(ctx context.Context, phoneNumberID string) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, getPhoneNumberByMetaID, phoneNumberID)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WhatsappAccountID,
		&i.PhoneNumberID,
		&i.DisplayPhoneNumber,
		&i.VerifiedName,
		&i.NameStatus,
		&i.QualityRating,
		&i.MessagingLimitTier,
		&i.CodeVerificationStatus,
		&i.IsCoexistence,
		&i.RegisteredAt,
		&i.TwoStepPinEnc,
		&i.Status,
		&i.BusinessProfile,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWhatsAppAccountByWabaID = `-- name: GetWhatsAppAccountByWabaID :one
SELECT id, tenant_id, waba_id, business_id, name, currency, timezone_id, onboarding_flow, status, webhooks_subscribed_at, connected_at, disconnected_at, created_at, updated_at FROM whatsapp_accounts WHERE waba_id = $1
`

func (q *Queries) GetWhatsAppAccountByWabaID(ctx context.Context, wabaID string) (WhatsappAccount, error) {
	row := q.db.QueryRow(ctx, getWhatsAppAccountByWabaID, wabaID)
	var i WhatsappAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WabaID,
		&i.BusinessID,
		&i.Name,
		&i.Currency,
		&i.TimezoneID,
		&i.OnboardingFlow,
		&i.Status,
		&i.WebhooksSubscribedAt,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCredential = `-- name: InsertCredential :exec
INSERT INTO meta_credentials (id, tenant_id, whatsapp_account_id, token_ciphertext, data_key_ciphertext, master_key_version, scopes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertCredentialParams struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	WhatsappAccountID uuid.UUID
	TokenCiphertext   []byte
	DataKeyCiphertext []byte
	MasterKeyVersion  int32
	Scopes            []string
}

func (q *Queries) InsertCredential(ctx context.Context, arg InsertCredentialParams) error {
	_, err := q.db.Exec(ctx, insertCredential,
		arg.ID,
		arg.TenantID,
		arg.WhatsappAccountID,
		arg.TokenCiphertext,
		arg.DataKeyCiphertext,
		arg.MasterKeyVersion,
		arg.Scopes,
	)
	return err
}

const insertMetaAPIError = `-- name: InsertMetaAPIError :exec
INSERT INTO meta_api_errors (tenant_id, method, path, http_status, code, subcode, message, fbtrace_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertMetaAPIErrorParams struct {
	TenantID   *uuid.UUID
	Method     string
	Path       string
	HttpStatus int32
	Code       *int32
	Subcode    *int32
	Message    *string
	FbtraceID  *string
}

func (q *Queries) InsertMetaAPIError(ctx context.Context, arg InsertMetaAPIErrorParams) error {
	_, err := q.db.Exec(ctx, insertMetaAPIError,
		arg.TenantID,
		arg.Method,
		arg.Path,
		arg.HttpStatus,
		arg.Code,
		arg.Subcode,
		arg.Message,
		arg.FbtraceID,
	)
	return err
}

const listOnboardingSessions = `-- name: ListOnboardingSessions :many
SELECT id, tenant_id, user_id, flow, step, waba_id, phone_number_id, business_id, error_code, error_message, attempts, created_at, updated_at FROM onboarding_sessions ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListOnboardingSessions(ctx context.Context, limit int32) ([]OnboardingSession, error) {
	rows, err := q.db.Query(ctx, listOnboardingSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OnboardingSession
	for rows.Next() {
		var i OnboardingSession
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Flow,
			&i.Step,
			&i.WabaID,
			&i.PhoneNumberID,
			&i.BusinessID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPhoneRegistered = `-- name: MarkPhoneRegistered :exec
UPDATE phone_numbers SET registered_at = now(), two_step_pin_enc = $2, updated_at = now() WHERE id = $1
`

type MarkPhoneRegisteredParams struct {
	ID            uuid.UUID
	TwoStepPinEnc []byte
}

func (q *Queries) MarkPhoneRegistered(ctx context.Context, arg MarkPhoneRegisteredParams) error {
	_, err := q.db.Exec(ctx, markPhoneRegistered, arg.ID, arg.TwoStepPinEnc)
	return err
}

const markWebhooksSubscribed = `-- name: MarkWebhooksSubscribed :exec
UPDATE whatsapp_accounts SET webhooks_subscribed_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) MarkWebhooksSubscribed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWebhooksSubscribed, id)
	return err
}

const markWhatsAppAccountConnected = `-- name: MarkWhatsAppAccountConnected :exec
UPDATE whatsapp_accounts SET status = 'connected', connected_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) MarkWhatsAppAccountConnected(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWhatsAppAccountConnected, id)
	return err
}

const markWhatsAppAccountError = `-- name: MarkWhatsAppAccountError :exec
UPDATE whatsapp_accounts SET status = 'error', updated_at = now() WHERE id = $1 AND status <> 'connected'
`

func (q *Queries) MarkWhatsAppAccountError(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWhatsAppAccountError, id)
	return err
}

const phoneNumberOwner = `-- name: PhoneNumberOwner :one
SELECT coalesce(phone_number_owner($1::text), '00000000-0000-0000-0000-000000000000')::uuid AS tenant_id
`

func (q *Queries) PhoneNumberOwner(ctx context.Context, phoneNumberID string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, phoneNumberOwner, phoneNumberID)
	var tenant_id uuid.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}

const setOnboardingCode = `-- name: SetOnboardingCode :exec
UPDATE onboarding_sessions
SET step = 'code_received', waba_id = $2, phone_number_id = $3, business_id = $4,
    error_code = NULL, error_message = NULL, updated_at = now()
WHERE id = $1
`

type SetOnboardingCodeParams struct {
	ID            uuid.UUID
	WabaID        *string
	PhoneNumberID *string
	BusinessID    *string
}

func (q *Queries) SetOnboardingCode(ctx context.Context, arg SetOnboardingCodeParams) error {
	_, err := q.db.Exec(ctx, setOnboardingCode,
		arg.ID,
		arg.WabaID,
		arg.PhoneNumberID,
		arg.BusinessID,
	)
	return err
}

const setOnboardingPhoneNumberID = `-- name: SetOnboardingPhoneNumberID :exec
UPDATE onboarding_sessions SET phone_number_id = $2, updated_at = now() WHERE id = $1
`

type SetOnboardingPhoneNumberIDParams struct {
	ID            uuid.UUID
	PhoneNumberID *string
}

func (q *Queries) SetOnboardingPhoneNumberID(ctx context.Context, arg SetOnboardingPhoneNumberIDParams) error {
	_, err := q.db.Exec(ctx, setOnboardingPhoneNumberID, arg.ID, arg.PhoneNumberID)
	return err
}

const setOnboardingStep = `-- name: SetOnboardingStep :exec
UPDATE onboarding_sessions
SET step = $2, error_code = NULL, error_message = NULL, updated_at = now()
WHERE id = $1
`

type SetOnboardingStepParams struct {
	ID   uuid.UUID
	Step OnboardingStep
}

func (q *Queries) SetOnboardingStep(ctx context.Context, arg SetOnboardingStepParams) error {
	_, err := q.db.Exec(ctx, setOnboardingStep, arg.ID, arg.Step)
	return err
}

const setPhoneNumberStatus = `-- name: SetPhoneNumberStatus :exec
UPDATE phone_numbers SET status = $2, updated_at = now() WHERE id = $1
`

type SetPhoneNumberStatusParams struct {
	ID     uuid.UUID
	Status ConnectionStatus
}

func (q *Queries) SetPhoneNumberStatus(ctx context.Context, arg SetPhoneNumberStatusParams) error {
	_, err := q.db.Exec(ctx, setPhoneNumberStatus, arg.ID, arg.Status)
	return err
}

const setPhoneTwoStepPin = `-- name: SetPhoneTwoStepPin :exec
UPDATE phone_numbers SET two_step_pin_enc = $2, updated_at = now() WHERE id = $1
`

type SetPhoneTwoStepPinParams struct {
	ID            uuid.UUID
	TwoStepPinEnc []byte
}

func (q *Queries) SetPhoneTwoStepPin(ctx context.Context, arg SetPhoneTwoStepPinParams) error {
	_, err := q.db.Exec(ctx, setPhoneTwoStepPin, arg.ID, arg.TwoStepPinEnc)
	return err
}

const touchCredential = `-- name: TouchCredential :exec
UPDATE meta_credentials SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchCredential(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchCredential, id)
	return err
}

const updateWhatsAppAccountDetails = `-- name: UpdateWhatsAppAccountDetails :exec
UPDATE whatsapp_accounts SET name = $2, currency = $3, timezone_id = $4, updated_at = now() WHERE id = $1
`

type UpdateWhatsAppAccountDetailsParams struct {
	ID         uuid.UUID
	Name       *string
	Currency   *string
	TimezoneID *string
}

func (q *Queries) UpdateWhatsAppAccountDetails(ctx context.Context, arg UpdateWhatsAppAccountDetailsParams) error {
	_, err := q.db.Exec(ctx, updateWhatsAppAccountDetails,
		arg.ID,
		arg.Name,
		arg.Currency,
		arg.TimezoneID,
	)
	return err
}

const upsertPhoneNumber = `-- name: UpsertPhoneNumber :one
INSERT INTO phone_numbers (id, tenant_id, whatsapp_account_id, phone_number_id, display_phone_number,
                           verified_name, name_status, quality_rating, messaging_limit_tier,
                           code_verification_status, is_coexistence, last_synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now())
ON CONFLICT (phone_number_id) DO UPDATE
SET display_phone_number = EXCLUDED.display_phone_number, verified_name = EXCLUDED.verified_name,
    name_status = EXCLUDED.name_status, quality_rating = EXCLUDED.quality_rating,
    messaging_limit_tier = EXCLUDED.messaging_limit_tier,
    code_verification_status = EXCLUDED.code_verification_status,
    is_coexistence = EXCLUDED.is_coexistence, last_synced_at = now(), updated_at = now()
RETURNING id, tenant_id, whatsapp_account_id, phone_number_id, display_phone_number, verified_name, name_status, quality_rating, messaging_limit_tier, code_verification_status, is_coexistence, registered_at, two_step_pin_enc, status, business_profile, last_synced_at, created_at, updated_at
`

type UpsertPhoneNumberParams struct {
	ID                     uuid.UUID
	TenantID               uuid.UUID
	WhatsappAccountID      uuid.UUID
	PhoneNumberID          string
	DisplayPhoneNumber     string
	VerifiedName           *string
	NameStatus             *string
	QualityRating          QualityRating
	MessagingLimitTier     *string
	CodeVerificationStatus *string
	IsCoexistence          bool
}

func (q *Queries) UpsertPhoneNumber(ctx context.Context, arg UpsertPhoneNumberParams) (PhoneNumber, error) {
	row := q.db.QueryRow(ctx, upsertPhoneNumber,
		arg.ID,
		arg.TenantID,
		arg.WhatsappAccountID,
		arg.PhoneNumberID,
		arg.DisplayPhoneNumber,
		arg.VerifiedName,
		arg.NameStatus,
		arg.QualityRating,
		arg.MessagingLimitTier,
		arg.CodeVerificationStatus,
		arg.IsCoexistence,
	)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WhatsappAccountID,
		&i.PhoneNumberID,
		&i.DisplayPhoneNumber,
		&i.VerifiedName,
		&i.NameStatus,
		&i.QualityRating,
		&i.MessagingLimitTier,
		&i.CodeVerificationStatus,
		&i.IsCoexistence,
		&i.RegisteredAt,
		&i.TwoStepPinEnc,
		&i.Status,
		&i.BusinessProfile,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWhatsAppAccount = `-- name: UpsertWhatsAppAccount :one
INSERT INTO whatsapp_accounts (id, tenant_id, waba_id, business_id, onboarding_flow)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (waba_id) DO UPDATE
SET business_id = EXCLUDED.business_id, onboarding_flow = EXCLUDED.onboarding_flow,
    status = 'pending', disconnected_at = NULL, updated_at = now()
RETURNING id, tenant_id, waba_id, business_id, name, currency, timezone_id, onboarding_flow, status, webhooks_subscribed_at, connected_at, disconnected_at, created_at, updated_at
`

type UpsertWhatsAppAccountParams struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	WabaID         string
	BusinessID     string
	OnboardingFlow OnboardingFlow
}

func (q *Queries) UpsertWhatsAppAccount(ctx context.Context, arg UpsertWhatsAppAccountParams) (WhatsappAccount, error) {
	row := q.db.QueryRow(ctx, upsertWhatsAppAccount,
		arg.ID,
		arg.TenantID,
		arg.WabaID,
		arg.BusinessID,
		arg.OnboardingFlow,
	)
	var i WhatsappAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WabaID,
		&i.BusinessID,
		&i.Name,
		&i.Currency,
		&i.TimezoneID,
		&i.OnboardingFlow,
		&i.Status,
		&i.WebhooksSubscribedAt,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const wabaOwner = `-- name: WabaOwner :one
SELECT coalesce(waba_owner($1::text), '00000000-0000-0000-0000-000000000000')::uuid AS tenant_id
`

func (q *Queries) WabaOwner(ctx context.Context, wabaID string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, wabaOwner, wabaID)
	var tenant_id uuid.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}
