// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearOldConversationPreviews = `-- name: ClearOldConversationPreviews :execrows
UPDATE conversations SET last_message_preview = NULL
WHERE last_message_at < $1 AND last_message_preview IS NOT NULL
`

// A conversation whose latest message was purged no longer shows its text in the inbox list.
func (q *Queries) ClearOldConversationPreviews(ctx context.Context, cutoff *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, clearOldConversationPreviews, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media WHERE id = $1
`

func (q *Queries) DeleteMedia(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMedia, id)
	return err
}

const listExpiredMedia = `-- name: ListExpiredMedia :many
SELECT id, storage_key FROM media WHERE created_at < $1 ORDER BY created_at LIMIT $2
`

type ListExpiredMediaParams struct {
	Cutoff time.Time
	Batch  int32
}

type ListExpiredMediaRow struct {
	ID         uuid.UUID
	StorageKey string
}

func (q *Queries) ListExpiredMedia(ctx context.Context, arg ListExpiredMediaParams) ([]ListExpiredMediaRow, error) {
	rows, err := q.db.Query(ctx, listExpiredMedia, arg.Cutoff, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredMediaRow
	for rows.Next() {
		var i ListExpiredMediaRow
		if err := rows.Scan(&i.ID, &i.StorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetentionTenants = `-- name: ListRetentionTenants :many
SELECT id, message_retention_days FROM tenants
WHERE status <> 'closed' AND message_retention_days IS NOT NULL
ORDER BY id
`

type ListRetentionTenantsRow struct {
	ID                   uuid.UUID
	MessageRetentionDays *int32
}

func (q *Queries) ListRetentionTenants(ctx context.Context) ([]ListRetentionTenantsRow, error) {
	rows, err := q.db.Query(ctx, listRetentionTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRetentionTenantsRow
	for rows.Next() {
		var i ListRetentionTenantsRow
		if err := rows.Scan(&i.ID, &i.MessageRetentionDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeOldMessages = `-- name: PurgeOldMessages :execrows
DELETE FROM messages
WHERE id IN (SELECT m.id FROM messages m WHERE m.created_at < $1 ORDER BY m.created_at LIMIT $2)
`

type PurgeOldMessagesParams struct {
	Cutoff time.Time
	Batch  int32
}

// Deletes at most @batch of the oldest messages from before @cutoff.
func (q *Queries) PurgeOldMessages(ctx context.Context, arg PurgeOldMessagesParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOldMessages, arg.Cutoff, arg.Batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
