// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: security.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countRecentAudit = `-- name: CountRecentAudit :one
SELECT count(*) FROM audit_log WHERE actor_id = $1 AND action = $2 AND occurred_at > $3
`

type CountRecentAuditParams struct {
	ActorID    *uuid.UUID
	Action     string
	OccurredAt time.Time
}

// Recent entries of one action by one user, for throttling repeated failures.
func (q *Queries) CountRecentAudit(ctx context.Context, arg CountRecentAuditParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentAudit, arg.ActorID, arg.Action, arg.OccurredAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSessionAuth = `-- name: GetSessionAuth :one
SELECT s.id, s.user_id, s.tenant_id, s.token_hash, s.mfa_passed, s.ip, s.user_agent, s.created_at, s.last_seen_at, s.expires_at, s.persistent, (u.totp_secret_enc IS NOT NULL)::boolean AS totp_enabled, u.is_platform_admin
FROM sessions s JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetSessionAuthRow struct {
	Session         Session
	TotpEnabled     bool
	IsPlatformAdmin bool
}

// The session with what the middleware needs to know about its user.
func (q *Queries) GetSessionAuth(ctx context.Context, tokenHash []byte) (GetSessionAuthRow, error) {
	row := q.db.QueryRow(ctx, getSessionAuth, tokenHash)
	var i GetSessionAuthRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.TenantID,
		&i.Session.TokenHash,
		&i.Session.MfaPassed,
		&i.Session.Ip,
		&i.Session.UserAgent,
		&i.Session.CreatedAt,
		&i.Session.LastSeenAt,
		&i.Session.ExpiresAt,
		&i.Session.Persistent,
		&i.TotpEnabled,
		&i.IsPlatformAdmin,
	)
	return i, err
}

const setPlatformAdmin = `-- name: SetPlatformAdmin :execrows
UPDATE users SET is_platform_admin = $2, updated_at = now() WHERE email = $1
`

type SetPlatformAdminParams struct {
	Email           string
	IsPlatformAdmin bool
}

func (q *Queries) SetPlatformAdmin(ctx context.Context, arg SetPlatformAdminParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPlatformAdmin, arg.Email, arg.IsPlatformAdmin)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSessionMFAPassed = `-- name: SetSessionMFAPassed :exec
UPDATE sessions SET mfa_passed = true WHERE id = $1
`

func (q *Queries) SetSessionMFAPassed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setSessionMFAPassed, id)
	return err
}

const setTOTPSecret = `-- name: SetTOTPSecret :exec
UPDATE users SET totp_secret_enc = $2, updated_at = now() WHERE id = $1
`

type SetTOTPSecretParams struct {
	ID            uuid.UUID
	TotpSecretEnc []byte
}

func (q *Queries) SetTOTPSecret(ctx context.Context, arg SetTOTPSecretParams) error {
	_, err := q.db.Exec(ctx, setTOTPSecret, arg.ID, arg.TotpSecretEnc)
	return err
}
