// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearSessionsForTenant = `-- name: ClearSessionsForTenant :exec
UPDATE sessions SET tenant_id = NULL WHERE user_id = $1 AND tenant_id = $2
`

type ClearSessionsForTenantParams struct {
	UserID   uuid.UUID
	TenantID *uuid.UUID
}

// A removed member's sessions in this workspace lose it as their selected tenant.
func (q *Queries) ClearSessionsForTenant(ctx context.Context, arg ClearSessionsForTenantParams) error {
	_, err := q.db.Exec(ctx, clearSessionsForTenant, arg.UserID, arg.TenantID)
	return err
}

const createVerifiedUser = `-- name: CreateVerifiedUser :one
INSERT INTO users (id, email, name, password_hash, email_verified_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, email, name, password_hash, email_verified_at, totp_secret_enc, preferred_locale, is_platform_admin, last_login_at, created_at, updated_at
`

type CreateVerifiedUserParams struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash string
}

func (q *Queries) CreateVerifiedUser(ctx context.Context, arg CreateVerifiedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createVerifiedUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.TotpSecretEnc,
		&i.PreferredLocale,
		&i.IsPlatformAdmin,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :execrows
DELETE FROM invites WHERE id = $1 AND accepted_at IS NULL
`

func (q *Queries) DeleteInvite(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvite, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships WHERE user_id = $1
`

func (q *Queries) DeleteMembership(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMembership, userID)
	return err
}

const deleteOpenInvite = `-- name: DeleteOpenInvite :exec
DELETE FROM invites WHERE email = $1 AND accepted_at IS NULL
`

func (q *Queries) DeleteOpenInvite(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteOpenInvite, email)
	return err
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :exec
DELETE FROM sessions WHERE user_id = $1 AND id <> $2
`

type DeleteOtherSessionsParams struct {
	UserID uuid.UUID
	KeepID uuid.UUID
}

func (q *Queries) DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteOtherSessions, arg.UserID, arg.KeepID)
	return err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role FROM memberships WHERE user_id = $1
`

func (q *Queries) GetMemberRole(ctx context.Context, userID uuid.UUID) (MemberRole, error) {
	row := q.db.QueryRow(ctx, getMemberRole, userID)
	var role MemberRole
	err := row.Scan(&role)
	return role, err
}

const insertInvite = `-- name: InsertInvite :one
INSERT INTO invites (id, tenant_id, email, role, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at
`

type InsertInviteParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Email     string
	Role      MemberRole
	TokenHash []byte
	InvitedBy uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) InsertInvite(ctx context.Context, arg InsertInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, insertInvite,
		arg.ID,
		arg.TenantID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const inviteByToken = `-- name: InviteByToken :one
SELECT i.id::uuid AS id, i.tenant_id::uuid AS tenant_id, i.tenant_name::text AS tenant_name, i.email::text AS email,
       i.role::member_role AS role, i.invited_by_name::text AS invited_by_name,
       i.expires_at::timestamptz AS expires_at, (i.accepted_at IS NOT NULL)::boolean AS accepted
FROM invite_by_token($1::bytea) i
`

type InviteByTokenRow struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	TenantName    string
	Email         string
	Role          MemberRole
	InvitedByName string
	ExpiresAt     time.Time
	Accepted      bool
}

func (q *Queries) InviteByToken(ctx context.Context, tokenHash []byte) (InviteByTokenRow, error) {
	row := q.db.QueryRow(ctx, inviteByToken, tokenHash)
	var i InviteByTokenRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TenantName,
		&i.Email,
		&i.Role,
		&i.InvitedByName,
		&i.ExpiresAt,
		&i.Accepted,
	)
	return i, err
}

const listOpenInvites = `-- name: ListOpenInvites :many
SELECT i.id, i.email, i.role, i.expires_at, i.created_at, u.name AS invited_by_name
FROM invites i JOIN users u ON u.id = i.invited_by
WHERE i.accepted_at IS NULL
ORDER BY i.created_at DESC
`

type ListOpenInvitesRow struct {
	ID            uuid.UUID
	Email         string
	Role          MemberRole
	ExpiresAt     time.Time
	CreatedAt     time.Time
	InvitedByName string
}

func (q *Queries) ListOpenInvites(ctx context.Context) ([]ListOpenInvitesRow, error) {
	rows, err := q.db.Query(ctx, listOpenInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenInvitesRow
	for rows.Next() {
		var i ListOpenInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.InvitedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeam = `-- name: ListTeam :many
SELECT u.id, u.name, u.email, u.last_login_at, m.role, m.created_at
FROM memberships m JOIN users u ON u.id = m.user_id
ORDER BY m.created_at
`

type ListTeamRow struct {
	ID          uuid.UUID
	Name        string
	Email       string
	LastLoginAt *time.Time
	Role        MemberRole
	CreatedAt   time.Time
}

func (q *Queries) ListTeam(ctx context.Context) ([]ListTeamRow, error) {
	rows, err := q.db.Query(ctx, listTeam)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamRow
	for rows.Next() {
		var i ListTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.LastLoginAt,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteAccepted = `-- name: MarkInviteAccepted :execrows
UPDATE invites SET accepted_at = now() WHERE id = $1 AND accepted_at IS NULL
`

func (q *Queries) MarkInviteAccepted(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markInviteAccepted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMemberRole = `-- name: SetMemberRole :exec
UPDATE memberships SET role = $2 WHERE user_id = $1
`

type SetMemberRoleParams struct {
	UserID uuid.UUID
	Role   MemberRole
}

func (q *Queries) SetMemberRole(ctx context.Context, arg SetMemberRoleParams) error {
	_, err := q.db.Exec(ctx, setMemberRole, arg.UserID, arg.Role)
	return err
}

const setPassword = `-- name: SetPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type SetPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) SetPassword(ctx context.Context, arg SetPasswordParams) error {
	_, err := q.db.Exec(ctx, setPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateTenantSettings = `-- name: UpdateTenantSettings :one
UPDATE tenants SET name = $2, legal_name = $3, timezone = $4, updated_at = now() WHERE id = $1
RETURNING id, name, slug, legal_name, status, suspended_reason, default_locale, timezone, message_retention_days, created_at, updated_at
`

type UpdateTenantSettingsParams struct {
	ID        uuid.UUID
	Name      string
	LegalName *string
	Timezone  string
}

func (q *Queries) UpdateTenantSettings(ctx context.Context, arg UpdateTenantSettingsParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantSettings,
		arg.ID,
		arg.Name,
		arg.LegalName,
		arg.Timezone,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LegalName,
		&i.Status,
		&i.SuspendedReason,
		&i.DefaultLocale,
		&i.Timezone,
		&i.MessageRetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserName = `-- name: UpdateUserName :exec
UPDATE users SET name = $2, updated_at = now() WHERE id = $1
`

type UpdateUserNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.db.Exec(ctx, updateUserName, arg.ID, arg.Name)
	return err
}
