// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteTemplatesByName = `-- name: DeleteTemplatesByName :execrows
DELETE FROM templates WHERE whatsapp_account_id = $1 AND name = $2
`

type DeleteTemplatesByNameParams struct {
	WhatsappAccountID uuid.UUID
	Name              string
}

func (q *Queries) DeleteTemplatesByName(ctx context.Context, arg DeleteTemplatesByNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTemplatesByName, arg.WhatsappAccountID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTemplatesMissingFromMeta = `-- name: DeleteTemplatesMissingFromMeta :execrows
DELETE FROM templates
WHERE whatsapp_account_id = $1 AND meta_template_id IS NOT NULL
  AND NOT (meta_template_id = ANY($2::text[]))
`

type DeleteTemplatesMissingFromMetaParams struct {
	WhatsappAccountID uuid.UUID
	Keep              []string
}

func (q *Queries) DeleteTemplatesMissingFromMeta(ctx context.Context, arg DeleteTemplatesMissingFromMetaParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTemplatesMissingFromMeta, arg.WhatsappAccountID, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, tenant_id, whatsapp_account_id, meta_template_id, name, language, category, status, rejected_reason, quality_score, parameter_format, components, created_by, submitted_at, status_updated_at, created_at, updated_at FROM templates WHERE id = $1
`

func (q *Queries) GetTemplate(ctx context.Context, id uuid.UUID) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WhatsappAccountID,
		&i.MetaTemplateID,
		&i.Name,
		&i.Language,
		&i.Category,
		&i.Status,
		&i.RejectedReason,
		&i.QualityScore,
		&i.ParameterFormat,
		&i.Components,
		&i.CreatedBy,
		&i.SubmittedAt,
		&i.StatusUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByName = `-- name: GetTemplateByName :one
SELECT id, tenant_id, whatsapp_account_id, meta_template_id, name, language, category, status, rejected_reason, quality_score, parameter_format, components, created_by, submitted_at, status_updated_at, created_at, updated_at FROM templates WHERE whatsapp_account_id = $1 AND name = $2 AND language = $3
`

type GetTemplateByNameParams struct {
	WhatsappAccountID uuid.UUID
	Name              string
	Language          string
}

func (q *Queries) GetTemplateByName(ctx context.Context, arg GetTemplateByNameParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByName, arg.WhatsappAccountID, arg.Name, arg.Language)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WhatsappAccountID,
		&i.MetaTemplateID,
		&i.Name,
		&i.Language,
		&i.Category,
		&i.Status,
		&i.RejectedReason,
		&i.QualityScore,
		&i.ParameterFormat,
		&i.Components,
		&i.CreatedBy,
		&i.SubmittedAt,
		&i.StatusUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWhatsAppAccount = `-- name: GetWhatsAppAccount :one
SELECT id, tenant_id, waba_id, business_id, name, currency, timezone_id, onboarding_flow, status, webhooks_subscribed_at, connected_at, disconnected_at, created_at, updated_at FROM whatsapp_accounts WHERE id = $1
`

func (q *Queries) GetWhatsAppAccount(ctx context.Context, id uuid.UUID) (WhatsappAccount, error) {
	row := q.db.QueryRow(ctx, getWhatsAppAccount, id)
	var i WhatsappAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WabaID,
		&i.BusinessID,
		&i.Name,
		&i.Currency,
		&i.TimezoneID,
		&i.OnboardingFlow,
		&i.Status,
		&i.WebhooksSubscribedAt,
		&i.ConnectedAt,
		&i.DisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, tenant_id, whatsapp_account_id, meta_template_id, name, language, category, status, rejected_reason, quality_score, parameter_format, components, created_by, submitted_at, status_updated_at, created_at, updated_at FROM templates
WHERE ($1::uuid IS NULL OR whatsapp_account_id = $1)
  AND ($2::template_status IS NULL OR status = $2)
  AND ($3::template_category IS NULL OR category = $3)
  AND ($4::text IS NULL OR name = $4)
  AND ($5::uuid IS NULL OR id < $5)
  AND status <> 'deleted'
ORDER BY id DESC
LIMIT $6
`

type ListTemplatesParams struct {
	WhatsappAccountID *uuid.UUID
	Status            *TemplateStatus
	Category          *TemplateCategory
	Name              *string
	Before            *uuid.UUID
	Lim               int32
}

func (q *Queries) ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates,
		arg.WhatsappAccountID,
		arg.Status,
		arg.Category,
		arg.Name,
		arg.Before,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WhatsappAccountID,
			&i.MetaTemplateID,
			&i.Name,
			&i.Language,
			&i.Category,
			&i.Status,
			&i.RejectedReason,
			&i.QualityScore,
			&i.ParameterFormat,
			&i.Components,
			&i.CreatedBy,
			&i.SubmittedAt,
			&i.StatusUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWhatsAppAccounts = `-- name: ListWhatsAppAccounts :many
SELECT id, tenant_id, waba_id, business_id, name, currency, timezone_id, onboarding_flow, status, webhooks_subscribed_at, connected_at, disconnected_at, created_at, updated_at FROM whatsapp_accounts ORDER BY created_at
`

func (q *Queries) ListWhatsAppAccounts(ctx context.Context) ([]WhatsappAccount, error) {
	rows, err := q.db.Query(ctx, listWhatsAppAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WhatsappAccount
	for rows.Next() {
		var i WhatsappAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WabaID,
			&i.BusinessID,
			&i.Name,
			&i.Currency,
			&i.TimezoneID,
			&i.OnboardingFlow,
			&i.Status,
			&i.WebhooksSubscribedAt,
			&i.ConnectedAt,
			&i.DisconnectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplateAfterEdit = `-- name: UpdateTemplateAfterEdit :one
UPDATE templates
SET category = $2, components = $3, status = 'pending', rejected_reason = NULL,
    submitted_at = now(), status_updated_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, whatsapp_account_id, meta_template_id, name, language, category, status, rejected_reason, quality_score, parameter_format, components, created_by, submitted_at, status_updated_at, created_at, updated_at
`

type UpdateTemplateAfterEditParams struct {
	ID         uuid.UUID
	Category   TemplateCategory
	Components []byte
}

func (q *Queries) UpdateTemplateAfterEdit(ctx context.Context, arg UpdateTemplateAfterEditParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplateAfterEdit, arg.ID, arg.Category, arg.Components)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WhatsappAccountID,
		&i.MetaTemplateID,
		&i.Name,
		&i.Language,
		&i.Category,
		&i.Status,
		&i.RejectedReason,
		&i.QualityScore,
		&i.ParameterFormat,
		&i.Components,
		&i.CreatedBy,
		&i.SubmittedAt,
		&i.StatusUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTemplateFromMeta = `-- name: UpsertTemplateFromMeta :one
INSERT INTO templates (id, tenant_id, whatsapp_account_id, meta_template_id, name, language, category, status,
                       rejected_reason, quality_score, parameter_format, components, created_by, submitted_at,
                       status_updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, now())
ON CONFLICT (whatsapp_account_id, name, language) DO UPDATE
SET meta_template_id = EXCLUDED.meta_template_id,
    category = EXCLUDED.category,
    status = EXCLUDED.status,
    rejected_reason = EXCLUDED.rejected_reason,
    quality_score = EXCLUDED.quality_score,
    parameter_format = EXCLUDED.parameter_format,
    components = EXCLUDED.components,
    created_by = coalesce(templates.created_by, EXCLUDED.created_by),
    submitted_at = coalesce(EXCLUDED.submitted_at, templates.submitted_at),
    status_updated_at = CASE WHEN templates.status <> EXCLUDED.status THEN now() ELSE templates.status_updated_at END,
    updated_at = now()
RETURNING id, tenant_id, whatsapp_account_id, meta_template_id, name, language, category, status, rejected_reason, quality_score, parameter_format, components, created_by, submitted_at, status_updated_at, created_at, updated_at
`

type UpsertTemplateFromMetaParams struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	WhatsappAccountID uuid.UUID
	MetaTemplateID    *string
	Name              string
	Language          string
	Category          TemplateCategory
	Status            TemplateStatus
	RejectedReason    *string
	QualityScore      *string
	ParameterFormat   string
	Components        []byte
	CreatedBy         *uuid.UUID
	SubmittedAt       *time.Time
}

func (q *Queries) UpsertTemplateFromMeta(ctx context.Context, arg UpsertTemplateFromMetaParams) (Template, error) {
	row := q.db.QueryRow(ctx, upsertTemplateFromMeta,
		arg.ID,
		arg.TenantID,
		arg.WhatsappAccountID,
		arg.MetaTemplateID,
		arg.Name,
		arg.Language,
		arg.Category,
		arg.Status,
		arg.RejectedReason,
		arg.QualityScore,
		arg.ParameterFormat,
		arg.Components,
		arg.CreatedBy,
		arg.SubmittedAt,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WhatsappAccountID,
		&i.MetaTemplateID,
		&i.Name,
		&i.Language,
		&i.Category,
		&i.Status,
		&i.RejectedReason,
		&i.QualityScore,
		&i.ParameterFormat,
		&i.Components,
		&i.CreatedBy,
		&i.SubmittedAt,
		&i.StatusUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
