// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteWebhookEndpoint = `-- name: DeleteWebhookEndpoint :execrows
DELETE FROM webhook_endpoints WHERE id = $1
`

func (q *Queries) DeleteWebhookEndpoint(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhookEndpoint, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeliveryForSend = `-- name: GetDeliveryForSend :one
SELECT d.id, d.tenant_id, d.endpoint_id, d.event_id, d.event_type, d.payload, d.status, d.attempt_count, d.next_attempt_at, d.last_response_code, d.last_error, d.last_attempt_at, d.created_at, e.id, e.tenant_id, e.url, e.description, e.secret_ciphertext, e.event_types, e.phone_number_id, e.is_enabled, e.disabled_reason, e.created_at
FROM webhook_deliveries d JOIN webhook_endpoints e ON e.id = d.endpoint_id
WHERE d.id = $1
`

type GetDeliveryForSendRow struct {
	WebhookDelivery WebhookDelivery
	WebhookEndpoint WebhookEndpoint
}

func (q *Queries) GetDeliveryForSend(ctx context.Context, id uuid.UUID) (GetDeliveryForSendRow, error) {
	row := q.db.QueryRow(ctx, getDeliveryForSend, id)
	var i GetDeliveryForSendRow
	err := row.Scan(
		&i.WebhookDelivery.ID,
		&i.WebhookDelivery.TenantID,
		&i.WebhookDelivery.EndpointID,
		&i.WebhookDelivery.EventID,
		&i.WebhookDelivery.EventType,
		&i.WebhookDelivery.Payload,
		&i.WebhookDelivery.Status,
		&i.WebhookDelivery.AttemptCount,
		&i.WebhookDelivery.NextAttemptAt,
		&i.WebhookDelivery.LastResponseCode,
		&i.WebhookDelivery.LastError,
		&i.WebhookDelivery.LastAttemptAt,
		&i.WebhookDelivery.CreatedAt,
		&i.WebhookEndpoint.ID,
		&i.WebhookEndpoint.TenantID,
		&i.WebhookEndpoint.Url,
		&i.WebhookEndpoint.Description,
		&i.WebhookEndpoint.SecretCiphertext,
		&i.WebhookEndpoint.EventTypes,
		&i.WebhookEndpoint.PhoneNumberID,
		&i.WebhookEndpoint.IsEnabled,
		&i.WebhookEndpoint.DisabledReason,
		&i.WebhookEndpoint.CreatedAt,
	)
	return i, err
}

const getWebhookEndpoint = `-- name: GetWebhookEndpoint :one
SELECT id, tenant_id, url, description, secret_ciphertext, event_types, phone_number_id, is_enabled, disabled_reason, created_at FROM webhook_endpoints WHERE id = $1
`

func (q *Queries) GetWebhookEndpoint(ctx context.Context, id uuid.UUID) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpoint, id)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Description,
		&i.SecretCiphertext,
		&i.EventTypes,
		&i.PhoneNumberID,
		&i.IsEnabled,
		&i.DisabledReason,
		&i.CreatedAt,
	)
	return i, err
}

const insertDeliveriesForEvent = `-- name: InsertDeliveriesForEvent :many
INSERT INTO webhook_deliveries (tenant_id, endpoint_id, event_id, event_type, payload)
SELECT e.tenant_id, e.id, $1, $2::text, $3
FROM webhook_endpoints e
WHERE e.is_enabled AND $2::text = ANY (e.event_types)
  AND (e.phone_number_id IS NULL OR e.phone_number_id = $4)
RETURNING id
`

type InsertDeliveriesForEventParams struct {
	EventID       uuid.UUID
	EventType     string
	Payload       []byte
	PhoneNumberID *uuid.UUID
}

// Creates one delivery per enabled endpoint that subscribes to the event (and its number).
func (q *Queries) InsertDeliveriesForEvent(ctx context.Context, arg InsertDeliveriesForEventParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, insertDeliveriesForEvent,
		arg.EventID,
		arg.EventType,
		arg.Payload,
		arg.PhoneNumberID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWebhookEndpoint = `-- name: InsertWebhookEndpoint :one
INSERT INTO webhook_endpoints (id, tenant_id, url, description, secret_ciphertext, event_types, phone_number_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, url, description, secret_ciphertext, event_types, phone_number_id, is_enabled, disabled_reason, created_at
`

type InsertWebhookEndpointParams struct {
	ID               uuid.UUID
	TenantID         uuid.UUID
	Url              string
	Description      *string
	SecretCiphertext []byte
	EventTypes       []string
	PhoneNumberID    *uuid.UUID
}

func (q *Queries) InsertWebhookEndpoint(ctx context.Context, arg InsertWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, insertWebhookEndpoint,
		arg.ID,
		arg.TenantID,
		arg.Url,
		arg.Description,
		arg.SecretCiphertext,
		arg.EventTypes,
		arg.PhoneNumberID,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Description,
		&i.SecretCiphertext,
		&i.EventTypes,
		&i.PhoneNumberID,
		&i.IsEnabled,
		&i.DisabledReason,
		&i.CreatedAt,
	)
	return i, err
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT id, tenant_id, endpoint_id, event_id, event_type, payload, status, attempt_count, next_attempt_at, last_response_code, last_error, last_attempt_at, created_at FROM webhook_deliveries
WHERE endpoint_id = $1
  AND ($2::delivery_status IS NULL OR status = $2)
  AND ($3::timestamptz IS NULL OR (created_at, id) < ($3, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListDeliveriesParams struct {
	EndpointID uuid.UUID
	Status     *DeliveryStatus
	BeforeAt   *time.Time
	BeforeID   *uuid.UUID
	Lim        int32
}

func (q *Queries) ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listDeliveries,
		arg.EndpointID,
		arg.Status,
		arg.BeforeAt,
		arg.BeforeID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EndpointID,
			&i.EventID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LastResponseCode,
			&i.LastError,
			&i.LastAttemptAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpoints = `-- name: ListWebhookEndpoints :many
SELECT id, tenant_id, url, description, secret_ciphertext, event_types, phone_number_id, is_enabled, disabled_reason, created_at FROM webhook_endpoints ORDER BY created_at DESC
`

func (q *Queries) ListWebhookEndpoints(ctx context.Context) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEndpoint
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Url,
			&i.Description,
			&i.SecretCiphertext,
			&i.EventTypes,
			&i.PhoneNumberID,
			&i.IsEnabled,
			&i.DisabledReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDeliveryAttempt = `-- name: RecordDeliveryAttempt :exec
UPDATE webhook_deliveries
SET status = $1, attempt_count = attempt_count + 1, last_response_code = $2,
    last_error = $3, last_attempt_at = now(), next_attempt_at = $4
WHERE id = $5
`

type RecordDeliveryAttemptParams struct {
	Status           DeliveryStatus
	LastResponseCode *int32
	LastError        *string
	NextAttemptAt    time.Time
	ID               uuid.UUID
}

func (q *Queries) RecordDeliveryAttempt(ctx context.Context, arg RecordDeliveryAttemptParams) error {
	_, err := q.db.Exec(ctx, recordDeliveryAttempt,
		arg.Status,
		arg.LastResponseCode,
		arg.LastError,
		arg.NextAttemptAt,
		arg.ID,
	)
	return err
}

const requeueDelivery = `-- name: RequeueDelivery :execrows
UPDATE webhook_deliveries SET status = 'pending', next_attempt_at = now()
WHERE id = $1 AND endpoint_id = $2
`

type RequeueDeliveryParams struct {
	ID         uuid.UUID
	EndpointID uuid.UUID
}

func (q *Queries) RequeueDelivery(ctx context.Context, arg RequeueDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueDelivery, arg.ID, arg.EndpointID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
