-- Ecogo WhatsApp Platform: release 1 database schema
-- PostgreSQL 16. Design v0.1, 2026-10-02 (docs/design/schema-v0.1.sql).
-- Companion to the Technical Design doc and the BRD (module IDs D1-D9, A1).
--
-- Conventions
--   * Primary keys are UUIDv7 generated by the Go service (time-ordered); DB default is gen_random_uuid() as a fallback.
--   * Every tenant-owned table has tenant_id and a row-level security policy keyed on the
--     session setting app.tenant_id. The application role never has BYPASSRLS.
--   * Meta identifiers (WABA ID, phone number ID, wamid, template ID) are stored as text.
--   * Secrets (BISU tokens, PINs, TOTP seeds, webhook secrets) are stored only as ciphertext produced
--     with a per-record data key (envelope encryption); data keys are wrapped by a master key held
--     outside the database (a Kubernetes Secret mounted only into the api and worker pods; later OpenBao or Vault transit).
--     API keys are stored only as hashes.
--   * Background jobs use River (Postgres-backed Go job queue); its tables come from River's own
--     migrations and are not repeated here.
--   * Times are timestamptz in UTC.

BEGIN;

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------------
-- Enumerations
-- ---------------------------------------------------------------------------

CREATE TYPE tenant_status        AS ENUM ('active', 'suspended', 'closed');
CREATE TYPE member_role          AS ENUM ('owner', 'admin', 'agent', 'developer');
CREATE TYPE connection_status    AS ENUM ('pending', 'connected', 'disconnected', 'revoked', 'error');
CREATE TYPE onboarding_flow      AS ENUM ('standard', 'coexistence');
CREATE TYPE onboarding_step      AS ENUM ('started', 'code_received', 'token_exchanged', 'webhooks_subscribed',
                                          'number_registered', 'contacts_sync_requested', 'history_sync_requested', 'details_synced',
                                          'completed', 'failed', 'cancelled');
CREATE TYPE quality_rating       AS ENUM ('green', 'yellow', 'red', 'unknown');
CREATE TYPE opt_in_status        AS ENUM ('unknown', 'opted_in', 'opted_out');
CREATE TYPE consent_kind         AS ENUM ('opt_in', 'opt_out');
CREATE TYPE consent_source       AS ENUM ('dashboard', 'api', 'csv_import', 'keyword', 'inbound_message', 'whatsapp_flow', 'coexistence_import');
CREATE TYPE conversation_status  AS ENUM ('open', 'pending', 'closed');
CREATE TYPE message_direction    AS ENUM ('inbound', 'outbound');
CREATE TYPE message_origin       AS ENUM ('customer', 'dashboard', 'api', 'campaign', 'phone_app', 'bot');
CREATE TYPE message_type         AS ENUM ('text', 'image', 'video', 'audio', 'document', 'sticker', 'location',
                                          'contacts', 'template', 'interactive', 'reaction', 'button',
                                          'order', 'system', 'unsupported');
CREATE TYPE message_status       AS ENUM ('queued', 'sent', 'delivered', 'read', 'failed', 'received', 'deleted');
CREATE TYPE template_category    AS ENUM ('marketing', 'utility', 'authentication');
CREATE TYPE template_status      AS ENUM ('draft', 'pending', 'approved', 'rejected', 'paused', 'disabled', 'in_appeal', 'deleted');
CREATE TYPE campaign_status      AS ENUM ('draft', 'scheduled', 'running', 'paused', 'completed', 'cancelled', 'failed');
CREATE TYPE recipient_status     AS ENUM ('pending', 'skipped', 'queued', 'sent', 'delivered', 'read', 'failed');
CREATE TYPE api_key_mode         AS ENUM ('live', 'sandbox');
CREATE TYPE delivery_status      AS ENUM ('pending', 'succeeded', 'retrying', 'dead');
CREATE TYPE subscription_status  AS ENUM ('trialing', 'active', 'past_due', 'cancelled');
CREATE TYPE actor_type           AS ENUM ('user', 'platform_admin', 'api_key', 'system', 'meta');

-- ---------------------------------------------------------------------------
-- D1 Account and team
-- ---------------------------------------------------------------------------

CREATE TABLE tenants (
    id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name                    text NOT NULL,
    slug                    citext NOT NULL UNIQUE,
    legal_name              text,
    status                  tenant_status NOT NULL DEFAULT 'active',
    suspended_reason        text,
    default_locale          text NOT NULL DEFAULT 'en-IN',      -- dashboard language
    timezone                text NOT NULL DEFAULT 'Asia/Kolkata',
    message_retention_days  integer CHECK (message_retention_days IS NULL OR message_retention_days >= 30),
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now()
);

-- Users are global (one login can belong to several tenants); tenant access is via memberships.
CREATE TABLE users (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email               citext NOT NULL UNIQUE,
    name                text NOT NULL,
    password_hash       text NOT NULL,                   -- argon2id encoded string
    email_verified_at   timestamptz,
    totp_secret_enc     bytea,                           -- envelope-encrypted; NULL = 2FA off
    preferred_locale    text,
    is_platform_admin   boolean NOT NULL DEFAULT false,  -- Ecogo staff (A1)
    last_login_at       timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE memberships (
    tenant_id   uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    user_id     uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role        member_role NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, user_id)
);
CREATE INDEX memberships_user_idx ON memberships (user_id);

CREATE TABLE invites (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id    uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    email        citext NOT NULL,
    role         member_role NOT NULL CHECK (role <> 'owner'),
    token_hash   bytea NOT NULL UNIQUE,
    invited_by   uuid NOT NULL REFERENCES users(id),
    expires_at   timestamptz NOT NULL,
    accepted_at  timestamptz,
    created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX invites_open_uniq ON invites (tenant_id, email) WHERE accepted_at IS NULL;

CREATE TABLE sessions (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    tenant_id     uuid REFERENCES tenants(id) ON DELETE CASCADE,  -- currently selected tenant
    token_hash    bytea NOT NULL UNIQUE,                          -- SHA-256 of the cookie value
    mfa_passed    boolean NOT NULL DEFAULT false,
    ip            inet,
    user_agent    text,
    created_at    timestamptz NOT NULL DEFAULT now(),
    last_seen_at  timestamptz NOT NULL DEFAULT now(),
    expires_at    timestamptz NOT NULL
);
CREATE INDEX sessions_user_idx ON sessions (user_id);

-- ---------------------------------------------------------------------------
-- D2 Connect WhatsApp (Embedded Signup v4) and D5 Numbers
-- ---------------------------------------------------------------------------

CREATE TABLE whatsapp_accounts (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id           uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    waba_id             text NOT NULL UNIQUE,     -- a WABA belongs to exactly one tenant
    business_id         text NOT NULL,            -- client's Meta business portfolio ID
    name                text,
    currency            text,
    timezone_id         text,
    onboarding_flow     onboarding_flow NOT NULL DEFAULT 'standard',
    status              connection_status NOT NULL DEFAULT 'pending',
    webhooks_subscribed_at timestamptz,
    connected_at        timestamptz,
    disconnected_at     timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX whatsapp_accounts_tenant_idx ON whatsapp_accounts (tenant_id);

-- Business Integration System User token per WABA. Never selected by API handlers; only metaclient reads it.
CREATE TABLE meta_credentials (
    id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id            uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    whatsapp_account_id  uuid NOT NULL REFERENCES whatsapp_accounts(id) ON DELETE CASCADE,
    token_ciphertext     bytea NOT NULL,      -- AES-256-GCM(token) with data key
    data_key_ciphertext  bytea NOT NULL,      -- data key wrapped by the master key
    master_key_version   integer NOT NULL,   -- which master key wrapped it (rotation)
    scopes               text[] NOT NULL DEFAULT '{}',
    is_active            boolean NOT NULL DEFAULT true,
    last_used_at         timestamptz,
    revoked_at           timestamptz,
    created_at           timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX meta_credentials_active_uniq ON meta_credentials (whatsapp_account_id) WHERE is_active;

CREATE TABLE phone_numbers (
    id                        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id                 uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    whatsapp_account_id       uuid NOT NULL REFERENCES whatsapp_accounts(id) ON DELETE CASCADE,
    phone_number_id           text NOT NULL UNIQUE,   -- Meta's ID; used to route webhooks
    display_phone_number      text NOT NULL,          -- e.g. "+91 98765 43210"
    verified_name             text,
    name_status               text,                   -- APPROVED, PENDING_REVIEW, DECLINED ...
    quality_rating            quality_rating NOT NULL DEFAULT 'unknown',
    messaging_limit_tier      text,                   -- TIER_250, TIER_2K, TIER_10K, TIER_100K, TIER_UNLIMITED
    code_verification_status  text,
    is_coexistence            boolean NOT NULL DEFAULT false,
    registered_at             timestamptz,
    two_step_pin_enc          bytea,                  -- envelope-encrypted 6-digit PIN we set at registration
    status                    connection_status NOT NULL DEFAULT 'pending',
    business_profile          jsonb NOT NULL DEFAULT '{}'::jsonb,  -- cached about, address, website, logo
    last_synced_at            timestamptz,
    created_at                timestamptz NOT NULL DEFAULT now(),
    updated_at                timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX phone_numbers_tenant_idx ON phone_numbers (tenant_id);

CREATE TABLE onboarding_sessions (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id         uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    user_id           uuid NOT NULL REFERENCES users(id),
    flow              onboarding_flow NOT NULL,
    step              onboarding_step NOT NULL DEFAULT 'started',
    waba_id           text,
    phone_number_id   text,
    business_id       text,
    error_code        text,
    error_message     text,
    attempts          integer NOT NULL DEFAULT 0,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX onboarding_sessions_tenant_idx ON onboarding_sessions (tenant_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- D6 Contacts and consent
-- ---------------------------------------------------------------------------

CREATE TABLE contacts (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    wa_id           text NOT NULL CHECK (wa_id ~ '^[0-9]{6,15}$'),  -- E.164 digits, no "+"
    name            text,
    profile_name    text,                    -- name from the customer's WhatsApp profile
    language        text,                    -- preferred template language, e.g. "hi", "ta", "en"
    custom_fields   jsonb NOT NULL DEFAULT '{}'::jsonb,
    opt_in_status   opt_in_status NOT NULL DEFAULT 'unknown',
    opted_in_at     timestamptz,
    opted_out_at    timestamptz,
    blocked         boolean NOT NULL DEFAULT false,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, wa_id)
);
CREATE INDEX contacts_custom_fields_gin ON contacts USING gin (custom_fields);

CREATE TABLE tags (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id  uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name       citext NOT NULL,
    color      text,
    UNIQUE (tenant_id, name)
);

CREATE TABLE contact_tags (
    tenant_id   uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    contact_id  uuid NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    tag_id      uuid NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (contact_id, tag_id)
);
CREATE INDEX contact_tags_tag_idx ON contact_tags (tag_id);

-- Append-only consent record (proof of opt-in for Meta policy and DPDP).
CREATE TABLE consent_events (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id    uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    contact_id   uuid NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    kind         consent_kind NOT NULL,
    source       consent_source NOT NULL,
    evidence     text,                         -- e.g. form URL, keyword text, import file name
    recorded_by  uuid REFERENCES users(id),
    occurred_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX consent_events_contact_idx ON consent_events (contact_id, occurred_at DESC);

-- ---------------------------------------------------------------------------
-- D3 Inbox and messaging
-- ---------------------------------------------------------------------------

CREATE TABLE conversations (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id          uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    phone_number_id    uuid NOT NULL REFERENCES phone_numbers(id) ON DELETE CASCADE,
    contact_id         uuid NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    status             conversation_status NOT NULL DEFAULT 'open',
    assignee_user_id   uuid REFERENCES users(id) ON DELETE SET NULL,
    last_inbound_at    timestamptz,     -- customer service window = last_inbound_at + 24h
    last_message_at    timestamptz,
    last_message_preview text,
    unread_count       integer NOT NULL DEFAULT 0,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),
    UNIQUE (phone_number_id, contact_id)
);
CREATE INDEX conversations_list_idx ON conversations (tenant_id, phone_number_id, last_message_at DESC);
CREATE INDEX conversations_assignee_idx ON conversations (tenant_id, assignee_user_id, status);

CREATE TABLE media (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id        uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    phone_number_id  uuid REFERENCES phone_numbers(id) ON DELETE SET NULL,
    storage_key      text NOT NULL UNIQUE,   -- object key in the S3-compatible media bucket
    mime_type        text NOT NULL,
    size_bytes       bigint NOT NULL CHECK (size_bytes > 0),
    sha256           bytea,
    filename         text,
    meta_media_id    text,             -- ID returned by Meta upload, or inbound media ID
    meta_uploaded_at timestamptz,      -- Meta keeps uploaded media for 30 days
    created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE templates (
    id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id            uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    whatsapp_account_id  uuid NOT NULL REFERENCES whatsapp_accounts(id) ON DELETE CASCADE,
    meta_template_id     text UNIQUE,
    name                 text NOT NULL CHECK (name ~ '^[a-z0-9_]{1,512}$'),
    language             text NOT NULL,          -- e.g. en, en_US, hi, ta
    category             template_category NOT NULL,
    status               template_status NOT NULL DEFAULT 'draft',
    rejected_reason      text,
    quality_score        text,
    parameter_format     text NOT NULL DEFAULT 'positional' CHECK (parameter_format IN ('positional', 'named')),
    components           jsonb NOT NULL,         -- header, body, footer, buttons as sent to Meta
    created_by           uuid REFERENCES users(id),
    submitted_at         timestamptz,
    status_updated_at    timestamptz,
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now(),
    UNIQUE (whatsapp_account_id, name, language)
);
CREATE INDEX templates_tenant_status_idx ON templates (tenant_id, status);

-- D8 (declared before messages because messages reference it)
CREATE TABLE api_keys (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id        uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name             text NOT NULL,
    prefix           text NOT NULL UNIQUE,      -- first chars shown in UI, e.g. "eco_live_3fK9"
    key_hash         bytea NOT NULL UNIQUE,     -- SHA-256 of the full key; key shown once at creation
    mode             api_key_mode NOT NULL DEFAULT 'live',
    phone_number_id  uuid REFERENCES phone_numbers(id) ON DELETE CASCADE,  -- optional scope to one number
    created_by       uuid REFERENCES users(id),
    last_used_at     timestamptz,
    revoked_at       timestamptz,
    created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX api_keys_tenant_idx ON api_keys (tenant_id);

CREATE TABLE campaigns (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id         uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    phone_number_id   uuid NOT NULL REFERENCES phone_numbers(id),
    template_id       uuid NOT NULL REFERENCES templates(id),
    name              text NOT NULL,
    audience          jsonb NOT NULL,          -- {"tags":[...], "contact_ids":[...], "filter":{...}}
    variables         jsonb NOT NULL DEFAULT '{}'::jsonb,  -- template param -> contact field or literal
    status            campaign_status NOT NULL DEFAULT 'draft',
    scheduled_at      timestamptz,
    started_at        timestamptz,
    finished_at       timestamptz,
    send_rate_per_min integer CHECK (send_rate_per_min IS NULL OR send_rate_per_min > 0),
    stats             jsonb NOT NULL DEFAULT '{}'::jsonb,  -- cached counts per recipient_status
    created_by        uuid REFERENCES users(id),
    api_key_id        uuid REFERENCES api_keys(id),
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX campaigns_tenant_idx ON campaigns (tenant_id, created_at DESC);
CREATE INDEX campaigns_due_idx ON campaigns (scheduled_at) WHERE status = 'scheduled';

-- Messages grow fastest; plan monthly range partitioning on created_at once volume needs it.
CREATE TABLE messages (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id         uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    conversation_id   uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    phone_number_id   uuid NOT NULL REFERENCES phone_numbers(id) ON DELETE CASCADE,
    contact_id        uuid NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    direction         message_direction NOT NULL,
    origin            message_origin NOT NULL,
    wamid             text UNIQUE,              -- Meta message ID; NULL while queued
    type              message_type NOT NULL,
    content           jsonb NOT NULL,           -- normalised body (text, media ref, template params ...)
    media_id          uuid REFERENCES media(id) ON DELETE SET NULL,
    template_id       uuid REFERENCES templates(id) ON DELETE SET NULL,
    reply_to_wamid    text,
    status            message_status NOT NULL,
    error_code        integer,                  -- Meta error code, e.g. 131047
    error_title       text,
    sent_by_user_id   uuid REFERENCES users(id) ON DELETE SET NULL,
    api_key_id        uuid REFERENCES api_keys(id) ON DELETE SET NULL,
    campaign_id       uuid REFERENCES campaigns(id) ON DELETE SET NULL,
    idempotency_key   text,
    pricing_category  text,                     -- marketing, utility, authentication, service
    pricing_billable  boolean,
    recipient_country text,                     -- ISO 3166-1 alpha-2, for cost estimates (D9)
    meta_timestamp    timestamptz,              -- time Meta reports for the message
    status_updated_at timestamptz NOT NULL DEFAULT now(),
    created_at        timestamptz NOT NULL DEFAULT now(),
    CHECK (direction = 'outbound' OR status IN ('received', 'deleted')),
    CHECK (direction = 'inbound' OR status <> 'received'),
    UNIQUE (tenant_id, idempotency_key)
);
CREATE INDEX messages_conversation_idx ON messages (conversation_id, created_at DESC);
CREATE INDEX messages_tenant_created_idx ON messages (tenant_id, created_at DESC);
CREATE INDEX messages_campaign_idx ON messages (campaign_id) WHERE campaign_id IS NOT NULL;

CREATE TABLE message_status_events (
    id           bigserial PRIMARY KEY,
    tenant_id    uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    message_id   uuid NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    status       message_status NOT NULL,
    error_code   integer,
    error_title  text,
    occurred_at  timestamptz NOT NULL,
    raw          jsonb
);
CREATE INDEX message_status_events_msg_idx ON message_status_events (message_id, occurred_at);

CREATE TABLE conversation_notes (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id        uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    conversation_id  uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    author_user_id   uuid NOT NULL REFERENCES users(id),
    body             text NOT NULL,
    created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX conversation_notes_conv_idx ON conversation_notes (conversation_id, created_at);

CREATE TABLE quick_replies (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id  uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    shortcut   citext NOT NULL,      -- typed as "/shortcut" in the composer
    body       text NOT NULL,
    created_by uuid REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, shortcut)
);

-- D7 Campaign recipients
CREATE TABLE campaign_recipients (
    tenant_id    uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    campaign_id  uuid NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    contact_id   uuid NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    status       recipient_status NOT NULL DEFAULT 'pending',
    skip_reason  text,                 -- opted_out, blocked, no_opt_in, duplicate
    message_id   uuid REFERENCES messages(id) ON DELETE SET NULL,
    error_code   integer,
    updated_at   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (campaign_id, contact_id)
);
CREATE INDEX campaign_recipients_pending_idx ON campaign_recipients (campaign_id) WHERE status = 'pending';

-- ---------------------------------------------------------------------------
-- D8 Developer settings: idempotency, client webhooks
-- ---------------------------------------------------------------------------

CREATE TABLE idempotency_records (
    tenant_id        uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    key              text NOT NULL,
    request_hash     bytea NOT NULL,          -- same key + different body => 422
    response_status  integer,
    response_body    jsonb,
    created_at       timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, key)
);
CREATE INDEX idempotency_records_created_idx ON idempotency_records (created_at);  -- purge after 24h

CREATE TABLE webhook_endpoints (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id         uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    url               text NOT NULL CHECK (url ~ '^https://'),
    description       text,
    secret_ciphertext bytea NOT NULL,         -- HMAC signing secret, shown once
    event_types       text[] NOT NULL,        -- message.received, message.status, template.status, number.quality ...
    phone_number_id   uuid REFERENCES phone_numbers(id) ON DELETE CASCADE,
    is_enabled        boolean NOT NULL DEFAULT true,
    disabled_reason   text,
    created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX webhook_endpoints_tenant_idx ON webhook_endpoints (tenant_id) WHERE is_enabled;

CREATE TABLE webhook_deliveries (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id          uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    endpoint_id        uuid NOT NULL REFERENCES webhook_endpoints(id) ON DELETE CASCADE,
    event_id           uuid NOT NULL,          -- stable ID sent to the client for de-duplication
    event_type         text NOT NULL,
    payload            jsonb NOT NULL,
    status             delivery_status NOT NULL DEFAULT 'pending',
    attempt_count      integer NOT NULL DEFAULT 0,
    next_attempt_at    timestamptz NOT NULL DEFAULT now(),
    last_response_code integer,
    last_error         text,
    last_attempt_at    timestamptz,
    created_at         timestamptz NOT NULL DEFAULT now(),
    UNIQUE (endpoint_id, event_id)
);
CREATE INDEX webhook_deliveries_endpoint_idx ON webhook_deliveries (endpoint_id, created_at DESC);
CREATE INDEX webhook_deliveries_due_idx ON webhook_deliveries (next_attempt_at) WHERE status IN ('pending', 'retrying');

-- ---------------------------------------------------------------------------
-- Meta webhook intake (platform-level, not tenant-scoped until routed)
-- ---------------------------------------------------------------------------

CREATE TABLE meta_webhook_events (
    id             bigserial PRIMARY KEY,
    payload_hash   bytea NOT NULL UNIQUE,    -- SHA-256 of raw body: replayed deliveries are no-ops
    received_at    timestamptz NOT NULL,
    object         text NOT NULL,            -- whatsapp_business_account
    field          text,                     -- messages, message_template_status_update, ...
    waba_id        text,
    meta_phone_number_id text,
    tenant_id      uuid REFERENCES tenants(id) ON DELETE SET NULL,
    payload        jsonb NOT NULL,
    processed_at   timestamptz,
    error          text
);
CREATE INDEX meta_webhook_events_unprocessed_idx ON meta_webhook_events (received_at) WHERE processed_at IS NULL;
CREATE INDEX meta_webhook_events_tenant_idx ON meta_webhook_events (tenant_id, received_at DESC);

CREATE TABLE meta_api_errors (
    id            bigserial PRIMARY KEY,
    tenant_id     uuid REFERENCES tenants(id) ON DELETE SET NULL,
    method        text NOT NULL,
    path          text NOT NULL,             -- Graph path with IDs, no tokens
    http_status   integer NOT NULL,
    code          integer,
    subcode       integer,
    message       text,
    fbtrace_id    text,
    occurred_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX meta_api_errors_time_idx ON meta_api_errors (occurred_at DESC);

-- Meta data deletion callback (App Review requirement)
CREATE TABLE data_deletion_requests (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    confirmation_code  text NOT NULL UNIQUE,
    meta_user_id       text NOT NULL,
    status             text NOT NULL DEFAULT 'received' CHECK (status IN ('received', 'in_progress', 'completed')),
    requested_at       timestamptz NOT NULL DEFAULT now(),
    completed_at       timestamptz
);

-- ---------------------------------------------------------------------------
-- D9 Analytics and our own billing (Tech Provider mode: no Meta re-billing)
-- ---------------------------------------------------------------------------

CREATE TABLE usage_daily (
    tenant_id         uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    phone_number_id   uuid NOT NULL REFERENCES phone_numbers(id) ON DELETE CASCADE,
    day               date NOT NULL,                -- in Asia/Kolkata
    pricing_category  text NOT NULL,                -- marketing, utility, authentication, service
    recipient_country text NOT NULL,
    origin            message_origin NOT NULL,      -- separates phone-app (coexistence) from API traffic
    sent              integer NOT NULL DEFAULT 0,
    delivered         integer NOT NULL DEFAULT 0,
    read              integer NOT NULL DEFAULT 0,
    failed            integer NOT NULL DEFAULT 0,
    billable          integer NOT NULL DEFAULT 0,
    est_meta_cost_minor bigint NOT NULL DEFAULT 0,   -- estimate in paise
    PRIMARY KEY (tenant_id, phone_number_id, day, pricing_category, recipient_country, origin)
);

CREATE TABLE plans (
    code               text PRIMARY KEY,           -- starter, growth, pro
    name               text NOT NULL,
    price_minor        bigint NOT NULL,            -- monthly price in paise (INR); amounts still to set
    currency           text NOT NULL DEFAULT 'INR',
    included_numbers   integer NOT NULL,
    included_seats     integer NOT NULL,
    extra_seat_minor   bigint NOT NULL,
    features           jsonb NOT NULL DEFAULT '{}'::jsonb,
    is_active          boolean NOT NULL DEFAULT true
);

CREATE TABLE subscriptions (
    id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id             uuid NOT NULL UNIQUE REFERENCES tenants(id) ON DELETE CASCADE,
    plan_code             text NOT NULL REFERENCES plans(code),
    status                subscription_status NOT NULL DEFAULT 'trialing',
    seats                 integer NOT NULL DEFAULT 1,
    current_period_start  timestamptz NOT NULL,
    current_period_end    timestamptz NOT NULL,
    payment_provider      text NOT NULL DEFAULT 'razorpay',
    provider_customer_id  text,                    -- Razorpay customer ID (cust_...)
    provider_subscription_id text UNIQUE,          -- Razorpay subscription ID (sub_...)
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- A1 Audit log (append-only; app role has INSERT and SELECT only)
-- ---------------------------------------------------------------------------

CREATE TABLE audit_log (
    id            bigserial PRIMARY KEY,
    tenant_id     uuid REFERENCES tenants(id) ON DELETE SET NULL,
    actor_type    actor_type NOT NULL,
    actor_id      uuid,                       -- user or api key ID
    action        text NOT NULL,              -- e.g. tenant.suspend, api_key.create, message_content.view
    target_type   text,
    target_id     text,
    reason        text,                       -- required when platform admin views message content
    ip            inet,
    metadata      jsonb NOT NULL DEFAULT '{}'::jsonb,
    occurred_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_log_tenant_idx ON audit_log (tenant_id, occurred_at DESC);
CREATE INDEX audit_log_actor_idx ON audit_log (actor_id, occurred_at DESC);

-- ---------------------------------------------------------------------------
-- Row-level security
-- The Go service runs every request in a transaction that first executes
--   SELECT set_config('app.tenant_id', $1, true);
-- Platform-admin and webhook-routing code uses the security-definer functions below,
-- never a role that bypasses RLS.
-- ---------------------------------------------------------------------------

CREATE FUNCTION current_tenant_id() RETURNS uuid
    LANGUAGE sql STABLE
    AS $$ SELECT nullif(current_setting('app.tenant_id', true), '')::uuid $$;

DO $$
DECLARE t text;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'memberships', 'invites', 'whatsapp_accounts', 'meta_credentials', 'phone_numbers',
        'onboarding_sessions', 'contacts', 'tags', 'contact_tags', 'consent_events',
        'conversations', 'media', 'templates', 'api_keys', 'campaigns', 'messages',
        'message_status_events', 'conversation_notes', 'quick_replies', 'campaign_recipients',
        'idempotency_records', 'webhook_endpoints', 'webhook_deliveries', 'usage_daily',
        'subscriptions'
    ] LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
        EXECUTE format(
            'CREATE POLICY tenant_isolation ON %I USING (tenant_id = current_tenant_id()) '
            'WITH CHECK (tenant_id = current_tenant_id())', t);
    END LOOP;
END $$;

-- Webhook routing: find the tenant for a Meta event before app.tenant_id is known.
CREATE FUNCTION route_meta_event(p_phone_number_id text, p_waba_id text)
    RETURNS uuid
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path = public
    AS $$
        SELECT coalesce(
            (SELECT tenant_id FROM phone_numbers WHERE phone_number_id = p_phone_number_id),
            (SELECT tenant_id FROM whatsapp_accounts WHERE waba_id = p_waba_id)
        )
    $$;

-- API key lookup: resolve tenant from a key hash before app.tenant_id is known.
CREATE FUNCTION resolve_api_key(p_key_hash bytea)
    RETURNS TABLE (api_key_id uuid, tenant_id uuid, mode api_key_mode, phone_number_id uuid)
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path = public
    AS $$
        SELECT k.id, k.tenant_id, k.mode, k.phone_number_id
        FROM api_keys k JOIN tenants t ON t.id = k.tenant_id
        WHERE k.key_hash = p_key_hash AND k.revoked_at IS NULL AND t.status = 'active'
    $$;

-- Roles and grants for the application role: see 000002_app_access.up.sql

COMMIT;
